igtl::LabelMetaMessage Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::LabelMetaMessage Class Reference
#include <igtlLabelMetaMessage.h>
Public Types
enum {
UNPACK_UNDEF = 0x0000 ,
UNPACK_HEADER = 0x0001 ,
UNPACK_BODY = 0x0002
}
Unpack status. They are returned by the Unpack() function.
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
int AddLabelMetaElement (LabelMetaElement::Pointer &elem)
Adds an label meta element to the list.
void AllocateBuffer ()
void AllocatePack ()
igtl_uint64 CalculateReceiveContentSize (bool &isUnpacked)
void ClearLabelMetaElement ()
Clears the all label meta elements in the list.
virtual igtl::MessageBase::Pointer Clone ()
Create a clone of this message, new memory but all internals are preserved.
int Copy (const MessageBase *mb)
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
igtl_uint64 GetBodySizeToRead ()
const char * GetBodyType ()
Gets the type of the body.
void * GetBufferBodyPointer ()
Gets a pointer to the raw byte array for the serialized body data.
igtl_uint64 GetBufferBodySize ()
Gets the size of the serialized body data.
void * GetBufferPointer ()
Gets a pointer to the raw byte array for the serialized data including the header and the body.
igtl_uint64 GetBufferSize ()
Gets the size of the serialized message data.
bool GetDebug () const
const char * GetDeviceName ()
Gets the device name.
std::string GetDeviceName () const
Gets the device name.
const char * GetDeviceType ()
Gets the device (message) type.
unsigned short GetHeaderVersion () const
Gets the message version number.
void GetLabelMetaElement (int index, LabelMetaElement::Pointer &elem)
Gets the label meta element specified by the index.
std::string GetMessageType () const
Gets the message type.
virtual const char * GetNameOfClass () const
int GetNumberOfLabelMetaElement ()
Gets the number of the label meta elements in the list.
void * GetPackBodyPointer ()
igtl_uint64 GetPackBodySize ()
void * GetPackPointer ()
igtl_uint64 GetPackSize ()
virtual int GetReferenceCount () const
void GetTimeStamp (igtl::TimeStamp::Pointer &ts)
Gets time of message creation.
int GetTimeStamp (unsigned int *sec, unsigned int *frac)
Gets time of message creation. 'sec' and 'frac' are seconds and fractions of a second respectively.
igtlNewMacro (igtl::LabelMetaMessage)
igtlTypeMacro (igtl::LabelMetaMessage, igtl::MessageBase)
igtlTypeMacro (Object, LightObject)
void InitBuffer ()
void InitPack ()
virtual int Pack ()
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
void SetDeviceName (const char *name)
Sets the device name.
void SetDeviceName (const std::string &name)
Sets the device name.
void SetDeviceType (const std::string &type)
Sets the device (message) type.
void SetHeaderVersion (unsigned short headerVersion)
Sets the message version number.
virtual int SetMessageHeader (const MessageHeader *mb)
Sets the message header.
void SetReferenceCount (int) override
void SetTimeStamp (igtl::TimeStamp::Pointer &ts)
Sets time of message creation.
int SetTimeStamp (unsigned int sec, unsigned int frac)
Sets time of message creation. 'sec' and 'frac' are seconds and fractions of a second respectively.
int Unpack (int crccheck=0)
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void AllocateBuffer (igtlUint64 contentSize)
virtual void AllocateUnpack (igtl_uint64 bodySizeToRead)
igtlUint64 CalculateContentBufferSize () override
Gets the size of the serialized content.
int CopyBody (const MessageBase *mb)
Copies the serialized body data.
int CopyHeader (const MessageBase *mb)
Copies a header from given message.
LabelMetaMessage ()
int PackContent () override
Packs (serialize) the content. Must be implemented in all child classes.
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
void UnpackBody (int crccheck, int &r)
int UnpackContent () override
Unpacks (deserialize) the content. Must be implemented in all child classes.
void UnpackHeader (int &r)
Unpack the first 58 bytes.
~LabelMetaMessage ()
Protected Attributes
unsigned char * m_Body
igtl_uint64 m_BodySizeToRead
unsigned char * m_Content
A pointer to the underlying content of a message.
std::string m_DeviceName
A character string for the device name (message name).
unsigned char * m_Header
unsigned short m_HeaderVersion
An unsigned short for the message format version.
bool m_IsBodyPacked
Packing (serialization) status for the body.
bool m_IsBodyUnpacked
Unpacking (deserialization) status for the body.
bool m_IsHeaderUnpacked
Unpacking (deserialization) status for the header.
std::vector< LabelMetaElement::Pointer > m_LabelMetaList
igtl_uint64 m_MessageSize
std::string m_ReceiveMessageType
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
std::string m_SendMessageType
A character string for the send device type (message type).
unsigned int m_TimeStampSec
unsigned int m_TimeStampSecFraction
Detailed Description
The LBMETA is used to transfer meta information for label maps, which are not available in the IMAGE message type. To retrieve voxel objects or a label map, GET_IMAGE / IMAGE can be used. But the client should be able to get a list of available structures.
Definition at line 137 of file igtlLabelMetaMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum inherited
Unpack status. They are returned by the Unpack() function.
Enumerator
UNPACK_UNDEF
UNPACK_HEADER
UNPACK_BODY
Definition at line 91 of file igtlMessageBase.h.
Constructor & Destructor Documentation
LabelMetaMessage()
igtl::LabelMetaMessage::LabelMetaMessage () protected
Definition at line 170 of file igtlLabelMetaMessage.cxx.
References m_LabelMetaList, and igtl::MessageBase::m_SendMessageType.
Referenced by igtlNewMacro().
~LabelMetaMessage()
igtl::LabelMetaMessage::~LabelMetaMessage () protected
Definition at line 177 of file igtlLabelMetaMessage.cxx.
Member Function Documentation
AddLabelMetaElement()
int igtl::LabelMetaMessage::AddLabelMetaElement (LabelMetaElement::Pointer & elem)
Adds an label meta element to the list.
Definition at line 182 of file igtlLabelMetaMessage.cxx.
References igtl::MessageBase::m_IsBodyPacked, and m_LabelMetaList.
Referenced by igtlNewMacro().
AllocateBuffer() [1/2]
void igtl::MessageBase::AllocateBuffer () inherited
AllocatePack() allocates memory for underlying buffer If m_BodySizeToRead > 0, we are allocating for receiving a message
Definition at line 685 of file igtlMessageBase.cxx.
References AllocateBuffer(), AllocateUnpack(), CalculateContentBufferSize(), and m_BodySizeToRead.
Referenced by igtl::ImageMessage2::AllocateBuffer(), AllocateBuffer(), AllocatePack(), igtl::ImageMessage2::AllocateScalars(), igtl::ImageMessage::AllocateScalars(), igtl::VideoMessage::AllocateScalars(), igtl::ColorTableMessage::AllocateTable(), Copy(), igtl::BindMessage::GetChildMessage(), igtl::BindMessage::PackContent(), igtl::CapabilityMessage::PackContent(), igtl::CommandMessage::PackContent(), igtl::GetBindMessage::PackContent(), igtl::GetColorTableMessage::PackContent(), igtl::GetImageMessage2::PackContent(), igtl::GetImageMetaMessage::PackContent(), igtl::GetLabelMetaMessage::PackContent(), igtl::GetPointMessage::PackContent(), igtl::GetPolyDataMessage::PackContent(), igtl::GetTrajectoryMessage::PackContent(), igtl::GetVideoMetaMessage::PackContent(), igtl::HeaderOnlyMessageBase::PackContent(), igtl::ImageMetaMessage::PackContent(), igtl::LabelMetaMessage::PackContent(), igtl::NDArrayMessage::PackContent(), igtl::PointMessage::PackContent(), igtl::PolyDataMessage::PackContent(), igtl::PositionMessage::PackContent(), igtl::QuaternionTrackingDataMessage::PackContent(), igtl::QueryMessage::PackContent(), igtl::RTSBindMessage::PackContent(), igtl::RTSPolyDataMessage::PackContent(), igtl::RTSQuaternionTrackingDataMessage::PackContent(), igtl::RTSTrackingDataMessage::PackContent(), igtl::SensorMessage::PackContent(), igtl::StartBindMessage::PackContent(), igtl::StartQuaternionTrackingDataMessage::PackContent(), igtl::StartTrackingDataMessage::PackContent(), igtl::StatusMessage::PackContent(), igtl::StopBindMessage::PackContent(), igtl::StopQuaternionTrackingDataMessage::PackContent(), igtl::StopTrackingDataMessage::PackContent(), igtl::StopVideoMessage::PackContent(), igtl::StringMessage::PackContent(), igtl::TrackingDataMessage::PackContent(), igtl::TrajectoryMessage::PackContent(), igtl::TransformMessage::PackContent(), and igtl::VideoMetaMessage::PackContent().
AllocateBuffer() [2/2]
void igtl::MessageBase::AllocateBuffer (igtlUint64 contentSize) protected virtual inherited
Allocates memory specifying the content size. Implicitly allocates extended header, metadata header and metadata in addition to content
Reimplemented in igtl::ImageMessage2.
Definition at line 746 of file igtlMessageBase.cxx.
References IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, m_Body, m_Content, m_Header, m_HeaderVersion, m_IsBodyPacked, m_IsBodyUnpacked, m_IsHeaderUnpacked, and m_MessageSize.
AllocatePack()
void igtl::MessageBase::AllocatePack () inline inherited
Definition at line 238 of file igtlMessageBase.h.
References AllocateBuffer().
Referenced by igtl::StartPolyDataMessage::PackBody(), igtl::StopPolyDataMessage::PackBody(), and igtl::StartVideoMessage::PackContent().
AllocateUnpack()
void igtl::MessageBase::AllocateUnpack (igtl_uint64 bodySizeToRead) protected virtual inherited
Allocates memory specifying the unpack content size Size of body to allocate is determined from v1 message header field 'body_size'
Definition at line 935 of file igtlMessageBase.cxx.
References IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, m_Body, m_Content, m_Header, m_HeaderVersion, m_IsBodyPacked, m_IsBodyUnpacked, m_IsHeaderUnpacked, and m_MessageSize.
Referenced by AllocateBuffer().
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CalculateContentBufferSize()
igtlUint64 igtl::LabelMetaMessage::CalculateContentBufferSize () override protected virtual
Gets the size of the serialized content.
Reimplemented from igtl::MessageBase.
Definition at line 211 of file igtlLabelMetaMessage.cxx.
References IGTL_LBMETA_ELEMENT_SIZE, and m_LabelMetaList.
Referenced by igtlNewMacro().
CalculateReceiveContentSize()
igtl_uint64 igtl::MessageBase::CalculateReceiveContentSize (bool & isUnpacked) inherited
Calculate the size of the received content data Returns -1 if the extended header has not been properly initialized (meta data size, meta data header size, etc...) Used when receiving data, not sending
Definition at line 647 of file igtlMessageBase.cxx.
References GetBufferSize(), IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, m_BodySizeToRead, and m_HeaderVersion.
Referenced by igtl::CapabilityMessage::UnpackContent(), igtl::NDArrayMessage::UnpackContent(), igtl::PointMessage::UnpackContent(), igtl::PolyDataMessage::UnpackContent(), igtl::PositionMessage::UnpackContent(), igtl::QuaternionTrackingDataMessage::UnpackContent(), igtl::StatusMessage::UnpackContent(), igtl::TrackingDataMessage::UnpackContent(), and igtl::TrajectoryMessage::UnpackContent().
ClearLabelMetaElement()
void igtl::LabelMetaMessage::ClearLabelMetaElement ()
Clears the all label meta elements in the list.
Definition at line 190 of file igtlLabelMetaMessage.cxx.
References m_LabelMetaList.
Referenced by igtlNewMacro().
Clone()
igtl::MessageBase::Pointer igtl::MessageBase::Clone () virtual inherited
Create a clone of this message, new memory but all internals are preserved.
Definition at line 81 of file igtlMessageBase.cxx.
References GetHeaderVersion(), GetMessageType(), IGTL_HEADER_SIZE, m_MessageSize, and igtl::LightObject::New().
Copy()
int igtl::MessageBase::Copy (const MessageBase * mb) inherited
Copy() copies contents from the specified Massage class. If the type of the specified class is the same as this class, general header and body are copied.
Definition at line 982 of file igtlMessageBase.cxx.
References AllocateBuffer(), CopyBody(), CopyHeader(), IGTL_HEADER_SIZE, m_HeaderVersion, m_MessageSize, m_ReceiveMessageType, m_SendMessageType, and MessageBase().
Referenced by SetMessageHeader().
CopyBody()
int igtl::MessageBase::CopyBody (const MessageBase * mb) protected inherited
Copies the serialized body data.
Definition at line 826 of file igtlMessageBase.cxx.
References IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, m_Body, m_Content, m_HeaderVersion, m_MessageSize, and MessageBase().
Referenced by Copy().
CopyHeader()
int igtl::MessageBase::CopyHeader (const MessageBase * mb) protected inherited
Copies a header from given message.
Definition at line 801 of file igtlMessageBase.cxx.
References IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, m_Body, m_BodySizeToRead, m_Content, m_DeviceName, m_Header, m_HeaderVersion, m_IsBodyPacked, m_IsBodyUnpacked, m_IsHeaderUnpacked, m_MessageSize, m_ReceiveMessageType, m_TimeStampSec, m_TimeStampSecFraction, and MessageBase().
Referenced by Copy().
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetBodySizeToRead()
igtl_uint64 igtl::MessageBase::GetBodySizeToRead () inherited
GetBodySizeToRead() returns the size of the body to be read. This function must be called after the message header is set.
Definition at line 1018 of file igtlMessageBase.cxx.
References m_BodySizeToRead.
GetBodyType()
const char * igtl::MessageBase::GetBodyType () inherited
Gets the type of the body.
Definition at line 670 of file igtlMessageBase.cxx.
References m_ReceiveMessageType.
GetBufferBodyPointer()
void * igtl::MessageBase::GetBufferBodyPointer () inherited
Gets a pointer to the raw byte array for the serialized body data.
Definition at line 632 of file igtlMessageBase.cxx.
References m_Body.
Referenced by igtl::BindMessageBase::AppendChildMessage(), igtl::BindMessage::GetChildMessage(), GetPackBodyPointer(), and igtl::BindMessageBase::SetChildMessage().
GetBufferBodySize()
igtl_uint64 igtl::MessageBase::GetBufferBodySize () inherited
Gets the size of the serialized body data.
Definition at line 642 of file igtlMessageBase.cxx.
References GetBufferSize(), and IGTL_HEADER_SIZE.
Referenced by igtl::BindMessageBase::AppendChildMessage(), GetPackBodySize(), Pack(), igtl::BindMessageBase::SetChildMessage(), Unpack(), igtl::BindMessage::UnpackContent(), igtl::GetBindMessage::UnpackContent(), and igtl::StartBindMessage::UnpackContent().
GetBufferPointer()
void * igtl::MessageBase::GetBufferPointer () inherited
Gets a pointer to the raw byte array for the serialized data including the header and the body.
Definition at line 627 of file igtlMessageBase.cxx.
References m_Header.
Referenced by igtl::BindMessage::GetChildMessage(), GetPackPointer(), igtl::VideoMessage::GetPackPointer(), and igtl::SessionManager::PushMessage().
GetBufferSize()
igtl_uint64 igtl::MessageBase::GetBufferSize () inherited
Gets the size of the serialized message data.
Definition at line 637 of file igtlMessageBase.cxx.
References m_MessageSize.
Referenced by CalculateReceiveContentSize(), GetBufferBodySize(), GetPackSize(), and igtl::SessionManager::PushMessage().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetDeviceName() [1/2]
const char * igtl::MessageBase::GetDeviceName () inherited
Gets the device name.
Definition at line 144 of file igtlMessageBase.cxx.
References m_DeviceName.
Referenced by igtl::BindMessageBase::AppendChildMessage(), and igtl::BindMessageBase::SetChildMessage().
GetDeviceName() [2/2]
std::string igtl::MessageBase::GetDeviceName () const inherited
Gets the device name.
Definition at line 139 of file igtlMessageBase.cxx.
References m_DeviceName.
GetDeviceType()
const char * igtl::MessageBase::GetDeviceType () inherited
Gets the device (message) type.
Definition at line 149 of file igtlMessageBase.cxx.
References m_ReceiveMessageType, and m_SendMessageType.
Referenced by igtl::BindMessageBase::AppendChildMessage(), and igtl::BindMessageBase::SetChildMessage().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetHeaderVersion()
unsigned short igtl::MessageBase::GetHeaderVersion () const inherited
Gets the message version number.
Definition at line 113 of file igtlMessageBase.cxx.
References m_HeaderVersion.
Referenced by Clone().
GetLabelMetaElement()
void igtl::LabelMetaMessage::GetLabelMetaElement (int index, LabelMetaElement::Pointer & elem)
Gets the label meta element specified by the index.
Definition at line 202 of file igtlLabelMetaMessage.cxx.
References m_LabelMetaList.
Referenced by igtlNewMacro().
GetMessageType()
std::string igtl::MessageBase::GetMessageType () const inherited
Gets the message type.
Definition at line 161 of file igtlMessageBase.cxx.
References m_ReceiveMessageType, and m_SendMessageType.
Referenced by igtl::BindMessageBase::AppendChildMessage(), Clone(), and igtl::BindMessageBase::SetChildMessage().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetNumberOfLabelMetaElement()
int igtl::LabelMetaMessage::GetNumberOfLabelMetaElement ()
Gets the number of the label meta elements in the list.
Definition at line 196 of file igtlLabelMetaMessage.cxx.
References m_LabelMetaList.
Referenced by igtlNewMacro().
GetPackBodyPointer()
void * igtl::MessageBase::GetPackBodyPointer () inline inherited
Definition at line 214 of file igtlMessageBase.h.
References GetBufferBodyPointer().
GetPackBodySize()
igtl_uint64 igtl::MessageBase::GetPackBodySize () inline inherited
Definition at line 222 of file igtlMessageBase.h.
References GetBufferBodySize().
Referenced by igtl::VideoMessage::GetBitStreamSize().
GetPackPointer()
void * igtl::MessageBase::GetPackPointer () inline inherited
Definition at line 210 of file igtlMessageBase.h.
References GetBufferPointer().
GetPackSize()
igtl_uint64 igtl::MessageBase::GetPackSize () inline inherited
Definition at line 218 of file igtlMessageBase.h.
References GetBufferSize().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetTimeStamp() [1/2]
void igtl::MessageBase::GetTimeStamp (igtl::TimeStamp::Pointer & ts) inherited
Gets time of message creation.
Definition at line 535 of file igtlMessageBase.cxx.
References igtl_frac_to_nanosec(), m_TimeStampSec, and m_TimeStampSecFraction.
GetTimeStamp() [2/2]
int igtl::MessageBase::GetTimeStamp (unsigned int * sec, unsigned int * frac) inherited
Gets time of message creation. 'sec' and 'frac' are seconds and fractions of a second respectively.
Definition at line 521 of file igtlMessageBase.cxx.
References m_TimeStampSec, and m_TimeStampSecFraction.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::LabelMetaMessage::igtlNewMacro (igtl::LabelMetaMessage)
References AddLabelMetaElement(), CalculateContentBufferSize(), ClearLabelMetaElement(), GetLabelMetaElement(), GetNumberOfLabelMetaElement(), LabelMetaMessage(), PackContent(), and UnpackContent().
igtlTypeMacro() [1/2]
igtl::LabelMetaMessage::igtlTypeMacro (igtl::LabelMetaMessage , igtl::MessageBase)
igtlTypeMacro() [2/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
InitBuffer()
void igtl::MessageBase::InitBuffer () inherited
Call InitPack() before receive header. This function simply resets the Unpacked flag for both the header and body pack Only allocate the original 58 byte header
Definition at line 699 of file igtlMessageBase.cxx.
References IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, m_Body, m_BodySizeToRead, m_Content, m_DeviceName, m_Header, m_HeaderVersion, m_IsBodyPacked, m_IsBodyUnpacked, m_IsHeaderUnpacked, m_MessageSize, and m_ReceiveMessageType.
Referenced by igtl::BindMessage::GetChildMessage(), InitPack(), and Unpack().
InitPack()
void igtl::MessageBase::InitPack () inline inherited
Definition at line 245 of file igtlMessageBase.h.
References InitBuffer().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Pack()
int igtl::MessageBase::Pack () virtual inherited
Pack() serializes the header and body based on the member variables. PackContent() must be implemented in the child class.
Reimplemented in igtl::ImageMessage2.
Definition at line 541 of file igtlMessageBase.cxx.
References igtl_header::body_size, igtl_header::crc, crc64(), igtl_header::device_name, GetBufferBodySize(), igtl_header::header_version, igtl_header_convert_byte_order(), m_Body, m_DeviceName, m_Header, m_HeaderVersion, m_IsBodyPacked, m_SendMessageType, m_TimeStampSec, m_TimeStampSecFraction, igtl_header::name, PackContent(), and igtl_header::timestamp.
Referenced by igtl::H264Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::H265Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::igtlAV1Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::VP9Encoder::EncodeSingleFrameIntoVideoMSG(), and igtl::GenericEncoder::PackUncompressedData().
PackContent()
int igtl::LabelMetaMessage::PackContent () override protected virtual
Packs (serialize) the content. Must be implemented in all child classes.
Reimplemented from igtl::MessageBase.
Definition at line 218 of file igtlLabelMetaMessage.cxx.
References igtl::MessageBase::AllocateBuffer(), igtl_lbmeta_element::device_name, igtl_lbmeta_convert_byte_order(), IGTL_LBMETA_LEN_DEVICE_NAME, IGTL_LBMETA_LEN_NAME, IGTL_LBMETA_LEN_OWNER, igtl_lbmeta_element::label, igtl::MessageBase::m_Content, m_LabelMetaList, igtl_lbmeta_element::name, igtl_lbmeta_element::owner, igtl_lbmeta_element::reserved, igtl_lbmeta_element::rgba, and igtl_lbmeta_element::size.
Referenced by igtlNewMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetDeviceName() [1/2]
void igtl::MessageBase::SetDeviceName (const char * name) inherited
Sets the device name.
Definition at line 118 of file igtlMessageBase.cxx.
References SetDeviceName().
Referenced by SetDeviceName().
SetDeviceName() [2/2]
void igtl::MessageBase::SetDeviceName (const std::string & name) inherited
Sets the device name.
Definition at line 127 of file igtlMessageBase.cxx.
References m_DeviceName, and m_IsBodyPacked.
SetDeviceType()
void igtl::MessageBase::SetDeviceType (const std::string & type) inherited
Sets the device (message) type.
Definition at line 133 of file igtlMessageBase.cxx.
References m_IsBodyPacked, and m_ReceiveMessageType.
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetHeaderVersion()
void igtl::MessageBase::SetHeaderVersion (unsigned short headerVersion) inherited
Sets the message version number.
Definition at line 107 of file igtlMessageBase.cxx.
References m_HeaderVersion, and m_IsBodyPacked.
SetMessageHeader()
int igtl::MessageBase::SetMessageHeader (const MessageHeader * mb) virtual inherited
Sets the message header.
Definition at line 1013 of file igtlMessageBase.cxx.
References Copy().
Referenced by igtl::BindMessage::GetChildMessage().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetTimeStamp() [1/2]
void igtl::MessageBase::SetTimeStamp (igtl::TimeStamp::Pointer & ts) inherited
Sets time of message creation.
Definition at line 528 of file igtlMessageBase.cxx.
References igtl_nanosec_to_frac(), m_TimeStampSec, and m_TimeStampSecFraction.
SetTimeStamp() [2/2]
int igtl::MessageBase::SetTimeStamp (unsigned int sec, unsigned int frac) inherited
Sets time of message creation. 'sec' and 'frac' are seconds and fractions of a second respectively.
Definition at line 514 of file igtlMessageBase.cxx.
References m_TimeStampSec, and m_TimeStampSecFraction.
Unpack()
int igtl::MessageBase::Unpack (int crccheck = 0) inherited
Unpack() deserializes the header and/or body, extracting data from the byte stream. If the header has already been deserilized, Unpack() deserializes only the body part. UnpackBody() must be implemented to deserialize the body part. Unpack() performs 64-bit CRC check, when crccheck = 1. It returns:
UNPACK_UNDEF : Nothing deserialized UNPACK_HEADER : The header has been deserialized. UNPACK_BODY : The body has been deserialized. If CRC check fails, Unpack() doesn't deserialize the body, thus it doesn't return UNPACK_BODY flag. UNPACK_HEADER|UNPACK_BODY: Both the header and body have been deserialized
Definition at line 591 of file igtlMessageBase.cxx.
References GetBufferBodySize(), IGTL_HEADER_SIZE, IGTL_HEADER_VERSION_2, InitBuffer(), m_Header, m_HeaderVersion, m_IsBodyUnpacked, m_IsHeaderUnpacked, m_MessageSize, UNPACK_UNDEF, UnpackBody(), and UnpackHeader().
Referenced by igtl::BindMessage::GetChildMessage().
UnpackBody()
void igtl::MessageBase::UnpackBody (int crccheck, int & r) protected inherited
Unpack the body If it's a v3 message, body is ext header + content + metadataheader + metadata<optional>
Definition at line 891 of file igtlMessageBase.cxx.
References igtl_header::crc, crc64(), igtl_header::header_version, m_Body, m_BodySizeToRead, m_Header, m_IsBodyUnpacked, UNPACK_BODY, and UnpackContent().
Referenced by Unpack().
UnpackContent()
int igtl::LabelMetaMessage::UnpackContent () override protected virtual
Unpacks (deserialize) the content. Must be implemented in all child classes.
Reimplemented from igtl::MessageBase.
Definition at line 258 of file igtlLabelMetaMessage.cxx.
References igtl_lbmeta_element::device_name, igtl_lbmeta_convert_byte_order(), igtl_lbmeta_get_data_n, IGTL_LBMETA_LEN_DEVICE_NAME, IGTL_LBMETA_LEN_NAME, IGTL_LBMETA_LEN_OWNER, igtl_lbmeta_element::label, igtl::MessageBase::m_BodySizeToRead, igtl::MessageBase::m_Content, m_LabelMetaList, igtl_lbmeta_element::name, igtl::LightObject::New(), igtl_lbmeta_element::owner, igtl_lbmeta_element::rgba, and igtl_lbmeta_element::size.
Referenced by igtlNewMacro().
UnpackHeader()
void igtl::MessageBase::UnpackHeader (int & r) protected inherited
Unpack the first 58 bytes.
Definition at line 860 of file igtlMessageBase.cxx.
References igtl_header::body_size, igtl_header::device_name, igtl_header::header_version, igtl_header_convert_byte_order(), IGTL_HEADER_NAME_SIZE, IGTL_HEADER_TYPE_SIZE, m_BodySizeToRead, m_DeviceName, m_Header, m_HeaderVersion, m_IsHeaderUnpacked, m_ReceiveMessageType, m_TimeStampSec, m_TimeStampSecFraction, igtl_header::name, igtl_header::timestamp, and UNPACK_HEADER.
Referenced by Unpack().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_Body
unsigned char* igtl::MessageBase::m_Body protected inherited
A pointer to the byte array for the serialized body. To prevent large copy of the byte array in the Pack() function, header byte array is concatenated to the byte array for the header.
Definition at line 304 of file igtlMessageBase.h.
Referenced by igtl::ImageMessage2::AllocateBuffer(), AllocateBuffer(), igtl::ImageMessage::AllocateScalars(), igtl::VideoMessage::AllocateScalars(), AllocateUnpack(), CopyBody(), CopyHeader(), GetBufferBodyPointer(), InitBuffer(), MessageBase(), Pack(), igtl::CommandMessage::PackContent(), igtl::PositionMessage::PackContent(), igtl::QueryMessage::PackContent(), igtl::RTSPolyDataMessage::PackContent(), igtl::StringMessage::PackContent(), igtl::TransformMessage::PackContent(), igtl::VideoMessage::PackContent(), UnpackBody(), igtl::CommandMessage::UnpackContent(), igtl::ImageMessage::UnpackContent(), igtl::PointMessage::UnpackContent(), igtl::PositionMessage::UnpackContent(), igtl::QuaternionTrackingDataMessage::UnpackContent(), igtl::QueryMessage::UnpackContent(), igtl::RTSPolyDataMessage::UnpackContent(), igtl::StringMessage::UnpackContent(), igtl::TrajectoryMessage::UnpackContent(), igtl::VideoMessage::UnpackContent(), igtl::VideoMessage::VideoMessage(), and ~MessageBase().
m_BodySizeToRead
igtl_uint64 igtl::MessageBase::m_BodySizeToRead protected inherited
The size of the body to be read. This function must be called after the message header is set.
Definition at line 311 of file igtlMessageBase.h.
Referenced by AllocateBuffer(), CalculateReceiveContentSize(), CopyHeader(), GetBodySizeToRead(), InitBuffer(), MessageBase(), UnpackBody(), igtl::ImageMetaMessage::UnpackContent(), igtl::LabelMetaMessage::UnpackContent(), igtl::PointMessage::UnpackContent(), igtl::QuaternionTrackingDataMessage::UnpackContent(), igtl::TrajectoryMessage::UnpackContent(), igtl::VideoMetaMessage::UnpackContent(), and UnpackHeader().
m_Content
unsigned char* igtl::MessageBase::m_Content protected inherited
A pointer to the underlying content of a message.
Definition at line 307 of file igtlMessageBase.h.
Referenced by AllocateBuffer(), igtl::ImageMessage2::AllocateScalars(), igtl::ImageMessage::AllocateScalars(), igtl::ColorTableMessage::AllocateTable(), AllocateUnpack(), CopyBody(), CopyHeader(), igtl::ImageMessage2::ImageMessage2(), InitBuffer(), MessageBase(), igtl::BindMessage::PackContent(), igtl::CapabilityMessage::PackContent(), igtl::CommandMessage::PackContent(), igtl::GetBindMessage::PackContent(), igtl::ImageMetaMessage::PackContent(), igtl::LabelMetaMessage::PackContent(), igtl::NDArrayMessage::PackContent(), igtl::PointMessage::PackContent(), igtl::PolyDataMessage::PackContent(), igtl::PositionMessage::PackContent(), igtl::QuaternionTrackingDataMessage::PackContent(), igtl::QueryMessage::PackContent(), igtl::RTSBindMessage::PackContent(), igtl::RTSPolyDataMessage::PackContent(), igtl::RTSQuaternionTrackingDataMessage::PackContent(), igtl::RTSTrackingDataMessage::PackContent(), igtl::SensorMessage::PackContent(), igtl::StartBindMessage::PackContent(), igtl::StartQuaternionTrackingDataMessage::PackContent(), igtl::StartTrackingDataMessage::PackContent(), igtl::StartVideoMessage::PackContent(), igtl::StatusMessage::PackContent(), igtl::StringMessage::PackContent(), igtl::TrackingDataMessage::PackContent(), igtl::TrajectoryMessage::PackContent(), igtl::TransformMessage::PackContent(), igtl::VideoMetaMessage::PackContent(), igtl::ImageMessage2::SetScalarPointer(), igtl::TransformMessage::TransformMessage(), igtl::BindMessage::UnpackContent(), igtl::CapabilityMessage::UnpackContent(), igtl::ColorTableMessage::UnpackContent(), igtl::CommandMessage::UnpackContent(), igtl::GetBindMessage::UnpackContent(), igtl::ImageMessage2::UnpackContent(), igtl::ImageMessage::UnpackContent(), igtl::ImageMetaMessage::UnpackContent(), igtl::LabelMetaMessage::UnpackContent(), igtl::NDArrayMessage::UnpackContent(), igtl::PointMessage::UnpackContent(), igtl::PolyDataMessage::UnpackContent(), igtl::PositionMessage::UnpackContent(), igtl::QuaternionTrackingDataMessage::UnpackContent(), igtl::QueryMessage::UnpackContent(), igtl::RTSBindMessage::UnpackContent(), igtl::RTSPolyDataMessage::UnpackContent(), igtl::RTSQuaternionTrackingDataMessage::UnpackContent(), igtl::RTSTrackingDataMessage::UnpackContent(), igtl::SensorMessage::UnpackContent(), igtl::StartBindMessage::UnpackContent(), igtl::StartQuaternionTrackingDataMessage::UnpackContent(), igtl::StartTrackingDataMessage::UnpackContent(), igtl::StartVideoMessage::UnpackContent(), igtl::StatusMessage::UnpackContent(), igtl::StringMessage::UnpackContent(), igtl::TrackingDataMessage::UnpackContent(), igtl::TrajectoryMessage::UnpackContent(), igtl::TransformMessage::UnpackContent(), igtl::VideoMetaMessage::UnpackContent(), igtl::ImageMessage2::~ImageMessage2(), and ~MessageBase().
m_DeviceName
std::string igtl::MessageBase::m_DeviceName protected inherited
A character string for the device name (message name).
Definition at line 324 of file igtlMessageBase.h.
Referenced by CopyHeader(), GetDeviceName(), GetDeviceName(), InitBuffer(), MessageBase(), igtl::ImageMessage2::Pack(), Pack(), SetDeviceName(), and UnpackHeader().
m_Header
unsigned char* igtl::MessageBase::m_Header protected inherited
A pointer to the byte array for the serialized header. To prevent large copy of the byte array in the Pack() function, header byte array is concatenated to the byte array for the body.
Definition at line 299 of file igtlMessageBase.h.
Referenced by AllocateBuffer(), AllocateUnpack(), CopyHeader(), igtl::ImageMessage2::GetBufferPointer(), GetBufferPointer(), igtl::ImageMessage2::GetPackFragmentPointer(), igtl::VideoMessage::GetPackFragmentPointer(), igtl::ImageMessage2::ImageMessage2(), InitBuffer(), MessageBase(), igtl::ImageMessage2::Pack(), Pack(), Unpack(), UnpackBody(), UnpackHeader(), and ~MessageBase().
m_HeaderVersion
unsigned short igtl::MessageBase::m_HeaderVersion protected inherited
An unsigned short for the message format version.
Definition at line 321 of file igtlMessageBase.h.
Referenced by AllocateBuffer(), igtl::VideoMessage::AllocateScalars(), AllocateUnpack(), CalculateReceiveContentSize(), igtl::CapabilityMessage::CapabilityMessage(), igtl::ColorTableMessage::ColorTableMessage(), igtl::CommandMessage::CommandMessage(), Copy(), CopyBody(), CopyHeader(), igtl::VideoMessage::GetBitStreamSize(), GetHeaderVersion(), InitBuffer(), MessageBase(), Pack(), igtl::TransformMessage::PackContent(), igtl::VideoMessage::PackContent(), igtl::VideoMessage::SetBitStreamSize(), SetHeaderVersion(), Unpack(), igtl::TransformMessage::UnpackContent(), igtl::VideoMessage::UnpackContent(), igtl::VideoMetaMessage::UnpackContent(), and UnpackHeader().
m_IsBodyPacked
bool igtl::MessageBase::m_IsBodyPacked protected inherited
Packing (serialization) status for the body.
Definition at line 341 of file igtlMessageBase.h.
Referenced by igtl::PolyDataMessage::AddAttribute(), igtl::ImageMetaMessage::AddImageMetaElement(), igtl::LabelMetaMessage::AddLabelMetaElement(), igtl::PointMessage::AddPointElement(), igtl::TrackingDataMessage::AddTrackingDataElement(), igtl::TrajectoryMessage::AddTrajectoryElement(), AllocateBuffer(), AllocateUnpack(), igtl::BindMessageBase::AppendChildMessage(), igtl::GetBindMessage::AppendChildMessage(), CopyHeader(), igtl::VideoMessage::GetPackedBitStreamSize(), InitBuffer(), MessageBase(), Pack(), igtl::NDArrayMessage::SetArray(), igtl::BindMessageBase::SetChildMessage(), igtl::StatusMessage::SetCode(), igtl::CommandMessage::SetCommandContent(), igtl::CommandMessage::SetCommandContent(), igtl::RTSCommandMessage::SetCommandErrorString(), igtl::RTSCommandMessage::SetCommandErrorString(), igtl::CommandMessage::SetCommandId(), igtl::CommandMessage::SetCommandName(), igtl::CommandMessage::SetContentEncoding(), SetDeviceName(), SetDeviceType(), igtl::ImageMessage2::SetDimensions(), igtl::ImageMessage2::SetDimensions(), igtl::ImageMessage::SetDimensions(), igtl::ImageMessage::SetDimensions(), igtl::StringMessage::SetEncoding(), igtl::StatusMessage::SetErrorName(), SetHeaderVersion(), igtl::ImageMessage2::SetMatrix(), igtl::ImageMessage::SetMatrix(), igtl::TransformMessage::SetMatrix(), igtl::ImageMessage2::SetNormals(), igtl::ImageMessage2::SetNormals(), igtl::ImageMessage::SetNormals(), igtl::ImageMessage::SetNormals(), igtl::TransformMessage::SetNormals(), igtl::TransformMessage::SetNormals(), igtl::BindMessageBase::SetNumberOfChildMessages(), igtl::ImageMessage2::SetOrigin(), igtl::ImageMessage2::SetOrigin(), igtl::ImageMessage::SetOrigin(), igtl::ImageMessage::SetOrigin(), igtl::PositionMessage::SetPackTypeByContentSize(), igtl::PositionMessage::SetPosition(), igtl::PositionMessage::SetPosition(), igtl::TransformMessage::SetPosition(), igtl::TransformMessage::SetPosition(), igtl::PositionMessage::SetQuaternion(), igtl::PositionMessage::SetQuaternion(), igtl::StartBindMessage::SetResolution(), igtl::ImageMessage2::SetSpacing(), igtl::ImageMessage2::SetSpacing(), igtl::ImageMessage::SetSpacing(), igtl::ImageMessage::SetSpacing(), igtl::RTSPolyDataMessage::SetStatus(), igtl::StatusMessage::SetStatusString(), igtl::StringMessage::SetString(), igtl::StringMessage::SetString(), igtl::StatusMessage::SetSubCode(), igtl::ImageMessage2::SetSubVolume(), igtl::ImageMessage2::SetSubVolume(), igtl::ImageMessage::SetSubVolume(), igtl::ImageMessage::SetSubVolume(), igtl::CapabilityMessage::SetType(), and igtl::CapabilityMessage::SetTypes().
m_IsBodyUnpacked
bool igtl::MessageBase::m_IsBodyUnpacked protected inherited
Unpacking (deserialization) status for the body.
Definition at line 338 of file igtlMessageBase.h.
Referenced by igtl::ImageMessage2::AllocateBuffer(), AllocateBuffer(), AllocateUnpack(), CopyHeader(), InitBuffer(), MessageBase(), igtl::ImageMessage2::Pack(), Unpack(), and UnpackBody().
m_IsHeaderUnpacked
bool igtl::MessageBase::m_IsHeaderUnpacked protected inherited
Unpacking (deserialization) status for the header.
Definition at line 335 of file igtlMessageBase.h.
Referenced by igtl::ImageMessage2::AllocateBuffer(), AllocateBuffer(), AllocateUnpack(), CopyHeader(), InitBuffer(), MessageBase(), igtl::ImageMessage2::Pack(), Unpack(), and UnpackHeader().
m_LabelMetaList
std::vector<LabelMetaElement::Pointer> igtl::LabelMetaMessage::m_LabelMetaList protected
Definition at line 169 of file igtlLabelMetaMessage.h.
Referenced by AddLabelMetaElement(), CalculateContentBufferSize(), ClearLabelMetaElement(), GetLabelMetaElement(), GetNumberOfLabelMetaElement(), LabelMetaMessage(), PackContent(), and UnpackContent().
m_MessageSize
igtl_uint64 igtl::MessageBase::m_MessageSize protected inherited
Definition at line 294 of file igtlMessageBase.h.
Referenced by igtl::ImageMessage2::AllocateBuffer(), AllocateBuffer(), igtl::ImageMessage2::AllocateScalars(), AllocateUnpack(), Clone(), Copy(), CopyBody(), CopyHeader(), igtl::ImageMessage2::GetBufferPointer(), GetBufferSize(), igtl::ImageMessage2::ImageMessage2(), InitBuffer(), MessageBase(), igtl::VideoMessage::SetBitStreamSize(), Unpack(), and ~MessageBase().
m_ReceiveMessageType
std::string igtl::MessageBase::m_ReceiveMessageType protected inherited
A character string for the device type (message type). This will be used when the header is deserialized from a byte stream received from the network.
Definition at line 318 of file igtlMessageBase.h.
Referenced by Copy(), CopyHeader(), GetBodyType(), GetDeviceType(), GetMessageType(), InitBuffer(), MessageBase(), SetDeviceType(), and UnpackHeader().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_SendMessageType
std::string igtl::MessageBase::m_SendMessageType protected inherited
A character string for the send device type (message type).
Definition at line 314 of file igtlMessageBase.h.
Referenced by igtl::BindMessageBase::AppendChildMessage(), igtl::BindMessage::BindMessage(), igtl::CapabilityMessage::CapabilityMessage(), igtl::ColorTableMessage::ColorTableMessage(), igtl::CommandMessage::CommandMessage(), Copy(), igtl::GetBindMessage::GetBindMessage(), igtl::GetColorTableMessage::GetColorTableMessage(), GetDeviceType(), igtl::GetImageMessage::GetImageMessage(), igtl::GetImageMessage2::GetImageMessage2(), igtl::GetImageMetaMessage::GetImageMetaMessage(), igtl::GetLabelMetaMessage::GetLabelMetaMessage(), GetMessageType(), igtl::GetPointMessage::GetPointMessage(), igtl::GetPolyDataMessage::GetPolyDataMessage(), igtl::GetStatusMessage::GetStatusMessage(), igtl::GetTrajectoryMessage::GetTrajectoryMessage(), igtl::GetTransformMessage::GetTransformMessage(), igtl::GetVideoMetaMessage::GetVideoMetaMessage(), igtl::HeaderOnlyMessageBase::HeaderOnlyMessageBase(), igtl::ImageMessage::ImageMessage(), igtl::ImageMessage2::ImageMessage2(), igtl::ImageMetaMessage::ImageMetaMessage(), igtl::LabelMetaMessage::LabelMetaMessage(), MessageBase(), igtl::NDArrayMessage::NDArrayMessage(), igtl::ImageMessage2::Pack(), Pack(), igtl::PointMessage::PointMessage(), igtl::PolyDataMessage::PolyDataMessage(), igtl::PositionMessage::PositionMessage(), igtl::QuaternionTrackingDataMessage::QuaternionTrackingDataMessage(), igtl::QueryMessage::QueryMessage(), igtl::RTSBindMessage::RTSBindMessage(), igtl::RTSCommandMessage::RTSCommandMessage(), igtl::RTSPolyDataMessage::RTSPolyDataMessage(), igtl::RTSQuaternionTrackingDataMessage::RTSQuaternionTrackingDataMessage(), igtl::RTSTrackingDataMessage::RTSTrackingDataMessage(), igtl::SensorMessage::SensorMessage(), igtl::BindMessageBase::SetChildMessage(), igtl::StartBindMessage::StartBindMessage(), igtl::StartPolyDataMessage::StartPolyDataMessage(), igtl::StartQuaternionTrackingDataMessage::StartQuaternionTrackingDataMessage(), igtl::StartTrackingDataMessage::StartTrackingDataMessage(), igtl::StartVideoMessage::StartVideoMessage(), igtl::StatusMessage::StatusMessage(), igtl::StopBindMessage::StopBindMessage(), igtl::StopImageMessage::StopImageMessage(), igtl::StopPolyDataMessage::StopPolyDataMessage(), igtl::StopQuaternionTrackingDataMessage::StopQuaternionTrackingDataMessage(), igtl::StopTrackingDataMessage::StopTrackingDataMessage(), igtl::StopVideoMessage::StopVideoMessage(), igtl::StringMessage::StringMessage(), igtl::TrackingDataMessage::TrackingDataMessage(), igtl::TrajectoryMessage::TrajectoryMessage(), igtl::TransformMessage::TransformMessage(), igtl::VideoMessage::VideoMessage(), and igtl::VideoMetaMessage::VideoMetaMessage().
m_TimeStampSec
unsigned int igtl::MessageBase::m_TimeStampSec protected inherited
A time stamp (second) for message creation. It consists of fields for seconds (m_TimeStampSec)and fractions of a second (m_TimeStampSecFraction).
Definition at line 328 of file igtlMessageBase.h.
Referenced by CopyHeader(), igtl::BindMessage::GetChildMessage(), GetTimeStamp(), GetTimeStamp(), MessageBase(), igtl::ImageMessage2::Pack(), Pack(), SetTimeStamp(), SetTimeStamp(), and UnpackHeader().
m_TimeStampSecFraction
unsigned int igtl::MessageBase::m_TimeStampSecFraction protected inherited
A time stamp (second) for message creation. It consists of fields for seconds (m_TimeStampSec)and fractions of a second (m_TimeStampSecFraction).
Definition at line 332 of file igtlMessageBase.h.
Referenced by CopyHeader(), igtl::BindMessage::GetChildMessage(), GetTimeStamp(), GetTimeStamp(), MessageBase(), igtl::ImageMessage2::Pack(), Pack(), SetTimeStamp(), SetTimeStamp(), and UnpackHeader().
The documentation for this class was generated from the following files:
igtlLabelMetaMessage.h
igtlLabelMetaMessage.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012