igtl::ObjectFactoryBase Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::ObjectFactoryBase Class Reference abstract
Create instances of classes using an object factory.
#include <igtlObjectFactoryBase.h>
Data Structures
class OverrideInformation
Internal implementation class for ObjectFactorBase.
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
virtual void Disable (const char *className)
virtual std::list< std::string > GetClassOverrideDescriptions ()
virtual std::list< std::string > GetClassOverrideNames ()
virtual std::list< std::string > GetClassOverrideWithNames ()
bool GetDebug () const
virtual const char * GetDescription (void) const =0
virtual bool GetEnableFlag (const char *className, const char *subclassName)
virtual std::list< bool > GetEnableFlags ()
virtual const char * GetIGTLSourceVersion (void) const =0
const char * GetLibraryPath ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (ObjectFactoryBase, Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
virtual void SetEnableFlag (bool flag, const char *className, const char *subclassName)
void SetReferenceCount (int) override
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static std::list< LightObject::Pointer > CreateAllInstance (const char *igtlclassname)
static LightObject::Pointer CreateInstance (const char *igtlclassname)
static bool GetGlobalWarningDisplay ()
static std::list< ObjectFactoryBase * > GetRegisteredFactories ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void RegisterFactory (ObjectFactoryBase *)
static void ReHash ()
static void SetGlobalWarningDisplay (bool flag)
static void UnRegisterAllFactories ()
static void UnRegisterFactory (ObjectFactoryBase *)
Protected Member Functions
virtual LightObject::Pointer CreateObject (const char *igtlclassname)
ObjectFactoryBase ()
virtual void PrintHeader (std::ostream &os) const
void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
void RegisterOverride (const char *classOverride, const char *overrideClassName, const char *description, bool enableFlag, CreateObjectFunctionBase *createFunction)
virtual ~ObjectFactoryBase ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Create instances of classes using an object factory.
ObjectFactoryBase is used to create igtl objects. The base class ObjectFactoryBase contains a static method CreateInstance() that is used to create igtl objects from the list of registerd ObjectFactoryBase sub-classes. The first time CreateInstance() is called, all dll's or shared libraries in the environment variable IGTL_AUTOLOAD_PATH are loaded into the current process. The C function igtlLoad is called on each dll. igtlLoad should return an instance of the factory sub-class implemented in the shared library. IGTL_AUTOLOAD_PATH is an environment variable containing a colon separated (semi-colon on win32) list of paths.
This can be use to overide the creation of any object in IGTL.
Definition at line 63 of file igtlObjectFactoryBase.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
ObjectFactoryBase()
igtl::ObjectFactoryBase::ObjectFactoryBase () protected
initialize class members
Definition at line 406 of file igtlObjectFactoryBase.cxx.
Referenced by igtlTypeMacro(), RegisterFactory(), and UnRegisterFactory().
~ObjectFactoryBase()
igtl::ObjectFactoryBase::~ObjectFactoryBase () protected virtual
Unload the library and free the path string
Definition at line 417 of file igtlObjectFactoryBase.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAllInstance()
std::list< LightObject::Pointer > igtl::ObjectFactoryBase::CreateAllInstance (const char * igtlclassname) static
Create and return all possible instances of the named igtl object. Each loaded ObjectFactoryBase will be asked in the order the factory was in the IGTL_AUTOLOAD_PATH. All created objects will be returned in the list.
Definition at line 144 of file igtlObjectFactoryBase.cxx.
Referenced by igtlTypeMacro().
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
CreateInstance()
LightObject::Pointer igtl::ObjectFactoryBase::CreateInstance (const char * igtlclassname) static
Create and return an instance of the named igtl object. Each loaded ObjectFactoryBase will be asked in the order the factory was in the IGTL_AUTOLOAD_PATH. After the first factory returns the object no other factories are asked.
Create an instance of a named igtl object using the loaded factories
Definition at line 120 of file igtlObjectFactoryBase.cxx.
Referenced by igtl::ObjectFactory< T >::Create(), and igtlTypeMacro().
CreateObject()
LightObject::Pointer igtl::ObjectFactoryBase::CreateObject (const char * igtlclassname) protected virtual
This method is provided by sub-classes of ObjectFactoryBase. It should create the named igtl object or return 0 if that object is not supported by the factory implementation.
Definition at line 571 of file igtlObjectFactoryBase.cxx.
References igtl::end().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
Disable()
void igtl::ObjectFactoryBase::Disable (const char * className) virtual
Set all enable flags for the given class to 0. This will mean that the factory will stop producing class with the given name.
Definition at line 633 of file igtlObjectFactoryBase.cxx.
References igtl::end().
Referenced by GetDescription().
GetClassOverrideDescriptions()
std::list< std::string > igtl::ObjectFactoryBase::GetClassOverrideDescriptions () virtual
Return a list of descriptions for class overrides.
Retrun a list of descriptions for class overrides
Definition at line 694 of file igtlObjectFactoryBase.cxx.
Referenced by GetDescription().
GetClassOverrideNames()
std::list< std::string > igtl::ObjectFactoryBase::GetClassOverrideNames () virtual
Return a list of classes that this factory overrides.
Definition at line 660 of file igtlObjectFactoryBase.cxx.
Referenced by GetDescription().
GetClassOverrideWithNames()
std::list< std::string > igtl::ObjectFactoryBase::GetClassOverrideWithNames () virtual
Return a list of the names of classes that override classes.
Definition at line 677 of file igtlObjectFactoryBase.cxx.
Referenced by GetDescription().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetDescription()
virtual const char * igtl::ObjectFactoryBase::GetDescription (void) const pure virtual
Return a descriptive string describing the factory.
References Disable(), GetClassOverrideDescriptions(), GetClassOverrideNames(), GetClassOverrideWithNames(), GetEnableFlag(), GetEnableFlags(), GetLibraryPath(), and SetEnableFlag().
Referenced by PrintSelf().
GetEnableFlag()
bool igtl::ObjectFactoryBase::GetEnableFlag (const char * className, const char * subclassName) virtual
Get the Enable flag for the specific override of className.
Definition at line 613 of file igtlObjectFactoryBase.cxx.
References igtl::end().
Referenced by GetDescription().
GetEnableFlags()
std::list< bool > igtl::ObjectFactoryBase::GetEnableFlags () virtual
Return a list of enable flags.
Return a list of enable flags
Definition at line 711 of file igtlObjectFactoryBase.cxx.
Referenced by GetDescription().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetIGTLSourceVersion()
virtual const char * igtl::ObjectFactoryBase::GetIGTLSourceVersion (void) const pure virtual
All sub-classes of ObjectFactoryBase should must return the version of IGTL they were built with. This should be implemented with the macro IGTL_SOURCE_VERSION and NOT a call to Version::GetIGTLSourceVersion. As the version needs to be compiled into the file as a string constant. This is critical to determine possible incompatible dynamic factory loads.
GetLibraryPath()
const char * igtl::ObjectFactoryBase::GetLibraryPath ()
This returns the path to a dynamically loaded factory.
Return the path to a dynamically loaded factory.
Definition at line 726 of file igtlObjectFactoryBase.cxx.
Referenced by GetDescription().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetRegisteredFactories()
std::list< ObjectFactoryBase * > igtl::ObjectFactoryBase::GetRegisteredFactories () static
Return the list of all registered factories. This is NOT a copy, do not remove items from this list!
Definition at line 649 of file igtlObjectFactoryBase.cxx.
Referenced by igtlTypeMacro().
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::ObjectFactoryBase::igtlTypeMacro (ObjectFactoryBase , Object)
Run-time type information (and related methods).
References CreateAllInstance(), CreateInstance(), GetRegisteredFactories(), igtl::Object::Object(), ObjectFactoryBase(), RegisterFactory(), ReHash(), UnRegisterAllFactories(), and UnRegisterFactory().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::ObjectFactoryBase::PrintSelf (std::ostream & os) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::Object.
Definition at line 456 of file igtlObjectFactoryBase.cxx.
References GetDescription().
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
RegisterFactory()
void igtl::ObjectFactoryBase::RegisterFactory (ObjectFactoryBase * factory) static
Register a factory so it can be used to create igtl objects.
Add a factory to the registered list
Definition at line 429 of file igtlObjectFactoryBase.cxx.
References ObjectFactoryBase(), and igtl::Object::Register().
Referenced by igtlTypeMacro().
RegisterOverride()
void igtl::ObjectFactoryBase::RegisterOverride (const char * classOverride, const char * overrideClassName, const char * description, bool enableFlag, CreateObjectFunctionBase * createFunction) protected
Register object creation information with the factory.
Definition at line 552 of file igtlObjectFactoryBase.cxx.
References igtl::ObjectFactoryBase::OverrideInformation::m_CreateObject, igtl::ObjectFactoryBase::OverrideInformation::m_Description, igtl::ObjectFactoryBase::OverrideInformation::m_EnabledFlag, and igtl::ObjectFactoryBase::OverrideInformation::m_OverrideWithName.
ReHash()
void igtl::ObjectFactoryBase::ReHash () static
Re-check the IGTL_AUTOLOAD_PATH for new factory libraries. This calls UnRegisterAll before re-loading.
A file scoped function to determine if a file has the shared library extension in its name, this converts name to lower case before the compare, DynamicLoader always uses lower case for LibExtension values. Attempt to load each file in the directory as a shared library try to make sure the file has at least the extension for a shared library in it. Look for the symbol igtlLoad in the library if the symbol is found call it to create the factory from the library initialize class members if load worked Recheck the IGTL_AUTOLOAD_PATH for new libraries
Definition at line 395 of file igtlObjectFactoryBase.cxx.
References UnRegisterAllFactories().
Referenced by igtlTypeMacro().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetEnableFlag()
void igtl::ObjectFactoryBase::SetEnableFlag (bool flag, const char * className, const char * subclassName) virtual
Set the Enable flag for the specific override of className.
Definition at line 592 of file igtlObjectFactoryBase.cxx.
References igtl::end().
Referenced by GetDescription().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
UnRegisterAllFactories()
void igtl::ObjectFactoryBase::UnRegisterAllFactories () static
Unregister all factories.
unregister all factories and delete the RegisteredFactories list
Definition at line 510 of file igtlObjectFactoryBase.cxx.
Referenced by igtlTypeMacro(), and ReHash().
UnRegisterFactory()
void igtl::ObjectFactoryBase::UnRegisterFactory (ObjectFactoryBase * factory) static
Remove a factory from the list of registered factories.
Definition at line 489 of file igtlObjectFactoryBase.cxx.
References ObjectFactoryBase(), and igtl::Object::UnRegister().
Referenced by igtlTypeMacro().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlObjectFactoryBase.h
igtlObjectFactoryBase.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012