igtl::ConditionVariable Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::ConditionVariable Class Reference
A thread synchronization object used to suspend execution until some condition on shared data is met.
#include <igtlConditionVariable.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
void Broadcast ()
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlNewMacro (Self)
igtlTypeMacro (ConditionVariable, LightObject)
void Print (std::ostream &os) const
virtual void Register () const
virtual void SetReferenceCount (int)
void Signal ()
virtual void UnRegister () const
void Wait (SimpleMutexLock *mutex)
bool Wait (SimpleMutexLock *mutex, igtl_uint32 waitTime)
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
ConditionVariable ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
~ConditionVariable ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
A thread synchronization object used to suspend execution until some condition on shared data is met.
A thread calls Wait() to suspend its execution until the condition is met. Each call to Signal() from an executing thread will then cause a single waiting thread to be released. A call to Signal() means, "signal that the condition is true." Broadcast() releases all threads waiting on the condition variable.
The IGTL ConditionVariable implementation is consistent with the standard definition and use of condition variables in pthreads and other common thread libraries.
IMPORTANT: A condition variable always requires an associated SimpleMutexLock object. The mutex object is used to avoid a dangerous race condition when Wait() and Signal() are called simultaneously from two different threads.
On systems using pthreads, this implementation abstract the standard calls to the pthread condition variable. On Win32 systems, there is no system provided condition variable. This class implements a condition variable using a critical section, a semphore, an event and a number of counters. The implementation is almost an extract translation of the implementation presented by Douglas C Schmidt and Irfan Pyarali in "Strategies for Implementing POSIX Condition Variables on Win32". This article can be found at http://www.cs.wustl.edu/~schmidt/win32-cv-1.html
Definition at line 82 of file igtlConditionVariable.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
ConditionVariable()
igtl::ConditionVariable::ConditionVariable () protected
Definition at line 40 of file igtlConditionVariable.cxx.
Referenced by igtlNewMacro(), and igtlTypeMacro().
~ConditionVariable()
igtl::ConditionVariable::~ConditionVariable () protected
Definition at line 62 of file igtlConditionVariable.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
Broadcast()
void igtl::ConditionVariable::Broadcast ()
Signal that the condition is true and release all waiting threads
Definition at line 96 of file igtlConditionVariable.cxx.
Referenced by igtlNewMacro().
CreateAnother()
LightObject::Pointer igtl::LightObject::CreateAnother () const virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented in igtl::Object.
Definition at line 66 of file igtlLightObject.cxx.
References New().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
igtlNewMacro()
igtl::ConditionVariable::igtlNewMacro (Self)
Method for creation through the object factory.
References Broadcast(), ConditionVariable(), Signal(), and Wait().
igtlTypeMacro()
igtl::ConditionVariable::igtlTypeMacro (ConditionVariable , LightObject)
Run-time type information (and related methods).
References ConditionVariable(), and igtl::LightObject::LightObject().
New()
LightObject::Pointer igtl::LightObject::New () static inherited
Method for creation through the object factory.
Definition at line 52 of file igtlLightObject.cxx.
References igtl::ObjectFactory< T >::Create(), LightObject(), and UnRegister().
Referenced by igtl::MessageBase::Clone(), igtl::SessionManager::Connect(), CreateAnother(), igtl::VideoStreamIGTLinkServer::EncodeFile(), igtl::VideoStreamIGTLinkServer::EncodeSingleFrame(), igtl::MessageFactory::MessageFactory(), igtl::MessageRTPWrapper::MessageRTPWrapper(), igtl::VideoStreamIGTLinkReceiver::RunOnTCPSocket(), igtl::VideoStreamIGTLinkReceiver::RunOnUDPSocket(), igtl::VideoStreamIGTLinkServer::SendOriginalData(), igtl::VideoStreamIGTLinkReceiver::SendStopMessage(), igtl::SessionManager::SessionManager(), igtl::MultiThreader::SpawnThread(), igtl::ThreadFunctionServer(), igtl::ImageMetaMessage::UnpackContent(), igtl::LabelMetaMessage::UnpackContent(), igtl::PointMessage::UnpackContent(), igtl::PolyDataMessage::UnpackContent(), igtl::QuaternionTrackingDataMessage::UnpackContent(), igtl::TrackingDataMessage::UnpackContent(), igtl::TrajectoryMessage::UnpackContent(), igtl::VideoMetaMessage::UnpackContent(), igtl::VideoStreamIGTLinkReceiver::VideoStreamIGTLinkReceiver(), igtl::VideoStreamIGTLinkServer::VideoStreamIGTLinkServer(), and igtl::ServerSocket::WaitForConnection().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::LightObject::PrintSelf (std::ostream & os) const protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::Object, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 214 of file igtlLightObject.cxx.
References m_ReferenceCount.
Referenced by Print().
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::LightObject::Register () const virtual inherited
Increase the reference count (mark as used by another object).
Reimplemented in igtl::Object.
Definition at line 149 of file igtlLightObject.cxx.
References m_ReferenceCount, and m_ReferenceCountLock.
SetReferenceCount()
void igtl::LightObject::SetReferenceCount (int ref) virtual inherited
Sets the reference count on this object. This is a dangerous method, use it with care.
Sets the reference count (use with care)
Reimplemented in igtl::Object.
Definition at line 182 of file igtlLightObject.cxx.
References m_ReferenceCount, and m_ReferenceCountLock.
Signal()
void igtl::ConditionVariable::Signal ()
Signal that the condition is true and release one waiting thread
Definition at line 77 of file igtlConditionVariable.cxx.
Referenced by igtlNewMacro().
UnRegister()
void igtl::LightObject::UnRegister () const virtual inherited
Decrease the reference count (release by another object).
Reimplemented in igtl::Object.
Definition at line 162 of file igtlLightObject.cxx.
References m_ReferenceCount, and m_ReferenceCountLock.
Referenced by Delete(), and New().
Wait() [1/2]
void igtl::ConditionVariable::Wait (SimpleMutexLock * mutex)
Suspend execution of this thread until the condition is signaled. The argument is a SimpleMutex object that must be locked prior to calling this method.
Definition at line 138 of file igtlConditionVariable.cxx.
References igtl::SimpleMutexLock::GetMutexLock().
Referenced by igtlNewMacro().
Wait() [2/2]
bool igtl::ConditionVariable::Wait (SimpleMutexLock * mutex, igtl_uint32 waitTime)
Suspend execution of this thread until the condition is signaled or specified time in millisecond elapsed. return true if the signal recevied, false if the timeout expired or other error conditions happened. See the following links for more infomation about other scenarios: https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-signalobjectandwait https://www.ibm.com/support/knowledgecenter/en/ssw_i5_54/apis/users_77.htm The argument is a SimpleMutex object that must be locked prior to calling this method.
Definition at line 185 of file igtlConditionVariable.cxx.
References igtl::SimpleMutexLock::GetMutexLock().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlConditionVariable.h
igtlConditionVariable.cxx
Generated at Tue Sep 9 2025 15:29:15 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012