igtl::MultiThreader Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::MultiThreader Class Reference
#include <igtlMultiThreader.h>
Data Structures
class ThreadInfo
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetNumberOfThreads ()
virtual int GetReferenceCount () const
igtlNewMacro (Self)
igtlSetClampMacro (NumberOfThreads, int, 1, IGTL_MAX_THREADS)
igtlTypeMacro (MultiThreader, Object)
igtlTypeMacro (Object, LightObject)
void MultipleMethodExecute ()
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
void SetMultipleMethod (int index, ThreadFunctionType, void *data)
void SetReferenceCount (int) override
void SetSingleMethod (ThreadFunctionType, void *data)
void SingleMethodExecute ()
int SpawnThread (ThreadFunctionType, void *data)
void TerminateThread (int thread_id)
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static MultiThreaderIDType GetCurrentThreadID ()
static int GetGlobalDefaultNumberOfThreads ()
static int GetGlobalMaximumNumberOfThreads ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalDefaultNumberOfThreads (int val)
static void SetGlobalMaximumNumberOfThreads (int val)
static void SetGlobalWarningDisplay (bool flag)
static int ThreadsEqual (MultiThreaderIDType t1, MultiThreaderIDType t2)
Protected Member Functions
MultiThreader ()
virtual void PrintHeader (std::ostream &os) const
void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
~MultiThreader ()
Protected Attributes
void * m_MultipleData [IGTL_MAX_THREADS]
ThreadFunctionType m_MultipleMethod [IGTL_MAX_THREADS]
int m_NumberOfThreads
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
void * m_SingleData
ThreadFunctionType m_SingleMethod
int m_SpawnedThreadActiveFlag [IGTL_MAX_THREADS]
MutexLock::Pointer m_SpawnedThreadActiveFlagLock [IGTL_MAX_THREADS]
ThreadInfo m_SpawnedThreadInfoArray [IGTL_MAX_THREADS]
ThreadProcessIDType m_SpawnedThreadProcessID [IGTL_MAX_THREADS]
ThreadInfo m_ThreadInfoArray [IGTL_MAX_THREADS]
Detailed Description
Definition at line 132 of file igtlMultiThreader.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
MultiThreader()
igtl::MultiThreader::MultiThreader () protected
Definition at line 172 of file igtlMultiThreader.cxx.
References GetGlobalDefaultNumberOfThreads(), IGTL_MAX_THREADS, m_MultipleMethod, m_NumberOfThreads, m_SingleMethod, m_SpawnedThreadActiveFlag, m_SpawnedThreadActiveFlagLock, m_SpawnedThreadInfoArray, and m_ThreadInfoArray.
Referenced by igtlSetClampMacro(), and igtlTypeMacro().
~MultiThreader()
igtl::MultiThreader::~MultiThreader () protected
Definition at line 194 of file igtlMultiThreader.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetCurrentThreadID()
MultiThreaderIDType igtl::MultiThreader::GetCurrentThreadID () static
Definition at line 758 of file igtlMultiThreader.cxx.
Referenced by igtlSetClampMacro().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalDefaultNumberOfThreads()
int igtl::MultiThreader::GetGlobalDefaultNumberOfThreads () static
Definition at line 101 of file igtlMultiThreader.cxx.
References IGTL_MAX_THREADS, and igtl::MultiThreaderGlobalDefaultNumberOfThreads.
Referenced by igtlSetClampMacro(), and MultiThreader().
GetGlobalMaximumNumberOfThreads()
int igtl::MultiThreader::GetGlobalMaximumNumberOfThreads () static
Definition at line 84 of file igtlMultiThreader.cxx.
References igtl::MultiThreaderGlobalMaximumNumberOfThreads.
Referenced by igtlSetClampMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetNumberOfThreads()
int igtl::MultiThreader::GetNumberOfThreads () virtual
Definition at line 199 of file igtlMultiThreader.cxx.
References m_NumberOfThreads, and igtl::MultiThreaderGlobalMaximumNumberOfThreads.
Referenced by igtlSetClampMacro().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::MultiThreader::igtlNewMacro (Self)
igtlSetClampMacro()
igtl::MultiThreader::igtlSetClampMacro (NumberOfThreads , int , 1 , IGTL_MAX_THREADS)
References GetCurrentThreadID(), GetGlobalDefaultNumberOfThreads(), GetGlobalMaximumNumberOfThreads(), GetNumberOfThreads(), IGTL_MAX_THREADS, MultipleMethodExecute(), MultiThreader(), PrintSelf(), SetGlobalDefaultNumberOfThreads(), SetGlobalMaximumNumberOfThreads(), SetMultipleMethod(), SetSingleMethod(), SingleMethodExecute(), SpawnThread(), TerminateThread(), and ThreadsEqual().
igtlTypeMacro() [1/2]
igtl::MultiThreader::igtlTypeMacro (MultiThreader , Object)
References MultiThreader(), and igtl::Object::Object().
igtlTypeMacro() [2/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
MultipleMethodExecute()
void igtl::MultiThreader::MultipleMethodExecute ()
Definition at line 425 of file igtlMultiThreader.cxx.
References IGTL_MAX_THREADS, igtlErrorMacro, m_MultipleData, m_MultipleMethod, m_NumberOfThreads, m_ThreadInfoArray, and igtl::MultiThreaderGlobalMaximumNumberOfThreads.
Referenced by igtlSetClampMacro().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::MultiThreader::PrintSelf (std::ostream & os) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::Object.
Definition at line 791 of file igtlMultiThreader.cxx.
References m_NumberOfThreads, and igtl::MultiThreaderGlobalMaximumNumberOfThreads.
Referenced by igtlSetClampMacro().
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalDefaultNumberOfThreads()
void igtl::MultiThreader::SetGlobalDefaultNumberOfThreads (int val) static
Definition at line 92 of file igtlMultiThreader.cxx.
References igtl::MultiThreaderGlobalDefaultNumberOfThreads.
Referenced by igtlSetClampMacro().
SetGlobalMaximumNumberOfThreads()
void igtl::MultiThreader::SetGlobalMaximumNumberOfThreads (int val) static
Definition at line 75 of file igtlMultiThreader.cxx.
References igtl::MultiThreaderGlobalMaximumNumberOfThreads.
Referenced by igtlSetClampMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetMultipleMethod()
void igtl::MultiThreader::SetMultipleMethod (int index, ThreadFunctionType f, void * data)
Definition at line 223 of file igtlMultiThreader.cxx.
References igtlErrorMacro, m_MultipleData, m_MultipleMethod, and m_NumberOfThreads.
Referenced by igtlSetClampMacro().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetSingleMethod()
void igtl::MultiThreader::SetSingleMethod (ThreadFunctionType f, void * data)
Definition at line 212 of file igtlMultiThreader.cxx.
References m_SingleData, and m_SingleMethod.
Referenced by igtlSetClampMacro().
SingleMethodExecute()
void igtl::MultiThreader::SingleMethodExecute ()
Definition at line 240 of file igtlMultiThreader.cxx.
References IGTL_MAX_THREADS, igtlErrorMacro, m_NumberOfThreads, m_SingleData, m_SingleMethod, m_ThreadInfoArray, and igtl::MultiThreaderGlobalMaximumNumberOfThreads.
Referenced by igtlSetClampMacro().
SpawnThread()
int igtl::MultiThreader::SpawnThread (ThreadFunctionType f, void * data)
Definition at line 610 of file igtlMultiThreader.cxx.
References IGTL_MAX_THREADS, igtlErrorMacro, m_SpawnedThreadActiveFlag, m_SpawnedThreadActiveFlagLock, m_SpawnedThreadInfoArray, m_SpawnedThreadProcessID, and igtl::LightObject::New().
Referenced by igtlSetClampMacro().
TerminateThread()
void igtl::MultiThreader::TerminateThread (int thread_id)
Definition at line 714 of file igtlMultiThreader.cxx.
References igtlErrorMacro, m_SpawnedThreadActiveFlag, m_SpawnedThreadActiveFlagLock, and m_SpawnedThreadProcessID.
Referenced by igtlSetClampMacro().
ThreadsEqual()
int igtl::MultiThreader::ThreadsEqual (MultiThreaderIDType t1, MultiThreaderIDType t2) static
Definition at line 774 of file igtlMultiThreader.cxx.
Referenced by igtlSetClampMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_MultipleData
void* igtl::MultiThreader::m_MultipleData[IGTL_MAX_THREADS] protected
Definition at line 261 of file igtlMultiThreader.h.
Referenced by MultipleMethodExecute(), and SetMultipleMethod().
m_MultipleMethod
ThreadFunctionType igtl::MultiThreader::m_MultipleMethod[IGTL_MAX_THREADS] protected
Definition at line 248 of file igtlMultiThreader.h.
Referenced by MultipleMethodExecute(), MultiThreader(), and SetMultipleMethod().
m_NumberOfThreads
int igtl::MultiThreader::m_NumberOfThreads protected
Definition at line 239 of file igtlMultiThreader.h.
Referenced by GetNumberOfThreads(), MultipleMethodExecute(), MultiThreader(), PrintSelf(), SetMultipleMethod(), and SingleMethodExecute().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_SingleData
void* igtl::MultiThreader::m_SingleData protected
Definition at line 260 of file igtlMultiThreader.h.
Referenced by SetSingleMethod(), and SingleMethodExecute().
m_SingleMethod
ThreadFunctionType igtl::MultiThreader::m_SingleMethod protected
Definition at line 247 of file igtlMultiThreader.h.
Referenced by MultiThreader(), SetSingleMethod(), and SingleMethodExecute().
m_SpawnedThreadActiveFlag
int igtl::MultiThreader::m_SpawnedThreadActiveFlag[IGTL_MAX_THREADS] protected
Definition at line 252 of file igtlMultiThreader.h.
Referenced by MultiThreader(), SpawnThread(), and TerminateThread().
m_SpawnedThreadActiveFlagLock
MutexLock::Pointer igtl::MultiThreader::m_SpawnedThreadActiveFlagLock[IGTL_MAX_THREADS] protected
Definition at line 253 of file igtlMultiThreader.h.
Referenced by MultiThreader(), SpawnThread(), and TerminateThread().
m_SpawnedThreadInfoArray
ThreadInfo igtl::MultiThreader::m_SpawnedThreadInfoArray[IGTL_MAX_THREADS] protected
Definition at line 255 of file igtlMultiThreader.h.
Referenced by MultiThreader(), and SpawnThread().
m_SpawnedThreadProcessID
ThreadProcessIDType igtl::MultiThreader::m_SpawnedThreadProcessID[IGTL_MAX_THREADS] protected
Definition at line 254 of file igtlMultiThreader.h.
Referenced by SpawnThread(), and TerminateThread().
m_ThreadInfoArray
ThreadInfo igtl::MultiThreader::m_ThreadInfoArray[IGTL_MAX_THREADS] protected
Definition at line 244 of file igtlMultiThreader.h.
Referenced by MultipleMethodExecute(), MultiThreader(), and SingleMethodExecute().
The documentation for this class was generated from the following files:
igtlMultiThreader.h
igtlMultiThreader.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012