igtl::TrackingDataElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::TrackingDataElement Class Reference
#include <igtlTrackingDataMessage.h>
Public Types
enum {
TYPE_TRACKER = 1 ,
TYPE_6D = 2 ,
TYPE_3D = 3 ,
TYPE_5D = 4
}
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
void GetMatrix (Matrix4x4 &mat)
Gets the 4-by-4 transformation matrix.
const char * GetName ()
Gets the name of the instrument/tracker.
virtual const char * GetNameOfClass () const
void GetPosition (float *px, float *py, float *pz)
Gets the position. The function substitutes the xyz coordinates in 'px', 'py', and 'pz'.
void GetPosition (float p[3])
Gets the position. The function substitutes 3-element array of x, y and z coordinates in 'p'.
virtual int GetReferenceCount () const
igtlUint8 GetType ()
Gets the type of the instrument/tracker.
igtlNewMacro (igtl::TrackingDataElement)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::TrackingDataElement, igtl::Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
void SetMatrix (Matrix4x4 &mat)
Sets the 4-by-4 transformation matrix.
int SetName (const char *name)
Sets the name of the instrument/tracker.
void SetPosition (float p[3])
Sets the position by 3-element array of x, y, and z coordinates.
void SetPosition (float px, float py, float pz)
Sets the position by x, y, and z coordinates.
void SetReferenceCount (int) override
int SetType (igtlUint8 type)
Sets the type of the instrument/tracker.
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
TrackingDataElement ()
~TrackingDataElement ()
Protected Attributes
Matrix4x4 m_Matrix
Transform matrix.
std::string m_Name
Name / description (< 20 bytes.
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_Type
Tracking data type (TYPE_TRACKER, TYPE_6D, TYPE_3D, TYPE_5D)
Detailed Description
Definition at line 30 of file igtlTrackingDataMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Tracking data type. TYPE_TRACKER: Tracker TYPE_6D: 6D instrument: (regular instrument) TYPE_3D: 3D instrument (only tip of the instrument defined) TYPE_5D: 5D instrument (tip and handle are defined, but not the normal vector)
Enumerator
TYPE_TRACKER
TYPE_6D
TYPE_3D
TYPE_5D
Definition at line 41 of file igtlTrackingDataMessage.h.
Constructor & Destructor Documentation
TrackingDataElement()
igtl::TrackingDataElement::TrackingDataElement () protected
Definition at line 29 of file igtlTrackingDataMessage.cxx.
References igtl::IdentityMatrix(), m_Matrix, m_Name, m_Type, igtl::Object::Object(), and TYPE_TRACKER.
~TrackingDataElement()
igtl::TrackingDataElement::~TrackingDataElement () protected
Definition at line 37 of file igtlTrackingDataMessage.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetMatrix()
void igtl::TrackingDataElement::GetMatrix (Matrix4x4 & mat)
Gets the 4-by-4 transformation matrix.
Definition at line 129 of file igtlTrackingDataMessage.cxx.
References m_Matrix.
GetName()
const char * igtl::TrackingDataElement::GetName () inline
Gets the name of the instrument/tracker.
Definition at line 54 of file igtlTrackingDataMessage.h.
References m_Name.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetPosition() [1/2]
void igtl::TrackingDataElement::GetPosition (float * px, float * py, float * pz)
Gets the position. The function substitutes the xyz coordinates in 'px', 'py', and 'pz'.
Definition at line 97 of file igtlTrackingDataMessage.cxx.
References m_Matrix.
GetPosition() [2/2]
void igtl::TrackingDataElement::GetPosition (float p[3])
Gets the position. The function substitutes 3-element array of x, y and z coordinates in 'p'.
Definition at line 81 of file igtlTrackingDataMessage.cxx.
References m_Matrix.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetType()
igtlUint8 igtl::TrackingDataElement::GetType () inline
Gets the type of the instrument/tracker.
Definition at line 60 of file igtlTrackingDataMessage.h.
References m_Type.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::TrackingDataElement::igtlNewMacro (igtl::TrackingDataElement)
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::TrackingDataElement::igtlTypeMacro (igtl::TrackingDataElement , igtl::Object)
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetMatrix()
void igtl::TrackingDataElement::SetMatrix (Matrix4x4 & mat)
Sets the 4-by-4 transformation matrix.
Definition at line 105 of file igtlTrackingDataMessage.cxx.
References m_Matrix.
SetName()
int igtl::TrackingDataElement::SetName (const char * name)
Sets the name of the instrument/tracker.
Definition at line 42 of file igtlTrackingDataMessage.cxx.
References IGTL_TDATA_LEN_NAME, and m_Name.
SetPosition() [1/2]
void igtl::TrackingDataElement::SetPosition (float p[3])
Sets the position by 3-element array of x, y, and z coordinates.
Definition at line 73 of file igtlTrackingDataMessage.cxx.
References m_Matrix.
SetPosition() [2/2]
void igtl::TrackingDataElement::SetPosition (float px, float py, float pz)
Sets the position by x, y, and z coordinates.
Definition at line 89 of file igtlTrackingDataMessage.cxx.
References m_Matrix.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetType()
int igtl::TrackingDataElement::SetType (igtlUint8 type)
Sets the type of the instrument/tracker.
Definition at line 56 of file igtlTrackingDataMessage.cxx.
References m_Type, TYPE_3D, TYPE_5D, TYPE_6D, and TYPE_TRACKER.
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_Matrix
Matrix4x4 igtl::TrackingDataElement::m_Matrix protected
Transform matrix.
Definition at line 93 of file igtlTrackingDataMessage.h.
Referenced by GetMatrix(), GetPosition(), GetPosition(), SetMatrix(), SetPosition(), SetPosition(), and TrackingDataElement().
m_Name
std::string igtl::TrackingDataElement::m_Name protected
Name / description (< 20 bytes.
Definition at line 87 of file igtlTrackingDataMessage.h.
Referenced by GetName(), SetName(), and TrackingDataElement().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_Type
igtlUint8 igtl::TrackingDataElement::m_Type protected
Tracking data type (TYPE_TRACKER, TYPE_6D, TYPE_3D, TYPE_5D)
Definition at line 90 of file igtlTrackingDataMessage.h.
Referenced by GetType(), SetType(), and TrackingDataElement().
The documentation for this class was generated from the following files:
igtlTrackingDataMessage.h
igtlTrackingDataMessage.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012