igtl::UDPClientSocket Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::UDPClientSocket Class Reference
#include <igtlUDPClientSocket.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
void CloseSocket ()
Close the socket.
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
int GetConnected ()
Check is the socket is alive.
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
int GetSocketAddressAndPort (std::string &address, int &port)
Get socket address.
igtlTypeMacro (Object, LightObject)
igtlTypeMacro(igtl::UDPClientSocket, igtl::GeneralSocket) igtlNewMacro(igtl int JoinNetwork (const char *groupIPAddr, int portNum)
void Print (std::ostream &os) const
int ReadSocket (unsigned char *buffer, unsigned bufferSize)
int Receive (void *data, int length, int readFully=1)
int ReceiveUDP (void *data, int length)
void Register () const override
int Send (const void *data, int length)
int SendUDP (const void *data, int length)
void SetDebug (bool debugFlag) const
int SetIPAddress (const char *ip)
int SetPortNumber (igtl_uint16 port)
int SetReceiveBlocking (int sw)
int SetReceiveTimeout (int timeout)
void SetReferenceCount (int) override
int SetSendBlocking (int sw)
int SetSendTimeout (int timeout)
int SetTimeout (int timeout)
int Skip (int length, int skipFully=1)
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
int Accept (int socketdescriptor)
int BindSocket (int socketdescriptor, int port)
void CloseSocket (int socketdescriptor)
Close the socket.
int Connect (int socketdescriptor, const char *hostname, int port)
Connect to a server socket. Returns 0 on success, -1 on error.
int CreateSocket ()
int CreateUDPClientSocket ()
int CreateUDPServerSocket ()
int GetPort (int socketdescriptor)
igtlGetMacro (SocketDescriptor, int)
int Listen (int socketdescriptor)
Listen for connections on a socket. Returns 0 on success. -1 on error.
virtual void PrintHeader (std::ostream &os) const
void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
int SelectSocket (int socketdescriptor, unsigned long msec)
UDPClientSocket ()
~UDPClientSocket ()
Static Protected Member Functions
static int SelectSockets (const int *sockets_to_select, int size, unsigned long msec, int *selected_index)
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
int m_SocketDescriptor
Friends
class UDPServerSocket
Detailed Description
Definition at line 42 of file igtlUDPClientSocket.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
UDPClientSocket()
igtl::UDPClientSocket::UDPClientSocket () protected
Definition at line 35 of file igtlUDPClientSocket.cxx.
Referenced by UDPServerSocket.
~UDPClientSocket()
igtl::UDPClientSocket::~UDPClientSocket () protected
Definition at line 40 of file igtlUDPClientSocket.cxx.
Member Function Documentation
Accept()
int igtl::GeneralSocket::Accept (int socketdescriptor) protected inherited
Accept a connection on a socket. Returns -1 on error. Otherwise the descriptor of the accepted socket.
Definition at line 215 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
BindSocket()
int igtl::GeneralSocket::BindSocket (int socketdescriptor, int port) protected inherited
Binds socket to a particular port. Returns 0 on success other -1 is returned.
Definition at line 191 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CloseSocket() [1/2]
void igtl::GeneralSocket::CloseSocket () inline inherited
Close the socket.
Definition at line 78 of file igtlGeneralSocket.h.
References CloseSocket(), and m_SocketDescriptor.
Referenced by CloseSocket(), CreateUDPClientSocket(), igtl::UDPServerSocket::CreateUDPServer(), CreateUDPServerSocket(), vtkSocketCollection, and ~GeneralSocket().
CloseSocket() [2/2]
void igtl::GeneralSocket::CloseSocket (int socketdescriptor) protected inherited
Close the socket.
Definition at line 372 of file igtlGeneralSocket.cxx.
References igtlCloseSocketMacro.
Connect()
int igtl::GeneralSocket::Connect (int socketdescriptor, const char * hostname, int port) protected inherited
Connect to a server socket. Returns 0 on success, -1 on error.
Definition at line 321 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
CreateSocket()
int igtl::GeneralSocket::CreateSocket () protected inherited
Creates an endpoint for communication and returns the descriptor. -1 indicates error.
Definition at line 83 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
CreateUDPClientSocket()
int igtl::GeneralSocket::CreateUDPClientSocket () protected inherited
Creates an endpoint for communication and returns the descriptor. -1 indicates error.
Definition at line 136 of file igtlGeneralSocket.cxx.
References CloseSocket().
Referenced by igtl::UDPClientSocket::JoinNetwork(), and vtkSocketCollection.
CreateUDPServerSocket()
int igtl::GeneralSocket::CreateUDPServerSocket () protected inherited
Creates an endpoint for communication and returns the descriptor. -1 indicates error.
Definition at line 111 of file igtlGeneralSocket.cxx.
References CloseSocket().
Referenced by igtl::UDPServerSocket::CreateUDPServer(), and vtkSocketCollection.
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetConnected()
int igtl::GeneralSocket::GetConnected () inline inherited
Check is the socket is alive.
Definition at line 75 of file igtlGeneralSocket.h.
References m_SocketDescriptor.
Referenced by Receive(), ReceiveUDP(), Send(), SendUDP(), SetReceiveBlocking(), SetReceiveTimeout(), SetSendBlocking(), and SetSendTimeout().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetPort()
int igtl::GeneralSocket::GetPort (int socketdescriptor) protected inherited
Returns the port to which the socket is connected. 0 on error.
Definition at line 354 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetSocketAddressAndPort()
int igtl::GeneralSocket::GetSocketAddressAndPort (std::string & address, int & port) inherited
Get socket address.
Definition at line 812 of file igtlGeneralSocket.cxx.
References m_SocketDescriptor.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlGetMacro()
igtl::GeneralSocket::igtlGetMacro (SocketDescriptor , int) protected inherited
igtlTypeMacro()
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
JoinNetwork()
int igtl::UDPClientSocket::JoinNetwork (const char * groupIPAddr, int portNum)
Definition at line 44 of file igtlUDPClientSocket.cxx.
References igtl::GeneralSocket::CreateUDPClientSocket(), igtl::GeneralSocket::m_SocketDescriptor, igtl::GeneralSocket::SetIPAddress(), and igtl::GeneralSocket::SetPortNumber().
Listen()
int igtl::GeneralSocket::Listen (int socketdescriptor) protected inherited
Listen for connections on a socket. Returns 0 on success. -1 on error.
Definition at line 225 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::UDPClientSocket::PrintSelf (std::ostream & os) const override protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::GeneralSocket.
Definition at line 63 of file igtlUDPClientSocket.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
ReadSocket()
int igtl::UDPClientSocket::ReadSocket (unsigned char * buffer, unsigned bufferSize)
Definition at line 53 of file igtlUDPClientSocket.cxx.
References igtlErrorMacro, igtl::GeneralSocket::m_SocketDescriptor, and igtl::GeneralSocket::ReceiveUDP().
Receive()
int igtl::GeneralSocket::Receive (void * data, int length, int readFully = 1) inherited
Receive data from the socket. This call blocks until some data is read from the socket, unless timeout is set by SetTimeout() or SetReceiveTimeout(). When the readFully flag is set, this call will block until all the requested data is read from the socket. The readFully flag will be ignored if the timeout is active. 0 on error, -1 on timeout, else number of bytes read is returned.
Definition at line 433 of file igtlGeneralSocket.cxx.
References GetConnected(), m_SocketDescriptor, and igtl::Sleep().
Referenced by Skip().
ReceiveUDP()
int igtl::GeneralSocket::ReceiveUDP (void * data, int length) inherited
Receive UDP Diagram data from the socket. This function is able to receive the data at a group Ip (broadcast IP) by setting the IP Address 'SetIPAddress()' This call blocks until some data is read from the socket, unless timeout is set by SetTimeout() or SetReceiveTimeout().
Definition at line 566 of file igtlGeneralSocket.cxx.
References GetConnected(), m_SocketDescriptor, and igtl::Sleep().
Referenced by igtl::UDPClientSocket::ReadSocket().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SelectSocket()
int igtl::GeneralSocket::SelectSocket (int socketdescriptor, unsigned long msec) protected inherited
Selects a socket ie. waits for it to change status. Returns 1 on success; 0 on timeout; -1 on error. msec=0 implies no timeout.
Definition at line 235 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
SelectSockets()
int igtl::GeneralSocket::SelectSockets (const int * sockets_to_select, int size, unsigned long msec, int * selected_index) static protected inherited
Selects set of sockets. Returns 0 on timeout, -1 on error. 1 on success. Selected socket's index is returned thru selected_index
Definition at line 270 of file igtlGeneralSocket.cxx.
Referenced by vtkSocketCollection.
Send()
int igtl::GeneralSocket::Send (const void * data, int length) inherited
These methods send data over the socket. Returns 1 on success, 0 on error and raises vtkCommand::ErrorEvent. SIGPIPE or other signal may be raised on systems (e.g., Sun Solaris) where MSG_NOSIGNAL flag is not supported for the socket send method.
Definition at line 382 of file igtlGeneralSocket.cxx.
References GetConnected(), and m_SocketDescriptor.
SendUDP()
int igtl::GeneralSocket::SendUDP (const void * data, int length) inherited
These methods send UDP Diagram data over the socket. Returns 1 on success, 0 on error SIGPIPE or other signal may be raised on systems (e.g., Sun Solaris) where MSG_NOSIGNAL flag is not supported for the socket send method.
Definition at line 507 of file igtlGeneralSocket.cxx.
References GetConnected(), m_SocketDescriptor, and TTL_TYPE.
Referenced by igtl::UDPServerSocket::WriteSocket().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetIPAddress()
int igtl::GeneralSocket::SetIPAddress (const char * ip) inherited
Definition at line 487 of file igtlGeneralSocket.cxx.
Referenced by igtl::UDPClientSocket::JoinNetwork(), and igtl::UDPServerSocket::WriteSocket().
SetPortNumber()
int igtl::GeneralSocket::SetPortNumber (igtl_uint16 port) inherited
Definition at line 496 of file igtlGeneralSocket.cxx.
Referenced by igtl::UDPClientSocket::JoinNetwork(), and igtl::UDPServerSocket::WriteSocket().
SetReceiveBlocking()
int igtl::GeneralSocket::SetReceiveBlocking (int sw) inherited
Set (psuedo) non-blocking mode for recv(). When sw=1, the time out is set to minimum value (1 microsecond in UNIX, 1 millisecond in Windows) for receiving.
Definition at line 710 of file igtlGeneralSocket.cxx.
References GetConnected(), and m_SocketDescriptor.
SetReceiveTimeout()
int igtl::GeneralSocket::SetReceiveTimeout (int timeout) inherited
Set reciving timeout for the existing socket in millisecond. This function should be called after opening the socket.
Definition at line 640 of file igtlGeneralSocket.cxx.
References GetConnected(), and m_SocketDescriptor.
Referenced by SetTimeout().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetSendBlocking()
int igtl::GeneralSocket::SetSendBlocking (int sw) inherited
Set (psuedo) non-blocking mode for recv(). When sw=1, the time out is set to minimum value (1 microsecond in UNIX, 1 millisecond in Windows) for sending.
Definition at line 761 of file igtlGeneralSocket.cxx.
References GetConnected(), and m_SocketDescriptor.
SetSendTimeout()
int igtl::GeneralSocket::SetSendTimeout (int timeout) inherited
Set sending timeout for the existing socket in millisecond. This function should be called after opening the socket.
Definition at line 675 of file igtlGeneralSocket.cxx.
References GetConnected(), and m_SocketDescriptor.
Referenced by SetTimeout().
SetTimeout()
int igtl::GeneralSocket::SetTimeout (int timeout) inherited
Set sending/receiving timeout for the existing socket in millisecond. This function should be called after opening the socket.
Definition at line 626 of file igtlGeneralSocket.cxx.
References SetReceiveTimeout(), and SetSendTimeout().
Skip()
int igtl::GeneralSocket::Skip (int length, int skipFully = 1) inherited
Skip reading data from the socket. The Skip() call has been newly introduced to the igtlSocket, after the class is imported from VTK, thus the call is not available in vtkSocket class.
Definition at line 841 of file igtlGeneralSocket.cxx.
References Receive().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Friends And Related Symbol Documentation
UDPServerSocket
friend class UDPServerSocket friend
Definition at line 58 of file igtlUDPClientSocket.h.
References UDPClientSocket(), and UDPServerSocket.
Referenced by UDPServerSocket.
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_SocketDescriptor
int igtl::GeneralSocket::m_SocketDescriptor protected inherited
Definition at line 148 of file igtlGeneralSocket.h.
Referenced by CloseSocket(), igtl::UDPServerSocket::CreateUDPServer(), GeneralSocket(), GetConnected(), GetSocketAddressAndPort(), igtl::UDPClientSocket::JoinNetwork(), igtl::UDPClientSocket::ReadSocket(), Receive(), ReceiveUDP(), Send(), SendUDP(), SetReceiveBlocking(), SetReceiveTimeout(), SetSendBlocking(), SetSendTimeout(), and ~GeneralSocket().
The documentation for this class was generated from the following files:
igtlUDPClientSocket.h
igtlUDPClientSocket.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012