igtl::H265Decoder Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::H265Decoder Class Reference abstract
#include <igtlH265Decoder.h>
Data Structures
struct Info
Public Types
enum {
MULTITHREAD_FRAME = 1 ,
MULTITHREAD_SLICE = 2 ,
MULTITHREAD_FRAME_SLICE = 4
}
typedef SmartPointer< const Self > ConstPointer
typedef struct igtl::H265Decoder::Info Info
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual int DecodeBitStreamIntoFrame (unsigned char *bitStream, igtl_uint8 *outputFrame, igtl_uint32 iDimensions[], igtl_uint64 &iStreamSize)=0
int DecodeBitStreamIntoFrame (unsigned char *bitStream, igtl_uint8 *outputFrame, igtl_uint32 iDimensions[2], igtl_uint64 &iStreamSize) override
int DecodeVideoMSGIntoSingleFrame (igtl::VideoMessage *videoMessage, SourcePicture *pDecodedPic) override
virtual void Delete ()
virtual igtl_int64 getCurrentTime ()
bool GetDebug () const
virtual std::string GetDeviceName ()
virtual bool GetIsGrayImage ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
H265Decoder ()
igtlNewMacro (H265Decoder)
igtlTypeMacro (igtl::GenericDecoder, igtl::Object)
igtlTypeMacro (H265Decoder, GenericDecoder)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
virtual void SetDeviceName (std::string name)
virtual void SetIsGrayImage (bool grayImage)
void SetReferenceCount (int) override
int UnpackUncompressedData (igtl::VideoMessage *videoMessage, SourcePicture *decodedPic)
void UnRegister () const override
~H265Decoder ()
Static Public Member Functions
static void BreakOnError ()
static int ConvertYUVToGrayImage (igtl_uint8 *YUV420Frame, igtl_uint8 *GrayFrame, int iHeight, int iWidth)
static int ConvertYUVToRGB (igtl_uint8 *YUVFrame, igtl_uint8 *RGBFrame, int iHeight, int iWidth)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
static void Write2File (FILE *pFp, unsigned char *pData[], igtl_uint32 iDimensions[], igtl_uint32 iStride[])
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
std::string deviceName
bool isGrayImage
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 35 of file igtlH265Decoder.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Info
typedef struct igtl::H265Decoder::Info igtl::H265Decoder::Info
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MULTITHREAD_FRAME
Put frames into multiple threads.
MULTITHREAD_SLICE
Put slices of a frame into multiple threads.
MULTITHREAD_FRAME_SLICE
Put slices of multiple frames into multiple threads.
Definition at line 53 of file igtlH265Decoder.h.
Constructor & Destructor Documentation
H265Decoder()
igtl::H265Decoder::H265Decoder ()
Definition at line 19 of file igtlH265Decoder.cxx.
References MULTITHREAD_SLICE.
Referenced by igtlNewMacro(), and igtlTypeMacro().
~H265Decoder()
igtl::H265Decoder::~H265Decoder ()
Definition at line 31 of file igtlH265Decoder.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
ConvertYUVToGrayImage()
int igtl::GenericDecoder::ConvertYUVToGrayImage (igtl_uint8 * YUV420Frame, igtl_uint8 * GrayFrame, int iHeight, int iWidth) static inherited
Definition at line 246 of file igtlCodecCommonClasses.cxx.
ConvertYUVToRGB()
int igtl::GenericDecoder::ConvertYUVToRGB (igtl_uint8 * YUVFrame, igtl_uint8 * RGBFrame, int iHeight, int iWidth) static inherited
The conversion equations between RGB and YUV is Keith Jack's book "Video Demystified" (ISBN 1-878707-09-4). The equations are: RGB to YUV Conversion Y = (0.257 * R) + (0.504 * G) + (0.098 * B) + 16
U = -(0.148 * R) - (0.291 * G) + (0.439 * B) + 128
V = (0.439 * R) - (0.368 * G) - (0.071 * B) + 128
YUV to RGB Conversion R = 1.164(Y - 16) + 1.596(V - 128)
G = 1.164(Y - 16) - 0.391(U - 128) - 0.813(V - 128)
B = 1.164(Y - 16) + 2.018(U - 128)
To speed up the computation, float point multiplication is achieved via bitwise operator RGB to YUV Conversion Y = (16843 * R + 33030 * G + 6423 * B) >> 16 + 16
U = -(9699 * R - 19071 * G + 28770 * B) >> 16 + 128
V = (28770 * R - 24117 * G - 4653 * B) >> 16 + 128
Or
Y = (66 * R + 129 * G + 25 * B) >> 8 + 16
U = (-38 * R - 74 * G + 112 * B) >> 8 + 128
V = (112 * R - 94 * G - 18 * B) >> 8 + 128
YUV to RGB Conversion R = (76284 * (Y - 16) + 104595 * (V - 128)) >> 16
G = (76284 * (Y - 16) - 25625 * (U - 128) - 53280 * (V - 128)) >> 16
B = (76284 * (Y - 16) + 132252 * (U - 128)) >> 16
Or
R = (298 * (Y - 16) + 409 * (V - 128)) >> 8
G = (298 * (Y - 16) - 100 * (U - 128) - 208 * (V - 128)) >> 8
B = (298 * (Y - 16) + 517 * (U - 128)) >> 8
To do, use the latest conversion Scheme from ITU. https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2020-2-201510-I!!PDF-E.pdf
Definition at line 173 of file igtlCodecCommonClasses.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DecodeBitStreamIntoFrame() [1/2]
virtual int igtl::GenericDecoder::DecodeBitStreamIntoFrame (unsigned char * bitStream, igtl_uint8 * outputFrame, igtl_uint32 iDimensions[], igtl_uint64 & iStreamSize) pure virtual inherited
References Write2File().
DecodeBitStreamIntoFrame() [2/2]
int igtl::H265Decoder::DecodeBitStreamIntoFrame (unsigned char * bitStream, igtl_uint8 * outputFrame, igtl_uint32 iDimensions[2], igtl_uint64 & iStreamSize) override
Definition at line 102 of file igtlH265Decoder.cxx.
Referenced by DecodeVideoMSGIntoSingleFrame().
DecodeVideoMSGIntoSingleFrame()
int igtl::H265Decoder::DecodeVideoMSGIntoSingleFrame (igtl::VideoMessage * videoMessage, SourcePicture * pDecodedPic) override virtual
Reimplemented from igtl::GenericDecoder.
Definition at line 75 of file igtlH265Decoder.cxx.
References igtl::SourcePicture::data, DecodeBitStreamIntoFrame(), igtl::VideoMessage::GetBitStreamSize(), igtl::VideoMessage::GetFrameType(), igtl::VideoMessage::GetHeight(), igtl::VideoMessage::GetPackFragmentPointer(), igtl::VideoMessage::GetWidth(), igtl::GenericDecoder::isGrayImage, igtl::SourcePicture::picHeight, igtl::SourcePicture::picWidth, and igtl::SourcePicture::stride.
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
getCurrentTime()
igtl_int64 igtl::GenericDecoder::getCurrentTime () virtual inherited
Definition at line 160 of file igtlCodecCommonClasses.cxx.
Referenced by igtl::H264Decoder::DecodeBitStreamIntoFrame().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetDeviceName()
virtual std::string igtl::GenericDecoder::GetDeviceName () inline virtual inherited
Definition at line 205 of file igtlCodecCommonClasses.h.
References deviceName.
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetIsGrayImage()
virtual bool igtl::GenericDecoder::GetIsGrayImage () inline virtual inherited
Definition at line 215 of file igtlCodecCommonClasses.h.
References isGrayImage.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::H265Decoder::igtlNewMacro (H265Decoder)
References H265Decoder().
igtlTypeMacro() [1/3]
igtl::GenericDecoder::igtlTypeMacro (igtl::GenericDecoder , igtl::Object) inherited
igtlTypeMacro() [2/3]
igtl::H265Decoder::igtlTypeMacro (H265Decoder , GenericDecoder)
References igtl::GenericDecoder::GenericDecoder(), and H265Decoder().
igtlTypeMacro() [3/3]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetDeviceName()
virtual void igtl::GenericDecoder::SetDeviceName (std::string name) inline virtual inherited
Definition at line 210 of file igtlCodecCommonClasses.h.
References deviceName.
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetIsGrayImage()
virtual void igtl::GenericDecoder::SetIsGrayImage (bool grayImage) inline virtual inherited
Definition at line 220 of file igtlCodecCommonClasses.h.
References isGrayImage.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
UnpackUncompressedData()
int igtl::GenericDecoder::UnpackUncompressedData (igtl::VideoMessage * videoMessage, SourcePicture * decodedPic) inherited
Definition at line 134 of file igtlCodecCommonClasses.cxx.
References igtl::SourcePicture::data, igtl::VideoMessage::GetBitStreamSize(), igtl::VideoMessage::GetFrameType(), igtl::VideoMessage::GetHeight(), igtl::VideoMessage::GetPackFragmentPointer(), igtl::VideoMessage::GetWidth(), isGrayImage, igtl::SourcePicture::picHeight, igtl::SourcePicture::picWidth, and igtl::SourcePicture::stride.
Referenced by igtl::I420Decoder::DecodeVideoMSGIntoSingleFrame().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Write2File()
void igtl::GenericDecoder::Write2File (FILE * pFp, unsigned char * pData[], igtl_uint32 iDimensions[], igtl_uint32 iStride[]) static inherited
Definition at line 107 of file igtlCodecCommonClasses.cxx.
Referenced by DecodeBitStreamIntoFrame(), and igtl::H264Decoder::Process().
Field Documentation
deviceName
std::string igtl::GenericDecoder::deviceName protected inherited
Definition at line 285 of file igtlCodecCommonClasses.h.
Referenced by GenericDecoder(), GetDeviceName(), igtl::H264Decoder::H264Decoder(), igtl::I420Decoder::I420Decoder(), igtl::igtlAV1Decoder::igtlAV1Decoder(), SetDeviceName(), and igtl::VP9Decoder::VP9Decoder().
isGrayImage
bool igtl::GenericDecoder::isGrayImage protected inherited
Definition at line 287 of file igtlCodecCommonClasses.h.
Referenced by igtl::H264Decoder::DecodeVideoMSGIntoSingleFrame(), igtl::H265Decoder::DecodeVideoMSGIntoSingleFrame(), GenericDecoder(), GetIsGrayImage(), SetIsGrayImage(), and UnpackUncompressedData().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlH265Decoder.h
igtlH265Decoder.cxx
Generated at Tue Sep 9 2025 15:29:15 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012