igtl::SimpleMutexLock Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::SimpleMutexLock Class Reference
Simple mutual exclusion locking class.
#include <igtlMutexLock.h>
Public Types
typedef SimpleMutexLock Self
Public Member Functions
MutexType & GetMutexLock ()
const MutexType GetMutexLock () const
virtual const char * GetNameOfClass ()
void Lock (void)
SimpleMutexLock ()
void Unlock (void)
virtual ~SimpleMutexLock ()
Static Public Member Functions
static SimpleMutexLock * New ()
Protected Attributes
MutexType m_MutexLock
Detailed Description
Simple mutual exclusion locking class.
SimpleMutexLock allows the locking of variables which are accessed through different threads. This header file also defines SimpleMutexLock which is not a subclass of Object.
Definition at line 83 of file igtlMutexLock.h.
Member Typedef Documentation
Self
typedef SimpleMutexLock igtl::SimpleMutexLock::Self
Standard class typedefs.
Definition at line 87 of file igtlMutexLock.h.
Constructor & Destructor Documentation
SimpleMutexLock()
igtl::SimpleMutexLock::SimpleMutexLock ()
Constructor and destructor left public purposely.
Definition at line 46 of file igtlMutexLock.cxx.
References m_MutexLock.
Referenced by New().
~SimpleMutexLock()
igtl::SimpleMutexLock::~SimpleMutexLock () virtual
Definition at line 67 of file igtlMutexLock.cxx.
References m_MutexLock.
Member Function Documentation
GetMutexLock() [1/2]
MutexType & igtl::SimpleMutexLock::GetMutexLock () inline
Access the MutexType member variable from outside this class
Definition at line 107 of file igtlMutexLock.h.
References m_MutexLock.
Referenced by igtl::ConditionVariable::Wait(), and igtl::ConditionVariable::Wait().
GetMutexLock() [2/2]
const MutexType igtl::SimpleMutexLock::GetMutexLock () const inline
Definition at line 111 of file igtlMutexLock.h.
References m_MutexLock.
GetNameOfClass()
virtual const char * igtl::SimpleMutexLock::GetNameOfClass () inline virtual
Used for debugging and other run-time purposes.
Definition at line 98 of file igtlMutexLock.h.
Lock()
void igtl::SimpleMutexLock::Lock (void)
Lock the MutexLock.
Definition at line 79 of file igtlMutexLock.cxx.
References m_MutexLock.
Referenced by igtl::ThreadFunctionReadFrameFromFile(), igtl::ThreadFunctionSendPacket(), and igtl::ThreadFunctionServer().
New()
SimpleMutexLock * igtl::SimpleMutexLock::New () static
Methods for creation and destruction through the object factory.
Definition at line 40 of file igtlMutexLock.cxx.
References SimpleMutexLock().
Referenced by igtl::MessageRTPWrapper::MessageRTPWrapper(), igtl::VideoStreamIGTLinkReceiver::RunOnUDPSocket(), and igtl::VideoStreamIGTLinkServer::VideoStreamIGTLinkServer().
Unlock()
void igtl::SimpleMutexLock::Unlock (void)
Unlock the MutexLock.
Definition at line 95 of file igtlMutexLock.cxx.
References m_MutexLock.
Referenced by igtl::ThreadFunctionReadFrameFromFile(), igtl::ThreadFunctionSendPacket(), and igtl::ThreadFunctionServer().
Field Documentation
m_MutexLock
MutexType igtl::SimpleMutexLock::m_MutexLock protected
Definition at line 117 of file igtlMutexLock.h.
Referenced by GetMutexLock(), GetMutexLock(), Lock(), SimpleMutexLock(), Unlock(), and ~SimpleMutexLock().
The documentation for this class was generated from the following files:
igtlMutexLock.h
igtlMutexLock.cxx
Generated at Tue Sep 9 2025 15:29:17 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012