igtl::VideoStreamIGTLinkReceiver Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::VideoStreamIGTLinkReceiver Class Reference
#include <igtlVideoStreamIGTLinkReceiver.h>
Public Types
enum {
RunOnTCP = 0 ,
RunOnUDP = 1
}
Public Member Functions
std::string GetDeviceName ()
int GetHeight ()
int GetTransportMethod ()
int GetWidth ()
bool InitializeClient ()
void InitializeDecodedFrame ()
int ParseConfigForClient ()
int ProcessVideoStream (igtl_uint8 *bitStream, int streamLength)
int RunOnTCPSocket ()
int RunOnUDPSocket ()
void SendStopMessage ()
void SetDecoder (GenericDecoder *decoder)
void SetHeight (int iHeight)
void SetWidth (int iWidth)
VideoStreamIGTLinkReceiver (char *fileName)
~VideoStreamIGTLinkReceiver ()
Detailed Description
Definition at line 44 of file igtlVideoStreamIGTLinkReceiver.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
RunOnTCP
RunOnUDP
Definition at line 75 of file igtlVideoStreamIGTLinkReceiver.h.
Constructor & Destructor Documentation
VideoStreamIGTLinkReceiver()
igtl::VideoStreamIGTLinkReceiver::VideoStreamIGTLinkReceiver (char * fileName)
Definition at line 83 of file igtlVideoStreamIGTLinkReceiver.cxx.
References igtl::LightObject::New().
~VideoStreamIGTLinkReceiver()
igtl::VideoStreamIGTLinkReceiver::~VideoStreamIGTLinkReceiver ()
Definition at line 101 of file igtlVideoStreamIGTLinkReceiver.cxx.
Member Function Documentation
GetDeviceName()
std::string igtl::VideoStreamIGTLinkReceiver::GetDeviceName () inline
Definition at line 83 of file igtlVideoStreamIGTLinkReceiver.h.
Referenced by igtl::ThreadFunctionUnWrap().
GetHeight()
int igtl::VideoStreamIGTLinkReceiver::GetHeight () inline
Definition at line 67 of file igtlVideoStreamIGTLinkReceiver.h.
GetTransportMethod()
int igtl::VideoStreamIGTLinkReceiver::GetTransportMethod () inline
Definition at line 81 of file igtlVideoStreamIGTLinkReceiver.h.
GetWidth()
int igtl::VideoStreamIGTLinkReceiver::GetWidth () inline
Definition at line 65 of file igtlVideoStreamIGTLinkReceiver.h.
InitializeClient()
bool igtl::VideoStreamIGTLinkReceiver::InitializeClient ()
Definition at line 295 of file igtlVideoStreamIGTLinkReceiver.cxx.
References ParseConfigForClient().
InitializeDecodedFrame()
void igtl::VideoStreamIGTLinkReceiver::InitializeDecodedFrame ()
Definition at line 389 of file igtlVideoStreamIGTLinkReceiver.cxx.
Referenced by ProcessVideoStream().
ParseConfigForClient()
int igtl::VideoStreamIGTLinkReceiver::ParseConfigForClient ()
Definition at line 325 of file igtlVideoStreamIGTLinkReceiver.cxx.
References IP4AddressStrLen.
Referenced by InitializeClient().
ProcessVideoStream()
int igtl::VideoStreamIGTLinkReceiver::ProcessVideoStream (igtl_uint8 * bitStream, int streamLength)
Definition at line 399 of file igtlVideoStreamIGTLinkReceiver.cxx.
References igtl::SourcePicture::data, and InitializeDecodedFrame().
Referenced by RunOnTCPSocket(), and RunOnUDPSocket().
RunOnTCPSocket()
int igtl::VideoStreamIGTLinkReceiver::RunOnTCPSocket ()
Definition at line 110 of file igtlVideoStreamIGTLinkReceiver.cxx.
References IGTL_HEADER_VERSION_2, igtl::LightObject::New(), ProcessVideoStream(), SendStopMessage(), SetHeight(), SetWidth(), and igtl::Sleep().
RunOnUDPSocket()
int igtl::VideoStreamIGTLinkReceiver::RunOnUDPSocket ()
Definition at line 223 of file igtlVideoStreamIGTLinkReceiver.cxx.
References igtl::ReadSocketAndPush::clientSocket, IGTL_HEADER_SIZE, igtl::LightObject::New(), igtl::SimpleMutexLock::New(), ProcessVideoStream(), igtl::ReadSocketAndPush::receiver, igtl::Wrapper::receiver, SetHeight(), SetWidth(), igtl::ThreadFunctionReadSocket(), igtl::ThreadFunctionUnWrap(), igtl::ReadSocketAndPush::wrapper, and igtl::Wrapper::wrapper.
SendStopMessage()
void igtl::VideoStreamIGTLinkReceiver::SendStopMessage ()
Definition at line 210 of file igtlVideoStreamIGTLinkReceiver.cxx.
References IGTL_HEADER_VERSION_2, and igtl::LightObject::New().
Referenced by RunOnTCPSocket().
SetDecoder()
void igtl::VideoStreamIGTLinkReceiver::SetDecoder (GenericDecoder * decoder)
Definition at line 104 of file igtlVideoStreamIGTLinkReceiver.cxx.
SetHeight()
void igtl::VideoStreamIGTLinkReceiver::SetHeight (int iHeight)
Definition at line 384 of file igtlVideoStreamIGTLinkReceiver.cxx.
Referenced by RunOnTCPSocket(), and RunOnUDPSocket().
SetWidth()
void igtl::VideoStreamIGTLinkReceiver::SetWidth (int iWidth)
Definition at line 379 of file igtlVideoStreamIGTLinkReceiver.cxx.
Referenced by RunOnTCPSocket(), and RunOnUDPSocket().
The documentation for this class was generated from the following files:
igtlVideoStreamIGTLinkReceiver.h
igtlVideoStreamIGTLinkReceiver.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012