igtl::Array< T > Class Template Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::Array< T > Class Template Reference
#include <igtlNDArrayMessage.h>
Public Types
typedef std::vector< igtlUint16 > IndexType
Vector type for an index of N-D array.
Public Member Functions
int GetDimension ()
Gets the dimension of the N-D array.
void * GetRawArray ()
Gets the raw byte array stored in the class.
igtlUint64 GetRawArraySize ()
Gets the size of the raw byte array stored in the class.
IndexType GetSize ()
Gets the size of the N-D array.
int GetValue (IndexType index, T &value)
Gets a value of the element specified by 'index'.
int SetArray (void *array)
int SetSize (IndexType size)
Sets the size of the N-D array. Returns non-zero value, if success.
int SetValue (IndexType index, T value)
Sets a value of the element specified by 'index'.
Protected Member Functions
igtlUint32 Get1DIndex (IndexType index)
virtual int GetElementSize ()
Gets the size of elements (e.g. 1 byte in case of 8-bit integer)
igtlUint32 GetNumberOfElements ()
Gets the number of elements in the array.
Detailed Description
template<typename T>
class igtl::Array< T >
Definition at line 87 of file igtlNDArrayMessage.h.
Member Typedef Documentation
IndexType
typedef std::vector<igtlUint16> igtl::ArrayBase::IndexType inherited
Vector type for an index of N-D array.
Definition at line 35 of file igtlNDArrayMessage.h.
Member Function Documentation
Get1DIndex()
igtlUint32 igtl::ArrayBase::Get1DIndex (IndexType index) protected inherited
Returns the 1-D index of the element specified by 'index'. This function is used to calculate the index of the element in the raw array.
Definition at line 108 of file igtlNDArrayMessage.cxx.
References GetNumberOfElements().
Referenced by GetElementSize(), igtl::Array< T >::GetValue(), and igtl::Array< T >::SetValue().
GetDimension()
int igtl::ArrayBase::GetDimension () inline inherited
Gets the dimension of the N-D array.
Definition at line 50 of file igtlNDArrayMessage.h.
GetElementSize()
template<typename T> virtual int igtl::Array< T >::GetElementSize () inline protected virtual
Gets the size of elements (e.g. 1 byte in case of 8-bit integer)
Implements igtl::ArrayBase.
Definition at line 117 of file igtlNDArrayMessage.h.
GetNumberOfElements()
igtlUint32 igtl::ArrayBase::GetNumberOfElements () protected inherited
Gets the number of elements in the array.
Definition at line 96 of file igtlNDArrayMessage.cxx.
Referenced by Get1DIndex(), GetElementSize(), GetRawArraySize(), igtl::Array< T >::GetValue(), and igtl::Array< T >::SetValue().
GetRawArray()
void * igtl::ArrayBase::GetRawArray () inline inherited
Gets the raw byte array stored in the class.
Definition at line 60 of file igtlNDArrayMessage.h.
Referenced by igtl::Array< T >::GetValue(), and igtl::Array< T >::SetValue().
GetRawArraySize()
igtlUint64 igtl::ArrayBase::GetRawArraySize () inherited
Gets the size of the raw byte array stored in the class.
Definition at line 90 of file igtlNDArrayMessage.cxx.
References GetElementSize(), and GetNumberOfElements().
Referenced by SetArray(), and SetSize().
GetSize()
IndexType igtl::ArrayBase::GetSize () inline inherited
Gets the size of the N-D array.
Definition at line 47 of file igtlNDArrayMessage.h.
GetValue()
template<typename T> int igtl::Array< T >::GetValue (IndexType index, T & value) inline
Gets a value of the element specified by 'index'.
Definition at line 103 of file igtlNDArrayMessage.h.
References igtl::ArrayBase::Get1DIndex(), igtl::ArrayBase::GetNumberOfElements(), and igtl::ArrayBase::GetRawArray().
SetArray()
int igtl::ArrayBase::SetArray (void * array) inherited
Sets an array from a byte array. Size and dimension must be specified prior to calling the SetArray() function.
Definition at line 76 of file igtlNDArrayMessage.cxx.
References GetRawArraySize().
SetSize()
int igtl::ArrayBase::SetSize (IndexType size) inherited
Sets the size of the N-D array. Returns non-zero value, if success.
Definition at line 46 of file igtlNDArrayMessage.cxx.
References GetRawArraySize().
SetValue()
template<typename T> int igtl::Array< T >::SetValue (IndexType index, T value) inline
Sets a value of the element specified by 'index'.
Definition at line 91 of file igtlNDArrayMessage.h.
References igtl::ArrayBase::Get1DIndex(), igtl::ArrayBase::GetNumberOfElements(), and igtl::ArrayBase::GetRawArray().
The documentation for this class was generated from the following file:
igtlNDArrayMessage.h
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012