webSocketServer Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
webSocketServer Class Reference
#include <igtlWebServerSocket.h>
Public Types
typedef websocketpp::connection_hdl connection_hdl
typedef websocketpp::server< websocketpp::config::asio > server
Public Member Functions
int CreateHTTPServer (std::string docroot, uint16_t port)
int CreateServer (uint16_t port)
void on_close (connection_hdl hdl)
void on_http (connection_hdl hdl)
void on_open (connection_hdl hdl)
void on_timer ()
void Send (void *inputMessage, vcl_size_t len)
void set_timer ()
void SetTimeInterval (unsigned int time)
webSocketServer * WaitForConnection (unsigned long msec)
webSocketServer ()
Data Fields
std::string m_docroot
server m_endpoint
uint16_t port
bool serverCreated
Detailed Description
Definition at line 62 of file igtlWebServerSocket.h.
Member Typedef Documentation
connection_hdl
typedef websocketpp::connection_hdl webSocketServer::connection_hdl
Definition at line 64 of file igtlWebServerSocket.h.
server
typedef websocketpp::server<websocketpp::config::asio> webSocketServer::server
Definition at line 65 of file igtlWebServerSocket.h.
Constructor & Destructor Documentation
webSocketServer()
webSocketServer::webSocketServer ()
Definition at line 11 of file igtlWebServerSocket.cxx.
References m_endpoint, on_close(), on_http(), and on_open().
Referenced by WaitForConnection().
Member Function Documentation
CreateHTTPServer()
int webSocketServer::CreateHTTPServer (std::string docroot, uint16_t port)
Definition at line 38 of file igtlWebServerSocket.cxx.
References m_docroot, and port.
CreateServer()
int webSocketServer::CreateServer (uint16_t port)
Definition at line 33 of file igtlWebServerSocket.cxx.
References port.
on_close()
void webSocketServer::on_close (connection_hdl hdl)
Definition at line 186 of file igtlWebServerSocket.cxx.
Referenced by webSocketServer().
on_http()
void webSocketServer::on_http (connection_hdl hdl)
Definition at line 133 of file igtlWebServerSocket.cxx.
References m_docroot, and m_endpoint.
Referenced by webSocketServer().
on_open()
void webSocketServer::on_open (connection_hdl hdl)
Definition at line 182 of file igtlWebServerSocket.cxx.
Referenced by webSocketServer().
on_timer()
void webSocketServer::on_timer ()
Definition at line 111 of file igtlWebServerSocket.cxx.
References m_endpoint, action::msg, and set_timer().
Referenced by set_timer().
Send()
void webSocketServer::Send (void * inputMessage, vcl_size_t len)
Definition at line 91 of file igtlWebServerSocket.cxx.
References MESSAGE.
set_timer()
void webSocketServer::set_timer ()
Definition at line 105 of file igtlWebServerSocket.cxx.
References m_endpoint, and on_timer().
Referenced by on_timer().
SetTimeInterval()
void webSocketServer::SetTimeInterval (unsigned int time)
Definition at line 28 of file igtlWebServerSocket.cxx.
WaitForConnection()
webSocketServer * webSocketServer::WaitForConnection (unsigned long msec)
Definition at line 45 of file igtlWebServerSocket.cxx.
References igtl::Sleep(), and webSocketServer().
Field Documentation
m_docroot
std::string webSocketServer::m_docroot
Definition at line 79 of file igtlWebServerSocket.h.
Referenced by CreateHTTPServer(), and on_http().
m_endpoint
server webSocketServer::m_endpoint
Definition at line 78 of file igtlWebServerSocket.h.
Referenced by on_http(), on_timer(), set_timer(), and webSocketServer().
port
uint16_t webSocketServer::port
Definition at line 81 of file igtlWebServerSocket.h.
Referenced by CreateHTTPServer(), and CreateServer().
serverCreated
bool webSocketServer::serverCreated
Definition at line 80 of file igtlWebServerSocket.h.
The documentation for this class was generated from the following files:
igtlWebServerSocket.h
igtlWebServerSocket.cxx
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012