igtl::PolyDataAttribute Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::PolyDataAttribute Class Reference
Attribute class used for passing attribute data.
#include <igtlPolyDataMessage.h>
Public Types
enum {
POINT_SCALAR = 0x00 ,
POINT_VECTOR = 0x01 ,
POINT_NORMAL = 0x02 ,
POINT_TENSOR = 0x03 ,
POINT_RGBA = 0x04 ,
POINT_TCOORDS = 0x05 ,
CELL_SCALAR = 0x10 ,
CELL_VECTOR = 0x11 ,
CELL_NORMAL = 0x12 ,
CELL_TENSOR = 0x13 ,
CELL_RGBA = 0x14 ,
CELL_TCOORDS = 0x15
}
Point and cell types.
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
std::vector< igtlFloat32 >::iterator begin ()
Implement support for C++11 ranged for loops.
std::vector< igtlFloat32 >::const_iterator begin () const
void Clear ()
Clears the attributes.
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
std::vector< igtlFloat32 >::iterator end ()
std::vector< igtlFloat32 >::const_iterator end () const
int GetData (igtlFloat32 *data)
Gets the attribute as a byte array.
bool GetDebug () const
const char * GetName ()
Gets the name of the attribute.
virtual const char * GetNameOfClass () const
int GetNthData (unsigned int n, igtlFloat32 *data)
Gets the Nth data.
int GetNthData (unsigned int n, std::vector< igtlFloat32 > &data)
Gets the Nth data.
igtlUint32 GetNumberOfComponents ()
virtual int GetReferenceCount () const
igtlUint32 GetSize ()
Gets the size of the attribute.
igtlUint8 GetType ()
Gets the attribute type.
igtlNewMacro (igtl::PolyDataAttribute)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::PolyDataAttribute, igtl::Object)
void Print (std::ostream &os) const
std::vector< igtlFloat32 >::reverse_iterator rbegin ()
std::vector< igtlFloat32 >::const_reverse_iterator rbegin () const
void Register () const override
std::vector< igtlFloat32 >::reverse_iterator rend ()
std::vector< igtlFloat32 >::const_reverse_iterator rend () const
int SetData (igtlFloat32 *data)
Sets the attribute by byte array.
void SetDebug (bool debugFlag) const
void SetName (const char *name)
Sets the name of the attribute.
int SetNthData (unsigned int n, igtlFloat32 *data)
Sets the Nth data.
void SetReferenceCount (int) override
igtlUint32 SetSize (igtlUint32 size)
Sets the size of the attribute.
int SetType (int t, int n=1)
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
PolyDataAttribute ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
~PolyDataAttribute ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Attribute class used for passing attribute data.
Definition at line 226 of file igtlPolyDataMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Point and cell types.
Enumerator
POINT_SCALAR
POINT_VECTOR
POINT_NORMAL
POINT_TENSOR
POINT_RGBA
POINT_TCOORDS
CELL_SCALAR
CELL_VECTOR
CELL_NORMAL
CELL_TENSOR
CELL_RGBA
CELL_TCOORDS
Definition at line 230 of file igtlPolyDataMessage.h.
Constructor & Destructor Documentation
PolyDataAttribute()
igtl::PolyDataAttribute::PolyDataAttribute () protected
Definition at line 248 of file igtlPolyDataMessage.cxx.
References Clear(), and igtl::Object::Object().
Referenced by igtlNewMacro().
~PolyDataAttribute()
igtl::PolyDataAttribute::~PolyDataAttribute () protected
Definition at line 254 of file igtlPolyDataMessage.cxx.
Member Function Documentation
begin() [1/2]
std::vector< igtlFloat32 >::iterator igtl::PolyDataAttribute::begin ()
Implement support for C++11 ranged for loops.
Definition at line 444 of file igtlPolyDataMessage.cxx.
Referenced by igtl::begin(), and igtl::begin().
begin() [2/2]
std::vector< igtlFloat32 >::const_iterator igtl::PolyDataAttribute::begin () const
Definition at line 452 of file igtlPolyDataMessage.cxx.
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
Clear()
void igtl::PolyDataAttribute::Clear ()
Clears the attributes.
Definition at line 258 of file igtlPolyDataMessage.cxx.
References POINT_SCALAR.
Referenced by igtlNewMacro(), and PolyDataAttribute().
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
end() [1/2]
std::vector< igtlFloat32 >::iterator igtl::PolyDataAttribute::end ()
Definition at line 448 of file igtlPolyDataMessage.cxx.
Referenced by igtl::end(), and igtl::end().
end() [2/2]
std::vector< igtlFloat32 >::const_iterator igtl::PolyDataAttribute::end () const
Definition at line 456 of file igtlPolyDataMessage.cxx.
GetData()
int igtl::PolyDataAttribute::GetData (igtlFloat32 * data)
Gets the attribute as a byte array.
Definition at line 371 of file igtlPolyDataMessage.cxx.
Referenced by igtl::SetPolyDataInfoAttribute().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetName()
const char * igtl::PolyDataAttribute::GetName () inline
Gets the name of the attribute.
Definition at line 284 of file igtlPolyDataMessage.h.
Referenced by igtl::SetPolyDataInfoAttribute().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetNthData() [1/2]
int igtl::PolyDataAttribute::GetNthData (unsigned int n, igtlFloat32 * data)
Gets the Nth data.
Definition at line 405 of file igtlPolyDataMessage.cxx.
GetNthData() [2/2]
int igtl::PolyDataAttribute::GetNthData (unsigned int n, std::vector< igtlFloat32 > & data)
Gets the Nth data.
Definition at line 424 of file igtlPolyDataMessage.cxx.
GetNumberOfComponents()
igtlUint32 igtl::PolyDataAttribute::GetNumberOfComponents ()
Gets the number of components. The number depends on the type of the points/cells e.g. 3 in case of POINT_VECTOR.
Definition at line 323 of file igtlPolyDataMessage.cxx.
Referenced by igtl::SetPolyDataInfoAttribute().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetSize()
igtlUint32 igtl::PolyDataAttribute::GetSize ()
Gets the size of the attribute.
Definition at line 344 of file igtlPolyDataMessage.cxx.
Referenced by igtl::SetPolyDataInfoAttribute().
GetType()
igtlUint8 igtl::PolyDataAttribute::GetType () inline
Gets the attribute type.
Definition at line 268 of file igtlPolyDataMessage.h.
Referenced by igtl::SetPolyDataInfoAttribute().
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::PolyDataAttribute::igtlNewMacro (igtl::PolyDataAttribute)
References Clear(), PolyDataAttribute(), and SetType().
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::PolyDataAttribute::igtlTypeMacro (igtl::PolyDataAttribute , igtl::Object)
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
rbegin() [1/2]
std::vector< igtlFloat32 >::reverse_iterator igtl::PolyDataAttribute::rbegin ()
Definition at line 461 of file igtlPolyDataMessage.cxx.
Referenced by igtl::rbegin(), and igtl::rbegin().
rbegin() [2/2]
std::vector< igtlFloat32 >::const_reverse_iterator igtl::PolyDataAttribute::rbegin () const
Definition at line 469 of file igtlPolyDataMessage.cxx.
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
rend() [1/2]
std::vector< igtlFloat32 >::reverse_iterator igtl::PolyDataAttribute::rend ()
Definition at line 465 of file igtlPolyDataMessage.cxx.
Referenced by igtl::rend(), and igtl::rend().
rend() [2/2]
std::vector< igtlFloat32 >::const_reverse_iterator igtl::PolyDataAttribute::rend () const
Definition at line 473 of file igtlPolyDataMessage.cxx.
SetData()
int igtl::PolyDataAttribute::SetData (igtlFloat32 * data)
Sets the attribute by byte array.
Definition at line 354 of file igtlPolyDataMessage.cxx.
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetName()
void igtl::PolyDataAttribute::SetName (const char * name)
Sets the name of the attribute.
Definition at line 349 of file igtlPolyDataMessage.cxx.
SetNthData()
int igtl::PolyDataAttribute::SetNthData (unsigned int n, igtlFloat32 * data)
Sets the Nth data.
Definition at line 387 of file igtlPolyDataMessage.cxx.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetSize()
igtlUint32 igtl::PolyDataAttribute::SetSize (igtlUint32 size)
Sets the size of the attribute.
Definition at line 328 of file igtlPolyDataMessage.cxx.
SetType()
int igtl::PolyDataAttribute::SetType (int t, int n = 1)
SetType() is used to set the attribute type. If the attribute is set properly, the function returns the type value (POINT_* or CELL_*). Otherwise the function returns negative value. The second argument will be ignored if 't' is neither POINT_SCALAR nor CELL_SCALAR. If the POINT_SCALAR and CELL_SCALAR is specified as 't', the number of components can be specified as the second argument. The number of components must be 0 < n < 128.
Definition at line 267 of file igtlPolyDataMessage.cxx.
References CELL_NORMAL, CELL_RGBA, CELL_SCALAR, CELL_TCOORDS, CELL_TENSOR, CELL_VECTOR, POINT_NORMAL, POINT_RGBA, POINT_SCALAR, POINT_TCOORDS, POINT_TENSOR, and POINT_VECTOR.
Referenced by igtlNewMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlPolyDataMessage.h
igtlPolyDataMessage.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012