igtl::VP9Encoder Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::VP9Encoder Class Reference
#include <igtlVP9Encoder.h>
Public Types
enum {
SlowestSpeed = 0 ,
FastestSpeed = 8
}
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
int ConvertToLocalImageFormat (SourcePicture *pSrcPic) override
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
int EncodeSingleFrameIntoVideoMSG (SourcePicture *pSrcPic, igtl::VideoMessage *videoMessage, bool isGrayImage=false) override
int FillSpecificParameters () override
bool GetDebug () const
virtual bool GetInitializationStatus ()
virtual bool GetLosslessLink ()
virtual const char * GetNameOfClass () const
unsigned int GetPicHeight () override
unsigned int GetPicWidth () override
virtual int GetReferenceCount () const
virtual int GetVideoFrameType ()
igtlNewMacro (VP9Encoder)
igtlTypeMacro (GenericEncoder, Object)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (VP9Encoder, GenericEncoder)
int InitializeEncoder () override
int PackUncompressedData (SourcePicture *pSrcPic, igtl::VideoMessage *videoMessage, bool isGrayImage)
void Print (std::ostream &os) const
void Register () const override
virtual void SetConfigurationFile (std::string configFile)
int SetDeadlineMode (unsigned long mode)
deadline parameter analogous to VPx REALTIME mode.
void SetDebug (bool debugFlag) const
virtual int SetImageFormat (VideoFormatType value)
int SetKeyFrameDistance (int frameNum) override
int SetLosslessLink (bool linkMethod) override
int SetPicWidthAndHeight (unsigned int width, unsigned int height) override
int SetQP (int maxQP, int minQP) override
int SetRCMode (int value) override
int SetRCTargetBitRate (unsigned int bitRate) override
void SetReferenceCount (int) override
int SetSpeed (int speed) override
void UnRegister () const override
VP9Encoder (char *configFile=NULL)
~VP9Encoder ()
Static Public Member Functions
static void BreakOnError ()
static void ConvertRGBToYUV (igtlUint8 *rgb, igtlUint8 *destination, unsigned int width, unsigned int height)
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
Protected Attributes
int codecSpeed
std::string configFile
ReadConfigFile cRdCfg
int encodedFrameType
bool initializationDone
bool isLossLessLink
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
unsigned int picHeight
unsigned int picWidth
Detailed Description
Definition at line 46 of file igtlVP9Encoder.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SlowestSpeed
FastestSpeed
Definition at line 91 of file igtlVP9Encoder.h.
Constructor & Destructor Documentation
VP9Encoder()
igtl::VP9Encoder::VP9Encoder (char * configFile = NULL)
Definition at line 49 of file igtlVP9Encoder.cxx.
References igtl::GenericEncoder::codecSpeed, igtl::GenericEncoder::configFile, FillSpecificParameters(), igtl::FormatI420, igtl::GenericEncoder::GenericEncoder(), igtl::GenericEncoder::isLossLessLink, SetImageFormat(), and igtl::vp9StaticEncoder.
Referenced by igtlNewMacro(), and igtlTypeMacro().
~VP9Encoder()
igtl::VP9Encoder::~VP9Encoder ()
Definition at line 62 of file igtlVP9Encoder.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
ConvertRGBToYUV()
void igtl::GenericEncoder::ConvertRGBToYUV (igtlUint8 * rgb, igtlUint8 * destination, unsigned int width, unsigned int height) static inherited
Definition at line 257 of file igtlCodecCommonClasses.cxx.
ConvertToLocalImageFormat()
int igtl::VP9Encoder::ConvertToLocalImageFormat (SourcePicture * pSrcPic) override virtual
Get the type of encoded frame Convert the generic image format to local specific data format of the codec
Reimplemented from igtl::GenericEncoder.
Definition at line 253 of file igtlVP9Encoder.cxx.
References igtl::SourcePicture::data, InitializeEncoder(), igtl::SourcePicture::picHeight, igtl::SourcePicture::picWidth, and SetPicWidthAndHeight().
Referenced by EncodeSingleFrameIntoVideoMSG(), and igtlNewMacro().
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
EncodeSingleFrameIntoVideoMSG()
int igtl::VP9Encoder::EncodeSingleFrameIntoVideoMSG (SourcePicture * pSrcPic, igtl::VideoMessage * videoMessage, bool isGrayImage = false) override virtual
Encode a frame, for performance issue, before encode the frame, make sure the frame pointer is updated with a new frame. Otherwize, the old frame will be encoded.
Reimplemented from igtl::GenericEncoder.
Definition at line 274 of file igtlVP9Encoder.cxx.
References igtl::VideoMessage::AllocateScalars(), ConvertToLocalImageFormat(), igtl::GenericEncoder::encodedFrameType, igtl::FrameTypeKey, igtl::FrameTypeUnKnown, igtl::VideoMessage::GetBitStreamSize(), igtl::VideoMessage::GetPackFragmentPointer(), igtl_is_little_endian(), IGTL_VIDEO_CODEC_NAME_VP9, IGTL_VIDEO_ENDIAN_BIG, IGTL_VIDEO_ENDIAN_LITTLE, igtl::GenericEncoder::initializationDone, igtl::MessageBase::Pack(), igtl::SourcePicture::picHeight, igtl::SourcePicture::picWidth, igtl::VideoMessage::SetBitStreamSize(), igtl::VideoMessage::SetCodecType(), igtl::VideoMessage::SetEndian(), igtl::VideoMessage::SetFrameType(), igtl::VideoMessage::SetHeight(), SetPicWidthAndHeight(), and igtl::VideoMessage::SetWidth().
Referenced by igtlNewMacro().
FillSpecificParameters()
int igtl::VP9Encoder::FillSpecificParameters () override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 76 of file igtlVP9Encoder.cxx.
References FastestSpeed, and SetSpeed().
Referenced by igtlNewMacro(), and VP9Encoder().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetInitializationStatus()
virtual bool igtl::GenericEncoder::GetInitializationStatus () inline virtual inherited
Get the encoder and server initialization status.
Definition at line 132 of file igtlCodecCommonClasses.h.
References initializationDone.
GetLosslessLink()
virtual bool igtl::GenericEncoder::GetLosslessLink () inline virtual inherited
Reimplemented in igtl::H264Encoder, and igtl::H265Encoder.
Definition at line 151 of file igtlCodecCommonClasses.h.
References isLossLessLink.
Referenced by igtl::igtlAV1Encoder::InitializeEncoder(), and igtl::VP9Encoder::InitializeEncoder().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetPicHeight()
unsigned int igtl::VP9Encoder::GetPicHeight () inline override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 74 of file igtlVP9Encoder.h.
References igtl::GenericEncoder::picHeight.
Referenced by InitializeEncoder().
GetPicWidth()
unsigned int igtl::VP9Encoder::GetPicWidth () inline override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 72 of file igtlVP9Encoder.h.
References igtl::GenericEncoder::picWidth.
Referenced by InitializeEncoder().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetVideoFrameType()
virtual int igtl::GenericEncoder::GetVideoFrameType () inline virtual inherited
Definition at line 143 of file igtlCodecCommonClasses.h.
References encodedFrameType.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::VP9Encoder::igtlNewMacro (VP9Encoder)
References igtl::GenericEncoder::configFile, ConvertToLocalImageFormat(), EncodeSingleFrameIntoVideoMSG(), FillSpecificParameters(), InitializeEncoder(), SetPicWidthAndHeight(), and VP9Encoder().
igtlTypeMacro() [1/3]
igtl::GenericEncoder::igtlTypeMacro (GenericEncoder , Object) inherited
References GenericEncoder(), and igtl::Object::Object().
igtlTypeMacro() [2/3]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [3/3]
igtl::VP9Encoder::igtlTypeMacro (VP9Encoder , GenericEncoder)
References igtl::GenericEncoder::GenericEncoder(), and VP9Encoder().
InitializeEncoder()
int igtl::VP9Encoder::InitializeEncoder () override virtual
Parse the configuration file to initialize the encoder and server.
Implements igtl::GenericEncoder.
Definition at line 197 of file igtlVP9Encoder.cxx.
References igtl::GenericEncoder::codecSpeed, FastestSpeed, igtl::GenericEncoder::GetLosslessLink(), GetPicHeight(), GetPicWidth(), igtl::GenericEncoder::initializationDone, and SlowestSpeed.
Referenced by ConvertToLocalImageFormat(), igtlNewMacro(), and SetPicWidthAndHeight().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
PackUncompressedData()
int igtl::GenericEncoder::PackUncompressedData (SourcePicture * pSrcPic, igtl::VideoMessage * videoMessage, bool isGrayImage) inherited
Definition at line 300 of file igtlCodecCommonClasses.cxx.
References igtl::VideoMessage::AllocateScalars(), igtl::SourcePicture::data, encodedFrameType, igtl::FrameTypeKey, igtl::VideoMessage::GetPackFragmentPointer(), igtl_is_little_endian(), IGTL_VIDEO_ENDIAN_BIG, IGTL_VIDEO_ENDIAN_LITTLE, igtl::MessageBase::Pack(), igtl::SourcePicture::picHeight, igtl::SourcePicture::picWidth, igtl::VideoMessage::SetBitStreamSize(), igtl::VideoMessage::SetEndian(), igtl::VideoMessage::SetFrameType(), igtl::VideoMessage::SetHeight(), and igtl::VideoMessage::SetWidth().
Referenced by igtl::I420Encoder::EncodeSingleFrameIntoVideoMSG().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetConfigurationFile()
virtual void igtl::GenericEncoder::SetConfigurationFile (std::string configFile) inline virtual inherited
Definition at line 119 of file igtlCodecCommonClasses.h.
References configFile.
SetDeadlineMode()
int igtl::VP9Encoder::SetDeadlineMode (unsigned long mode)
deadline parameter analogous to VPx REALTIME mode.
deadline parameter analogous to VPx GOOD QUALITY mode.
deadline parameter analogous to VPx BEST QUALITY mode.
Encode a frame
Definition at line 247 of file igtlVP9Encoder.cxx.
Referenced by SetLosslessLink(), and SetSpeed().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetImageFormat()
int igtl::VP9Encoder::SetImageFormat (VideoFormatType value) virtual
Definition at line 103 of file igtlVP9Encoder.cxx.
References igtl::FormatI420, and igtl::FormatI444.
Referenced by VP9Encoder().
SetKeyFrameDistance()
int igtl::VP9Encoder::SetKeyFrameDistance (int frameNum) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 123 of file igtlVP9Encoder.cxx.
SetLosslessLink()
int igtl::VP9Encoder::SetLosslessLink (bool linkMethod) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 169 of file igtlVP9Encoder.cxx.
References igtl::GenericEncoder::isLossLessLink, and SetDeadlineMode().
SetPicWidthAndHeight()
int igtl::VP9Encoder::SetPicWidthAndHeight (unsigned int width, unsigned int height) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 232 of file igtlVP9Encoder.cxx.
References InitializeEncoder(), igtl::GenericEncoder::picHeight, and igtl::GenericEncoder::picWidth.
Referenced by ConvertToLocalImageFormat(), EncodeSingleFrameIntoVideoMSG(), and igtlNewMacro().
SetQP()
int igtl::VP9Encoder::SetQP (int maxQP, int minQP) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 155 of file igtlVP9Encoder.cxx.
References igtl::GenericEncoder::initializationDone.
SetRCMode()
int igtl::VP9Encoder::SetRCMode (int value) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 92 of file igtlVP9Encoder.cxx.
SetRCTargetBitRate()
int igtl::VP9Encoder::SetRCTargetBitRate (unsigned int bitRate) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 136 of file igtlVP9Encoder.cxx.
References igtl::GenericEncoder::initializationDone.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetSpeed()
int igtl::VP9Encoder::SetSpeed (int speed) override virtual
Reimplemented from igtl::GenericEncoder.
Definition at line 185 of file igtlVP9Encoder.cxx.
References igtl::GenericEncoder::codecSpeed, FastestSpeed, SetDeadlineMode(), and SlowestSpeed.
Referenced by FillSpecificParameters().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
codecSpeed
int igtl::GenericEncoder::codecSpeed protected inherited
Definition at line 185 of file igtlCodecCommonClasses.h.
Referenced by igtl::H265Encoder::FillSpecificParameters(), GenericEncoder(), igtl::H265Encoder::H265Encoder(), igtl::igtlAV1Encoder::igtlAV1Encoder(), igtl::igtlAV1Encoder::InitializeEncoder(), igtl::VP9Encoder::InitializeEncoder(), igtl::H264Encoder::SetSpeed(), igtl::H265Encoder::SetSpeed(), igtl::igtlAV1Encoder::SetSpeed(), igtl::VP9Encoder::SetSpeed(), and igtl::VP9Encoder::VP9Encoder().
configFile
std::string igtl::GenericEncoder::configFile protected inherited
Definition at line 179 of file igtlCodecCommonClasses.h.
Referenced by GenericEncoder(), igtl::H264Encoder::H264Encoder(), igtl::H265Encoder::H265Encoder(), igtl::I420Encoder::I420Encoder(), igtl::igtlAV1Encoder::igtlAV1Encoder(), igtl::H264Encoder::igtlNewMacro(), igtl::H265Encoder::igtlNewMacro(), igtl::I420Encoder::igtlNewMacro(), igtl::igtlAV1Encoder::igtlNewMacro(), igtl::VP9Encoder::igtlNewMacro(), igtl::H264Encoder::InitializeEncoder(), igtl::H265Encoder::InitializeEncoder(), SetConfigurationFile(), and igtl::VP9Encoder::VP9Encoder().
cRdCfg
ReadConfigFile igtl::GenericEncoder::cRdCfg protected inherited
Definition at line 177 of file igtlCodecCommonClasses.h.
Referenced by igtl::H264Encoder::InitializeEncoder().
encodedFrameType
int igtl::GenericEncoder::encodedFrameType protected inherited
Definition at line 175 of file igtlCodecCommonClasses.h.
Referenced by igtl::H264Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::H265Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::igtlAV1Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::VP9Encoder::EncodeSingleFrameIntoVideoMSG(), GenericEncoder(), GetVideoFrameType(), and PackUncompressedData().
initializationDone
bool igtl::GenericEncoder::initializationDone protected inherited
Definition at line 181 of file igtlCodecCommonClasses.h.
Referenced by igtl::H264Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::H265Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::igtlAV1Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::VP9Encoder::EncodeSingleFrameIntoVideoMSG(), GenericEncoder(), GetInitializationStatus(), igtl::H264Encoder::InitializeEncoder(), igtl::H265Encoder::InitializeEncoder(), igtl::igtlAV1Encoder::InitializeEncoder(), igtl::VP9Encoder::InitializeEncoder(), igtl::H264Encoder::SetLosslessLink(), igtl::H264Encoder::SetPicWidthAndHeight(), igtl::H265Encoder::SetPicWidthAndHeight(), igtl::H264Encoder::SetQP(), igtl::H265Encoder::SetQP(), igtl::igtlAV1Encoder::SetQP(), igtl::VP9Encoder::SetQP(), igtl::H264Encoder::SetRCMode(), igtl::H265Encoder::SetRCMode(), igtl::H264Encoder::SetRCTargetBitRate(), igtl::H265Encoder::SetRCTargetBitRate(), igtl::igtlAV1Encoder::SetRCTargetBitRate(), and igtl::VP9Encoder::SetRCTargetBitRate().
isLossLessLink
bool igtl::GenericEncoder::isLossLessLink protected inherited
Definition at line 183 of file igtlCodecCommonClasses.h.
Referenced by GenericEncoder(), GetLosslessLink(), igtl::igtlAV1Encoder::igtlAV1Encoder(), SetLosslessLink(), igtl::H264Encoder::SetLosslessLink(), igtl::igtlAV1Encoder::SetLosslessLink(), igtl::VP9Encoder::SetLosslessLink(), and igtl::VP9Encoder::VP9Encoder().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
picHeight
unsigned int igtl::GenericEncoder::picHeight protected inherited
Definition at line 173 of file igtlCodecCommonClasses.h.
Referenced by GenericEncoder(), GetPicHeight(), igtl::igtlAV1Encoder::GetPicHeight(), igtl::VP9Encoder::GetPicHeight(), igtl::igtlAV1Encoder::SetPicWidthAndHeight(), and igtl::VP9Encoder::SetPicWidthAndHeight().
picWidth
unsigned int igtl::GenericEncoder::picWidth protected inherited
Definition at line 171 of file igtlCodecCommonClasses.h.
Referenced by GenericEncoder(), GetPicWidth(), igtl::igtlAV1Encoder::GetPicWidth(), igtl::VP9Encoder::GetPicWidth(), igtl::igtlAV1Encoder::SetPicWidthAndHeight(), and igtl::VP9Encoder::SetPicWidthAndHeight().
The documentation for this class was generated from the following files:
igtlVP9Encoder.h
igtlVP9Encoder.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012