igtl::TimeStamp Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::TimeStamp Class Reference
#include <igtlTimeStamp.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void GetTime ()
Gets the current time from the system's clock and save it as a time stamp.
double GetTimeStamp ()
Gets the time stamp. Returns a double floating-point value.
void GetTimeStamp (igtlUint32 *second, igtlUint32 *nanosecond)
Gets the time stamp. The second and nanosecond parts are stored in 'second' and 'nanosecond'.
igtlUint64 GetTimeStampInNanoseconds () const
igtlUint64 GetTimeStampUint64 ()
Gets the time stamp. Returns a 64-bit fixed-point expression used in OpenIGTLink.
igtlGetConstMacro (Frequency, igtlUint32)
Gets the frequency of a clock.
igtlGetConstMacro (Nanosecond, igtlUint32)
Gets the fraction of second part of the time stamp.
igtlGetConstMacro (Second, igtlUint32)
Gets the second part of the time stamp.
igtlNewMacro (Self)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (TimeStamp, Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
void SetReferenceCount (int) override
void SetTime (double tm)
Sets the time by double floating-point value.
void SetTime (igtlUint32 second, igtlUint32 nanosecond)
Sets the time by second and nanosecond.
void SetTime (igtlUint64 tm)
Sets the time by using 64-bit fixed-point expression used in OpenIGTLink.
void SetTimeInNanoseconds (igtlUint64 tm)
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
TimeStamp ()
virtual ~TimeStamp ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 30 of file igtlTimeStamp.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
TimeStamp()
igtl::TimeStamp::TimeStamp () protected
constructor
Definition at line 54 of file igtlTimeStamp.cxx.
References igtl::Object::Object().
Referenced by igtlGetConstMacro(), and igtlTypeMacro().
~TimeStamp()
igtl::TimeStamp::~TimeStamp () protected virtual
destructor
Definition at line 126 of file igtlTimeStamp.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetTime()
void igtl::TimeStamp::GetTime ()
Gets the current time from the system's clock and save it as a time stamp.
Definition at line 131 of file igtlTimeStamp.cxx.
Referenced by igtlGetConstMacro().
GetTimeStamp() [1/2]
double igtl::TimeStamp::GetTimeStamp ()
Gets the time stamp. Returns a double floating-point value.
Definition at line 201 of file igtlTimeStamp.cxx.
Referenced by igtlGetConstMacro().
GetTimeStamp() [2/2]
void igtl::TimeStamp::GetTimeStamp (igtlUint32 * second, igtlUint32 * nanosecond)
Gets the time stamp. The second and nanosecond parts are stored in 'second' and 'nanosecond'.
Definition at line 210 of file igtlTimeStamp.cxx.
GetTimeStampInNanoseconds()
igtlUint64 igtl::TimeStamp::GetTimeStampInNanoseconds () const
Gets the time in nano-seconds since the start of time (Unix Epoch = 1 Jan 1970). Note: This is deliberately different to GetTimeStampUint64();
Definition at line 231 of file igtlTimeStamp.cxx.
Referenced by igtlGetConstMacro().
GetTimeStampUint64()
igtlUint64 igtl::TimeStamp::GetTimeStampUint64 ()
Gets the time stamp. Returns a 64-bit fixed-point expression used in OpenIGTLink.
Definition at line 217 of file igtlTimeStamp.cxx.
References igtl_nanosec_to_frac().
Referenced by igtlGetConstMacro().
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlGetConstMacro() [1/3]
igtl::TimeStamp::igtlGetConstMacro (Frequency , igtlUint32)
Gets the frequency of a clock.
igtlGetConstMacro() [2/3]
igtl::TimeStamp::igtlGetConstMacro (Nanosecond , igtlUint32)
Gets the fraction of second part of the time stamp.
References GetTime(), GetTimeStamp(), GetTimeStampInNanoseconds(), GetTimeStampUint64(), PrintSelf(), SetTime(), SetTimeInNanoseconds(), and TimeStamp().
igtlGetConstMacro() [3/3]
igtl::TimeStamp::igtlGetConstMacro (Second , igtlUint32)
Gets the second part of the time stamp.
igtlNewMacro()
igtl::TimeStamp::igtlNewMacro (Self)
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::TimeStamp::igtlTypeMacro (TimeStamp , Object)
References igtl::Object::Object(), and TimeStamp().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::TimeStamp::PrintSelf (std::ostream & os) const override protected virtual
Print the object information in a stream.
Reimplemented from igtl::Object.
Definition at line 238 of file igtlTimeStamp.cxx.
Referenced by igtlGetConstMacro().
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetTime() [1/3]
void igtl::TimeStamp::SetTime (double tm)
Sets the time by double floating-point value.
Definition at line 164 of file igtlTimeStamp.cxx.
Referenced by igtlGetConstMacro().
SetTime() [2/3]
void igtl::TimeStamp::SetTime (igtlUint32 second, igtlUint32 nanosecond)
Sets the time by second and nanosecond.
Definition at line 171 of file igtlTimeStamp.cxx.
SetTime() [3/3]
void igtl::TimeStamp::SetTime (igtlUint64 tm)
Sets the time by using 64-bit fixed-point expression used in OpenIGTLink.
Definition at line 181 of file igtlTimeStamp.cxx.
References igtl_frac_to_nanosec().
SetTimeInNanoseconds()
void igtl::TimeStamp::SetTimeInNanoseconds (igtlUint64 tm)
Sets the time using the total number of nano-seconds since the start of time (Unix Epoch = 1 Jan 1970). Note: This is deliberately different to SetTime();
Definition at line 192 of file igtlTimeStamp.cxx.
Referenced by igtlGetConstMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlTimeStamp.h
igtlTimeStamp.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012