igtl::SessionManager Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::SessionManager Class Reference
#include <igtlSessionManager.h>
Public Types
enum {
MODE_SERVER ,
MODE_CLIENT
}
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
int AddMessageHandler (MessageHandler *)
int Connect ()
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
int Disconnect ()
bool GetDebug () const
const char * GetHostname ()
int GetMode ()
virtual const char * GetNameOfClass () const
int GetPort ()
virtual int GetReferenceCount () const
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (SessionManager, Object) igtlNewMacro(SessionManager)
void Print (std::ostream &os) const
int ProcessMessage ()
int PushMessage (MessageBase *)
void Register () const override
int RemoveMessageHandler (MessageHandler *)
void SetDebug (bool debugFlag) const
void SetHostname (const char *str)
void SetMode (int m)
void SetPort (int p)
void SetReferenceCount (int) override
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
SessionManager ()
~SessionManager ()
Protected Attributes
bool m_ConfigurationUpdated
MessageHandler * m_CurrentMessageHandler
int m_CurrentReadIndex
igtl::MessageHeader::Pointer m_Header
int m_HeaderDeserialized
std::string m_Hostname
std::vector< MessageHandler * > m_MessageHandlerList
int m_Mode
int m_Port
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Socket::Pointer m_Socket
igtl::TimeStamp::Pointer m_TimeStamp
Detailed Description
Definition at line 28 of file igtlSessionManager.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
MODE_SERVER
MODE_CLIENT
Definition at line 35 of file igtlSessionManager.h.
Constructor & Destructor Documentation
SessionManager()
igtl::SessionManager::SessionManager () protected
Definition at line 32 of file igtlSessionManager.cxx.
References m_CurrentReadIndex, m_Header, m_HeaderDeserialized, m_MessageHandlerList, m_Mode, m_TimeStamp, MODE_SERVER, and igtl::LightObject::New().
Referenced by igtlTypeMacro().
~SessionManager()
igtl::SessionManager::~SessionManager () protected
Definition at line 45 of file igtlSessionManager.cxx.
Member Function Documentation
AddMessageHandler()
int igtl::SessionManager::AddMessageHandler (MessageHandler * handler)
Definition at line 50 of file igtlSessionManager.cxx.
References igtl::MessageHandler::GetMessageType(), and m_MessageHandlerList.
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
Connect()
int igtl::SessionManager::Connect ()
Definition at line 85 of file igtlSessionManager.cxx.
References igtl::SmartPointer< TObjectType >::IsNotNull(), m_CurrentReadIndex, m_HeaderDeserialized, m_Hostname, m_Mode, m_Port, m_Socket, MODE_CLIENT, and igtl::LightObject::New().
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
Disconnect()
int igtl::SessionManager::Disconnect ()
Definition at line 144 of file igtlSessionManager.cxx.
References m_Socket.
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetHostname()
const char * igtl::SessionManager::GetHostname () inline
Definition at line 41 of file igtlSessionManager.h.
References m_Hostname.
GetMode()
int igtl::SessionManager::GetMode () inline
Definition at line 48 of file igtlSessionManager.h.
References m_Mode.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetPort()
int igtl::SessionManager::GetPort () inline
Definition at line 43 of file igtlSessionManager.h.
References m_Port.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::SessionManager::igtlTypeMacro (SessionManager , Object)
References igtl::Object::Object(), and SessionManager().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
ProcessMessage()
int igtl::SessionManager::ProcessMessage ()
Definition at line 154 of file igtlSessionManager.cxx.
References IGTL_HEADER_SIZE, m_CurrentMessageHandler, m_CurrentReadIndex, m_Header, m_HeaderDeserialized, m_MessageHandlerList, m_Socket, and m_TimeStamp.
PushMessage()
int igtl::SessionManager::PushMessage (MessageBase * message)
Definition at line 307 of file igtlSessionManager.cxx.
References igtl::MessageBase::GetBufferPointer(), igtl::MessageBase::GetBufferSize(), and m_Socket.
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
RemoveMessageHandler()
int igtl::SessionManager::RemoveMessageHandler (MessageHandler * handler)
Definition at line 69 of file igtlSessionManager.cxx.
References m_MessageHandlerList.
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetHostname()
void igtl::SessionManager::SetHostname (const char * str) inline
Definition at line 40 of file igtlSessionManager.h.
References m_ConfigurationUpdated, and m_Hostname.
SetMode()
void igtl::SessionManager::SetMode (int m) inline
Definition at line 47 of file igtlSessionManager.h.
References m_ConfigurationUpdated, and m_Mode.
SetPort()
void igtl::SessionManager::SetPort (int p) inline
Definition at line 42 of file igtlSessionManager.h.
References m_ConfigurationUpdated, and m_Port.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_ConfigurationUpdated
bool igtl::SessionManager::m_ConfigurationUpdated protected
Definition at line 67 of file igtlSessionManager.h.
Referenced by SetHostname(), SetMode(), and SetPort().
m_CurrentMessageHandler
MessageHandler* igtl::SessionManager::m_CurrentMessageHandler protected
Definition at line 79 of file igtlSessionManager.h.
Referenced by ProcessMessage().
m_CurrentReadIndex
int igtl::SessionManager::m_CurrentReadIndex protected
Definition at line 76 of file igtlSessionManager.h.
Referenced by Connect(), ProcessMessage(), and SessionManager().
m_Header
igtl::MessageHeader::Pointer igtl::SessionManager::m_Header protected
Definition at line 84 of file igtlSessionManager.h.
Referenced by ProcessMessage(), and SessionManager().
m_HeaderDeserialized
int igtl::SessionManager::m_HeaderDeserialized protected
Definition at line 77 of file igtlSessionManager.h.
Referenced by Connect(), ProcessMessage(), and SessionManager().
m_Hostname
std::string igtl::SessionManager::m_Hostname protected
Definition at line 68 of file igtlSessionManager.h.
Referenced by Connect(), GetHostname(), and SetHostname().
m_MessageHandlerList
std::vector< MessageHandler* > igtl::SessionManager::m_MessageHandlerList protected
Definition at line 81 of file igtlSessionManager.h.
Referenced by AddMessageHandler(), ProcessMessage(), RemoveMessageHandler(), and SessionManager().
m_Mode
int igtl::SessionManager::m_Mode protected
Definition at line 70 of file igtlSessionManager.h.
Referenced by Connect(), GetMode(), SessionManager(), and SetMode().
m_Port
int igtl::SessionManager::m_Port protected
Definition at line 69 of file igtlSessionManager.h.
Referenced by Connect(), GetPort(), and SetPort().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_Socket
Socket::Pointer igtl::SessionManager::m_Socket protected
Definition at line 82 of file igtlSessionManager.h.
Referenced by Connect(), Disconnect(), ProcessMessage(), and PushMessage().
m_TimeStamp
igtl::TimeStamp::Pointer igtl::SessionManager::m_TimeStamp protected
Definition at line 85 of file igtlSessionManager.h.
Referenced by ProcessMessage(), and SessionManager().
The documentation for this class was generated from the following files:
igtlSessionManager.h
igtlSessionManager.cxx
Generated at Tue Sep 9 2025 15:29:17 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012