igtl::LightObject Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::LightObject Class Reference
Light weight base class for most igtl classes.
#include <igtlLightObject.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
virtual Pointer CreateAnother () const
virtual void Delete ()
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
void Print (std::ostream &os) const
virtual void Register () const
virtual void SetReferenceCount (int)
virtual void UnRegister () const
Static Public Member Functions
static void BreakOnError ()
static Pointer New ()
Protected Member Functions
LightObject ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const
virtual void PrintTrailer (std::ostream &os) const
virtual ~LightObject ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Light weight base class for most igtl classes.
LightObject is the highest level base class for most igtl objects. It implements reference counting and the API for object printing. It can be used as a lightweight base class in preference to Object. (LightObject does not support callbacks or modified time as Object does.) All IGTL objects should be a subclass of LightObject or Object with few exceptions (due to performance concerns).
See also
Object
Definition at line 58 of file igtlLightObject.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
LightObject()
igtl::LightObject::LightObject () inline protected
Definition at line 117 of file igtlLightObject.h.
References m_ReferenceCount.
Referenced by igtl::ConditionVariable::igtlTypeMacro(), igtl::Object::igtlTypeMacro(), New(), and igtl::Object::Object().
~LightObject()
igtl::LightObject::~LightObject () protected virtual
warn user if reference counting is on and the object is being referenced by another object.
Definition at line 195 of file igtlLightObject.cxx.
References igtlWarningMacro, and m_ReferenceCount.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::LightObject::CreateAnother () const virtual
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented in igtl::Object.
Definition at line 66 of file igtlLightObject.cxx.
References New().
Delete()
void igtl::LightObject::Delete () virtual
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
New()
LightObject::Pointer igtl::LightObject::New () static
Method for creation through the object factory.
Definition at line 52 of file igtlLightObject.cxx.
References igtl::ObjectFactory< T >::Create(), LightObject(), and UnRegister().
Referenced by igtl::MessageBase::Clone(), igtl::SessionManager::Connect(), CreateAnother(), igtl::VideoStreamIGTLinkServer::EncodeFile(), igtl::VideoStreamIGTLinkServer::EncodeSingleFrame(), igtl::MessageFactory::MessageFactory(), igtl::MessageRTPWrapper::MessageRTPWrapper(), igtl::VideoStreamIGTLinkReceiver::RunOnTCPSocket(), igtl::VideoStreamIGTLinkReceiver::RunOnUDPSocket(), igtl::VideoStreamIGTLinkServer::SendOriginalData(), igtl::VideoStreamIGTLinkReceiver::SendStopMessage(), igtl::SessionManager::SessionManager(), igtl::MultiThreader::SpawnThread(), igtl::ThreadFunctionServer(), igtl::ImageMetaMessage::UnpackContent(), igtl::LabelMetaMessage::UnpackContent(), igtl::PointMessage::UnpackContent(), igtl::PolyDataMessage::UnpackContent(), igtl::QuaternionTrackingDataMessage::UnpackContent(), igtl::TrackingDataMessage::UnpackContent(), igtl::TrajectoryMessage::UnpackContent(), igtl::VideoMetaMessage::UnpackContent(), igtl::VideoStreamIGTLinkReceiver::VideoStreamIGTLinkReceiver(), igtl::VideoStreamIGTLinkServer::VideoStreamIGTLinkServer(), and igtl::ServerSocket::WaitForConnection().
Print()
void igtl::LightObject::Print (std::ostream & os) const
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::LightObject::PrintSelf (std::ostream & os) const protected virtual
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::Object, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 214 of file igtlLightObject.cxx.
References m_ReferenceCount.
Referenced by Print().
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::LightObject::Register () const virtual
Increase the reference count (mark as used by another object).
Reimplemented in igtl::Object.
Definition at line 149 of file igtlLightObject.cxx.
References m_ReferenceCount, and m_ReferenceCountLock.
SetReferenceCount()
void igtl::LightObject::SetReferenceCount (int ref) virtual
Sets the reference count on this object. This is a dangerous method, use it with care.
Sets the reference count (use with care)
Reimplemented in igtl::Object.
Definition at line 182 of file igtlLightObject.cxx.
References m_ReferenceCount, and m_ReferenceCountLock.
UnRegister()
void igtl::LightObject::UnRegister () const virtual
Decrease the reference count (release by another object).
Reimplemented in igtl::Object.
Definition at line 162 of file igtlLightObject.cxx.
References m_ReferenceCount, and m_ReferenceCountLock.
Referenced by Delete(), and New().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlLightObject.h
igtlLightObject.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012