igtl::LabelMetaElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::LabelMetaElement Class Reference
#include <igtlLabelMetaMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
const char * GetDeviceName ()
Gets the device name (message name).
igtlUint8 GetLabel ()
Gets the label of the structure.
const char * GetName ()
Gets the image name/description.
virtual const char * GetNameOfClass () const
const char * GetOwner ()
Gets the name of the image that owns this label map.
virtual int GetReferenceCount () const
void GetRGBA (igtlUint8 &r, igtlUint8 &g, igtlUint8 &b, igtlUint8 &a)
Gets the color of the structure by R, G, B, and A values.
void GetRGBA (igtlUint8 *rgba)
Gets the color of the structure by an array representing RGBA.
void GetSize (igtlUint16 &si, igtlUint16 &sj, igtlUint16 &sk)
Gets the size of the image by the numbers of voxels in i, j, and k directions.
void GetSize (igtlUint16 *size)
igtlNewMacro (igtl::LabelMetaElement)
igtlTypeMacro (igtl::LabelMetaElement, igtl::Object)
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
int SetDeviceName (const char *devname)
void SetLabel (igtlUint8 label)
Sets the label of the structure.
int SetName (const char *name)
Sets the image name/description. The string 'name' must not exceed 64 characters.
int SetOwner (const char *owner)
Sets the name of the image that owns this label map.
void SetReferenceCount (int) override
void SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the structure by R, G, B, and A values.
void SetRGBA (igtlUint8 rgba[4])
Sets the color of the structure by an array representing RGBA.
void SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
Sets the size of the image by the numbers of voxels in i, j, and k directions.
void SetSize (igtlUint16 size[3])
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
LabelMetaElement ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
~LabelMetaElement ()
Protected Attributes
std::string m_DeviceName
Device name to query the IMAGE and COLORT.
igtlUint8 m_Label
Label.
std::string m_Name
Name / description (<= 64 bytes)
std::string m_Owner
device name of the owner image. (can be empty)
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_RGBA [4]
Color in RGBA. default: (0, 0, 0, 0)
igtlUint16 m_Size [3]
entire image volume size
Detailed Description
Definition at line 31 of file igtlLabelMetaMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
LabelMetaElement()
igtl::LabelMetaElement::LabelMetaElement () protected
Definition at line 34 of file igtlLabelMetaMessage.cxx.
References m_DeviceName, m_Label, m_Name, m_Owner, m_RGBA, m_Size, and igtl::Object::Object().
~LabelMetaElement()
igtl::LabelMetaElement::~LabelMetaElement () protected
Definition at line 50 of file igtlLabelMetaMessage.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetDeviceName()
const char * igtl::LabelMetaElement::GetDeviceName () inline
Gets the device name (message name).
Definition at line 50 of file igtlLabelMetaMessage.h.
References m_DeviceName.
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetLabel()
igtlUint8 igtl::LabelMetaElement::GetLabel () inline
Gets the label of the structure.
Definition at line 56 of file igtlLabelMetaMessage.h.
References m_Label.
GetName()
const char * igtl::LabelMetaElement::GetName () inline
Gets the image name/description.
Definition at line 43 of file igtlLabelMetaMessage.h.
References m_Name.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetOwner()
const char * igtl::LabelMetaElement::GetOwner () inline
Gets the name of the image that owns this label map.
Definition at line 88 of file igtlLabelMetaMessage.h.
References m_Owner.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetRGBA() [1/2]
void igtl::LabelMetaElement::GetRGBA (igtlUint8 & r, igtlUint8 & g, igtlUint8 & b, igtlUint8 & a)
Gets the color of the structure by R, G, B, and A values.
Definition at line 111 of file igtlLabelMetaMessage.cxx.
References m_RGBA.
GetRGBA() [2/2]
void igtl::LabelMetaElement::GetRGBA (igtlUint8 * rgba)
Gets the color of the structure by an array representing RGBA.
Definition at line 101 of file igtlLabelMetaMessage.cxx.
References m_RGBA.
GetSize() [1/2]
void igtl::LabelMetaElement::GetSize (igtlUint16 & si, igtlUint16 & sj, igtlUint16 & sk)
Gets the size of the image by the numbers of voxels in i, j, and k directions.
Definition at line 144 of file igtlLabelMetaMessage.cxx.
References m_Size.
GetSize() [2/2]
void igtl::LabelMetaElement::GetSize (igtlUint16 * size)
Gets the size of the image using an array containing the numbers of voxels in i, j, and k directions.
Definition at line 136 of file igtlLabelMetaMessage.cxx.
References m_Size.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::LabelMetaElement::igtlNewMacro (igtl::LabelMetaElement)
References SetName().
igtlTypeMacro() [1/2]
igtl::LabelMetaElement::igtlTypeMacro (igtl::LabelMetaElement , igtl::Object)
igtlTypeMacro() [2/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetDeviceName()
int igtl::LabelMetaElement::SetDeviceName (const char * devname)
Sets the device name (message name). The string 'devname' must not exceed 20 characters.
Definition at line 69 of file igtlLabelMetaMessage.cxx.
References IGTL_LBMETA_LEN_DEVICE_NAME, and m_DeviceName.
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetLabel()
void igtl::LabelMetaElement::SetLabel (igtlUint8 label) inline
Sets the label of the structure.
Definition at line 53 of file igtlLabelMetaMessage.h.
References m_Label.
SetName()
int igtl::LabelMetaElement::SetName (const char * name)
Sets the image name/description. The string 'name' must not exceed 64 characters.
Definition at line 55 of file igtlLabelMetaMessage.cxx.
References IGTL_LBMETA_LEN_NAME, and m_Name.
Referenced by igtlNewMacro().
SetOwner()
int igtl::LabelMetaElement::SetOwner (const char * owner)
Sets the name of the image that owns this label map.
Definition at line 152 of file igtlLabelMetaMessage.cxx.
References IGTL_LBMETA_LEN_OWNER, and m_Owner.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetRGBA() [1/2]
void igtl::LabelMetaElement::SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the structure by R, G, B, and A values.
Definition at line 92 of file igtlLabelMetaMessage.cxx.
References m_RGBA.
SetRGBA() [2/2]
void igtl::LabelMetaElement::SetRGBA (igtlUint8 rgba[4])
Sets the color of the structure by an array representing RGBA.
Definition at line 83 of file igtlLabelMetaMessage.cxx.
References m_RGBA.
SetSize() [1/2]
void igtl::LabelMetaElement::SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
Sets the size of the image by the numbers of voxels in i, j, and k directions.
Definition at line 128 of file igtlLabelMetaMessage.cxx.
References m_Size.
SetSize() [2/2]
void igtl::LabelMetaElement::SetSize (igtlUint16 size[3])
Sets the size of the image by an array containing the numbers of voxels in i, j, and k directions.
Definition at line 120 of file igtlLabelMetaMessage.cxx.
References m_Size.
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_DeviceName
std::string igtl::LabelMetaElement::m_DeviceName protected
Device name to query the IMAGE and COLORT.
Definition at line 100 of file igtlLabelMetaMessage.h.
Referenced by GetDeviceName(), LabelMetaElement(), and SetDeviceName().
m_Label
igtlUint8 igtl::LabelMetaElement::m_Label protected
Label.
Definition at line 103 of file igtlLabelMetaMessage.h.
Referenced by GetLabel(), LabelMetaElement(), and SetLabel().
m_Name
std::string igtl::LabelMetaElement::m_Name protected
Name / description (<= 64 bytes)
Definition at line 97 of file igtlLabelMetaMessage.h.
Referenced by GetName(), LabelMetaElement(), and SetName().
m_Owner
std::string igtl::LabelMetaElement::m_Owner protected
device name of the owner image. (can be empty)
Definition at line 112 of file igtlLabelMetaMessage.h.
Referenced by GetOwner(), LabelMetaElement(), and SetOwner().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_RGBA
igtlUint8 igtl::LabelMetaElement::m_RGBA[4] protected
Color in RGBA. default: (0, 0, 0, 0)
Definition at line 106 of file igtlLabelMetaMessage.h.
Referenced by GetRGBA(), GetRGBA(), LabelMetaElement(), SetRGBA(), and SetRGBA().
m_Size
igtlUint16 igtl::LabelMetaElement::m_Size[3] protected
entire image volume size
Definition at line 109 of file igtlLabelMetaMessage.h.
Referenced by GetSize(), GetSize(), LabelMetaElement(), SetSize(), and SetSize().
The documentation for this class was generated from the following files:
igtlLabelMetaMessage.h
igtlLabelMetaMessage.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012