igtl::VideoMetaElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::VideoMetaElement Class Reference
A class to manage meta data of images.
#include <igtlVideoMetaMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
const char * GetDeviceName ()
Gets the device name (message name).
igtlFloat64 GetFocalLength ()
Gets the focal length of the camera (e.g.+50.0mm, +200.0mm).
void GetMatrix (Matrix4x4 &mat)
Gets the origin/orientation matrix.
const char * GetName ()
Gets the image name/description.
virtual const char * GetNameOfClass () const
void GetNormals (float t[3], float s[3], float n[3])
Gets the orientation of the image using the normal vectors for the i, j and k indeces.
void GetOrigin (float &px, float &py, float &pz)
const char * GetPatientID ()
Gets the patient ID.
const char * GetPatientName ()
Gets the patient name.
virtual int GetReferenceCount () const
igtlUint8 GetScalarType ()
Gets the scalar type of the image.
void GetSize (igtlUint16 &si, igtlUint16 &sj, igtlUint16 &sk)
Gets the size of the image by the numbers of voxels in i, j, and k directions.
void GetSpacing (float &si, float &sj, float &sk)
Gets spacings using spacing values in i, j and k directions.
igtlInt16 GetZoomLevel ()
Gets the zoom level of the camera (e.g. +4, -4).
igtlNewMacro (igtl::VideoMetaElement)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::VideoMetaElement, igtl::Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
int SetDeviceName (const char *devname)
void SetFocalLength (igtlFloat64 length)
Sets the focal length of the camera (e.g. +50.0mm, +200.0mm).
void SetMatrix (Matrix4x4 &mat)
Sets the origin/orientation matrix.
int SetName (const char *name)
Sets the image name/description. The string 'name' must not exceed 64 characters.
void SetNormals (float t[3], float s[3], float n[3])
Sets the orientation of the image by the normal vectors for the i, j and k indeces.
void SetOrigin (float px, float py, float pz)
int SetPatientID (const char *patid)
Sets the patient ID. The string 'patid' must not exceed 64 characters.
int SetPatientName (const char *patname)
Sets the patient name. The string 'patname' must not exceed 64 characters.
void SetReferenceCount (int) override
void SetScalarType (igtlUint8 type)
Sets the scalar type of the image.
void SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
Sets the size of the image by the numbers of voxels in i, j, and k directions.
void SetSpacing (float si, float sj, float sk)
Sets spacings by spacing values in i, j and k directions.
void SetZoomLevel (igtlInt16 level)
Sets the zoom level of the camera (e.g. +4, -4).
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
VideoMetaElement ()
~VideoMetaElement ()
Protected Attributes
std::string m_DeviceName
device name to query the IMAGE and COLORT
igtlFloat64 m_FocalLength
Focal length of the camera.
std::string m_Name
name / description (<= 64 bytes)
std::string m_PatientID
patient ID (MRN etc.) (<= 64 bytes)
std::string m_PatientName
patient name (<= 64 bytes)
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_ScalarType
scalar type. see scalar_type in Video message
igtlUint16 m_Size [3]
entire image volume size, if the video is from ultrasound
igtlInt16 m_ZoomLevel
Zoom level of the camera.
Matrix4x4 matrix
float spacing [3]
A vector containing the spacings of the voxels in i, j and k directions.
Detailed Description
A class to manage meta data of images.
Definition at line 32 of file igtlVideoMetaMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
VideoMetaElement()
igtl::VideoMetaElement::VideoMetaElement () protected
Definition at line 33 of file igtlVideoMetaMessage.cxx.
References m_FocalLength, m_ScalarType, m_Size, m_ZoomLevel, matrix, igtl::Object::Object(), and spacing.
~VideoMetaElement()
igtl::VideoMetaElement::~VideoMetaElement () protected
Definition at line 55 of file igtlVideoMetaMessage.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetDeviceName()
const char * igtl::VideoMetaElement::GetDeviceName () inline
Gets the device name (message name).
Definition at line 51 of file igtlVideoMetaMessage.h.
References m_DeviceName.
GetFocalLength()
igtlFloat64 igtl::VideoMetaElement::GetFocalLength () inline
Gets the focal length of the camera (e.g.+50.0mm, +200.0mm).
Definition at line 63 of file igtlVideoMetaMessage.h.
References m_FocalLength.
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetMatrix()
void igtl::VideoMetaElement::GetMatrix (Matrix4x4 & mat)
Gets the origin/orientation matrix.
Definition at line 207 of file igtlVideoMetaMessage.cxx.
References matrix.
GetName()
const char * igtl::VideoMetaElement::GetName () inline
Gets the image name/description.
Definition at line 44 of file igtlVideoMetaMessage.h.
References m_Name.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetNormals()
void igtl::VideoMetaElement::GetNormals (float t[3], float s[3], float n[3])
Gets the orientation of the image using the normal vectors for the i, j and k indeces.
Definition at line 171 of file igtlVideoMetaMessage.cxx.
References matrix.
GetOrigin()
void igtl::VideoMetaElement::GetOrigin (float & px, float & py, float & pz)
Gets the coordinates of the origin by positions along the first (R or L), second (A or P) and the third (S) axes.
Definition at line 151 of file igtlVideoMetaMessage.cxx.
References matrix.
GetPatientID()
const char * igtl::VideoMetaElement::GetPatientID () inline
Gets the patient ID.
Definition at line 75 of file igtlVideoMetaMessage.h.
References m_PatientID.
GetPatientName()
const char * igtl::VideoMetaElement::GetPatientName () inline
Gets the patient name.
Definition at line 69 of file igtlVideoMetaMessage.h.
References m_PatientName.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetScalarType()
igtlUint8 igtl::VideoMetaElement::GetScalarType ()
Gets the scalar type of the image.
Definition at line 248 of file igtlVideoMetaMessage.cxx.
References m_ScalarType.
GetSize()
void igtl::VideoMetaElement::GetSize (igtlUint16 & si, igtlUint16 & sj, igtlUint16 & sk)
Gets the size of the image by the numbers of voxels in i, j, and k directions.
Definition at line 122 of file igtlVideoMetaMessage.cxx.
References m_Size.
GetSpacing()
void igtl::VideoMetaElement::GetSpacing (float & si, float & sj, float & sk)
Gets spacings using spacing values in i, j and k directions.
Definition at line 137 of file igtlVideoMetaMessage.cxx.
References spacing.
GetZoomLevel()
igtlInt16 igtl::VideoMetaElement::GetZoomLevel () inline
Gets the zoom level of the camera (e.g. +4, -4).
Definition at line 57 of file igtlVideoMetaMessage.h.
References m_ZoomLevel.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::VideoMetaElement::igtlNewMacro (igtl::VideoMetaElement)
References SetName().
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::VideoMetaElement::igtlTypeMacro (igtl::VideoMetaElement , igtl::Object)
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetDeviceName()
int igtl::VideoMetaElement::SetDeviceName (const char * devname)
Sets the device name (message name). The string 'devname' must not exceed 20 characters.
Definition at line 74 of file igtlVideoMetaMessage.cxx.
References IGTL_VIDEOMETA_LEN_DEVICE_NAME, and m_DeviceName.
SetFocalLength()
void igtl::VideoMetaElement::SetFocalLength (igtlFloat64 length) inline
Sets the focal length of the camera (e.g. +50.0mm, +200.0mm).
Definition at line 60 of file igtlVideoMetaMessage.h.
References m_FocalLength.
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetMatrix()
void igtl::VideoMetaElement::SetMatrix (Matrix4x4 & mat)
Sets the origin/orientation matrix.
Definition at line 184 of file igtlVideoMetaMessage.cxx.
References matrix.
SetName()
int igtl::VideoMetaElement::SetName (const char * name)
Sets the image name/description. The string 'name' must not exceed 64 characters.
Definition at line 60 of file igtlVideoMetaMessage.cxx.
References IGTL_VIDEOMETA_LEN_NAME, and m_Name.
Referenced by igtlNewMacro().
SetNormals()
void igtl::VideoMetaElement::SetNormals (float t[3], float s[3], float n[3])
Sets the orientation of the image by the normal vectors for the i, j and k indeces.
Definition at line 158 of file igtlVideoMetaMessage.cxx.
References matrix.
SetOrigin()
void igtl::VideoMetaElement::SetOrigin (float px, float py, float pz)
Sets the coordinates of the origin by positions along the first (R or L), second (A or P) and the third (S) axes.
Definition at line 144 of file igtlVideoMetaMessage.cxx.
References matrix.
SetPatientID()
int igtl::VideoMetaElement::SetPatientID (const char * patid)
Sets the patient ID. The string 'patid' must not exceed 64 characters.
Definition at line 101 of file igtlVideoMetaMessage.cxx.
References IGTL_VIDEOMETA_LEN_PATIENT_ID, and m_PatientID.
SetPatientName()
int igtl::VideoMetaElement::SetPatientName (const char * patname)
Sets the patient name. The string 'patname' must not exceed 64 characters.
Definition at line 87 of file igtlVideoMetaMessage.cxx.
References IGTL_VIDEOMETA_LEN_PATIENT_NAME, and m_PatientName.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetScalarType()
void igtl::VideoMetaElement::SetScalarType (igtlUint8 type)
Sets the scalar type of the image.
Definition at line 230 of file igtlVideoMetaMessage.cxx.
References IGTL_VIDEO_STYPE_TYPE_INT16, IGTL_VIDEO_STYPE_TYPE_INT32, IGTL_VIDEO_STYPE_TYPE_INT8, IGTL_VIDEO_STYPE_TYPE_UINT16, IGTL_VIDEO_STYPE_TYPE_UINT32, IGTL_VIDEO_STYPE_TYPE_UINT8, and m_ScalarType.
SetSize()
void igtl::VideoMetaElement::SetSize (igtlUint16 si, igtlUint16 sj, igtlUint16 sk)
Sets the size of the image by the numbers of voxels in i, j, and k directions.
Definition at line 115 of file igtlVideoMetaMessage.cxx.
References m_Size.
SetSpacing()
void igtl::VideoMetaElement::SetSpacing (float si, float sj, float sk)
Sets spacings by spacing values in i, j and k directions.
Definition at line 130 of file igtlVideoMetaMessage.cxx.
References spacing.
SetZoomLevel()
void igtl::VideoMetaElement::SetZoomLevel (igtlInt16 level) inline
Sets the zoom level of the camera (e.g. +4, -4).
Definition at line 54 of file igtlVideoMetaMessage.h.
References m_ZoomLevel.
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_DeviceName
std::string igtl::VideoMetaElement::m_DeviceName protected
device name to query the IMAGE and COLORT
Definition at line 125 of file igtlVideoMetaMessage.h.
Referenced by GetDeviceName(), and SetDeviceName().
m_FocalLength
igtlFloat64 igtl::VideoMetaElement::m_FocalLength protected
Focal length of the camera.
Definition at line 137 of file igtlVideoMetaMessage.h.
Referenced by GetFocalLength(), SetFocalLength(), and VideoMetaElement().
m_Name
std::string igtl::VideoMetaElement::m_Name protected
name / description (<= 64 bytes)
Definition at line 122 of file igtlVideoMetaMessage.h.
Referenced by GetName(), and SetName().
m_PatientID
std::string igtl::VideoMetaElement::m_PatientID protected
patient ID (MRN etc.) (<= 64 bytes)
Definition at line 131 of file igtlVideoMetaMessage.h.
Referenced by GetPatientID(), and SetPatientID().
m_PatientName
std::string igtl::VideoMetaElement::m_PatientName protected
patient name (<= 64 bytes)
Definition at line 128 of file igtlVideoMetaMessage.h.
Referenced by GetPatientName(), and SetPatientName().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_ScalarType
igtlUint8 igtl::VideoMetaElement::m_ScalarType protected
scalar type. see scalar_type in Video message
Definition at line 151 of file igtlVideoMetaMessage.h.
Referenced by GetScalarType(), SetScalarType(), and VideoMetaElement().
m_Size
igtlUint16 igtl::VideoMetaElement::m_Size[3] protected
entire image volume size, if the video is from ultrasound
Definition at line 148 of file igtlVideoMetaMessage.h.
Referenced by GetSize(), SetSize(), and VideoMetaElement().
m_ZoomLevel
igtlInt16 igtl::VideoMetaElement::m_ZoomLevel protected
Zoom level of the camera.
Definition at line 134 of file igtlVideoMetaMessage.h.
Referenced by GetZoomLevel(), SetZoomLevel(), and VideoMetaElement().
matrix
Matrix4x4 igtl::VideoMetaElement::matrix protected
A matrix representing the origin and the orientation of the image, if the camera is attached with tracking device. The matrix is set to identity by default
Definition at line 145 of file igtlVideoMetaMessage.h.
Referenced by GetMatrix(), GetNormals(), GetOrigin(), SetMatrix(), SetNormals(), SetOrigin(), and VideoMetaElement().
spacing
float igtl::VideoMetaElement::spacing[3] protected
A vector containing the spacings of the voxels in i, j and k directions.
Definition at line 140 of file igtlVideoMetaMessage.h.
Referenced by GetSpacing(), SetSpacing(), and VideoMetaElement().
The documentation for this class was generated from the following files:
igtlVideoMetaMessage.h
igtlVideoMetaMessage.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012