igtl::PointElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::PointElement Class Reference
A class to manage point information.
#include <igtlPointMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
const char * GetGroupName ()
Gets the group name.
const char * GetName ()
Gets the name/description of the point.
virtual const char * GetNameOfClass () const
const char * GetOwner ()
Gets the name of the image that owns this label map.
void GetPosition (igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
Gets the position of the point using x, y and z coordinates.
void GetPosition (igtlFloat32 *position)
Gets the position of the point using an array of x, y and z coordinates.
igtlFloat32 GetRadius ()
Gets the radius of the point.
virtual int GetReferenceCount () const
void GetRGBA (igtlUint8 &r, igtlUint8 &g, igtlUint8 &b, igtlUint8 &a)
Gets the color of the point using values of R, G, B and A.
void GetRGBA (igtlUint8 *rgba)
Gets the color of the point using an array of R, G, B and A.
igtlNewMacro (igtl::PointElement)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::PointElement, igtl::Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
int SetGroupName (const char *grpname)
Sets the group name e.g. "Labeled Point", "Landmark", "Fiducial", etc.
int SetName (const char *name)
Sets the name/description of the point. The string 'name' must not exceed 64 characters.
int SetOwner (const char *owner)
Sets the name of the image that owns this label map.
void SetPosition (igtlFloat32 position[3])
Sets the position of the point by an array of x, y and z coordinates.
void SetPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the position of the point by x, y and z coordinates.
void SetRadius (igtlFloat32 radius)
Sets the radius of the point.
void SetReferenceCount (int) override
void SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the point specified by values of R, G, B and A.
void SetRGBA (igtlUint8 rgba[4])
Sets the color of the point specified by an array of R, G, B and A.
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
PointElement ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
~PointElement ()
Protected Attributes
std::string m_GroupName
Can be "Labeled Point", "Landmark", Fiducial", ...
std::string m_Name
name / description (< 64 bytes)
std::string m_Owner
Device name of the ower image.
igtlFloat32 m_Position [3]
Position.
igtlFloat32 m_Radius
Radius of the point. Can be 0.
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_RGBA [4]
Color in R/G/B/A.
Detailed Description
A class to manage point information.
Definition at line 33 of file igtlPointMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
PointElement()
igtl::PointElement::PointElement () protected
Definition at line 32 of file igtlPointMessage.cxx.
References m_GroupName, m_Name, m_Owner, m_Position, m_Radius, m_RGBA, and igtl::Object::Object().
~PointElement()
igtl::PointElement::~PointElement () protected
Definition at line 48 of file igtlPointMessage.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGroupName()
const char * igtl::PointElement::GetGroupName () inline
Gets the group name.
Definition at line 51 of file igtlPointMessage.h.
References m_GroupName.
GetName()
const char * igtl::PointElement::GetName () inline
Gets the name/description of the point.
Definition at line 45 of file igtlPointMessage.h.
References m_Name.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetOwner()
const char * igtl::PointElement::GetOwner () inline
Gets the name of the image that owns this label map.
Definition at line 87 of file igtlPointMessage.h.
References m_Owner.
GetPosition() [1/2]
void igtl::PointElement::GetPosition (igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the position of the point using x, y and z coordinates.
Definition at line 141 of file igtlPointMessage.cxx.
References m_Position.
GetPosition() [2/2]
void igtl::PointElement::GetPosition (igtlFloat32 * position)
Gets the position of the point using an array of x, y and z coordinates.
Definition at line 133 of file igtlPointMessage.cxx.
References m_Position.
GetRadius()
igtlFloat32 igtl::PointElement::GetRadius () inline
Gets the radius of the point.
Definition at line 81 of file igtlPointMessage.h.
References m_Radius.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetRGBA() [1/2]
void igtl::PointElement::GetRGBA (igtlUint8 & r, igtlUint8 & g, igtlUint8 & b, igtlUint8 & a)
Gets the color of the point using values of R, G, B and A.
Definition at line 109 of file igtlPointMessage.cxx.
References m_RGBA.
GetRGBA() [2/2]
void igtl::PointElement::GetRGBA (igtlUint8 * rgba)
Gets the color of the point using an array of R, G, B and A.
Definition at line 99 of file igtlPointMessage.cxx.
References m_RGBA.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::PointElement::igtlNewMacro (igtl::PointElement)
References SetName().
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::PointElement::igtlTypeMacro (igtl::PointElement , igtl::Object)
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetGroupName()
int igtl::PointElement::SetGroupName (const char * grpname)
Sets the group name e.g. "Labeled Point", "Landmark", "Fiducial", etc.
Definition at line 67 of file igtlPointMessage.cxx.
References IGTL_POINT_LEN_GROUP_NAME, and m_GroupName.
SetName()
int igtl::PointElement::SetName (const char * name)
Sets the name/description of the point. The string 'name' must not exceed 64 characters.
Definition at line 53 of file igtlPointMessage.cxx.
References IGTL_POINT_LEN_NAME, and m_Name.
Referenced by igtlNewMacro().
SetOwner()
int igtl::PointElement::SetOwner (const char * owner)
Sets the name of the image that owns this label map.
Definition at line 148 of file igtlPointMessage.cxx.
References IGTL_POINT_LEN_OWNER, and m_Owner.
SetPosition() [1/2]
void igtl::PointElement::SetPosition (igtlFloat32 position[3])
Sets the position of the point by an array of x, y and z coordinates.
Definition at line 117 of file igtlPointMessage.cxx.
References m_Position.
SetPosition() [2/2]
void igtl::PointElement::SetPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the position of the point by x, y and z coordinates.
Definition at line 125 of file igtlPointMessage.cxx.
References m_Position.
SetRadius()
void igtl::PointElement::SetRadius (igtlFloat32 radius) inline
Sets the radius of the point.
Definition at line 78 of file igtlPointMessage.h.
References m_Radius.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetRGBA() [1/2]
void igtl::PointElement::SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the point specified by values of R, G, B and A.
Definition at line 90 of file igtlPointMessage.cxx.
References m_RGBA.
SetRGBA() [2/2]
void igtl::PointElement::SetRGBA (igtlUint8 rgba[4])
Sets the color of the point specified by an array of R, G, B and A.
Definition at line 81 of file igtlPointMessage.cxx.
References m_RGBA.
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_GroupName
std::string igtl::PointElement::m_GroupName protected
Can be "Labeled Point", "Landmark", Fiducial", ...
Definition at line 99 of file igtlPointMessage.h.
Referenced by GetGroupName(), PointElement(), and SetGroupName().
m_Name
std::string igtl::PointElement::m_Name protected
name / description (< 64 bytes)
Definition at line 96 of file igtlPointMessage.h.
Referenced by GetName(), PointElement(), and SetName().
m_Owner
std::string igtl::PointElement::m_Owner protected
Device name of the ower image.
Definition at line 111 of file igtlPointMessage.h.
Referenced by GetOwner(), PointElement(), and SetOwner().
m_Position
igtlFloat32 igtl::PointElement::m_Position[3] protected
Position.
Definition at line 105 of file igtlPointMessage.h.
Referenced by GetPosition(), GetPosition(), PointElement(), SetPosition(), and SetPosition().
m_Radius
igtlFloat32 igtl::PointElement::m_Radius protected
Radius of the point. Can be 0.
Definition at line 108 of file igtlPointMessage.h.
Referenced by GetRadius(), PointElement(), and SetRadius().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_RGBA
igtlUint8 igtl::PointElement::m_RGBA[4] protected
Color in R/G/B/A.
Definition at line 102 of file igtlPointMessage.h.
Referenced by GetRGBA(), GetRGBA(), PointElement(), SetRGBA(), and SetRGBA().
The documentation for this class was generated from the following files:
igtlPointMessage.h
igtlPointMessage.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012