igtl::MessageRTPWrapper Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::MessageRTPWrapper Class Reference
#include <igtlMessageRTPWrapper.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
enum PacketStatus {
PacketReady ,
WaitingForAnotherMSG ,
ProcessFragment ,
MessageReady ,
ToUnpackAnotherMSG ,
WaitingForAnotherPacket
}
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
int GetCurMSGLocation ()
bool GetDebug () const
PacketBuffer GetInCommingPackets ()
Get the incomming UDP packet.
virtual const char * GetNameOfClass () const
int GetNumberODataFragments ()
Gets the number of fragments for the packed (serialized) data. Returns numberOfDataFrag.
int GetNumberODataFragToSent ()
Gets the number of fragments to be sent for the packed (serialized) data. Returns numberOfDataFragToSent.
PacketBuffer GetOutGoingPackets ()
Get the wrapped outgoing UDP packet.
int GetPackedMSGLocation ()
virtual int GetReferenceCount () const
unsigned int GetRTPPayloadLength ()
igtl_uint8 GetRTPPayLoadType ()
int GetRTPWrapperStatus ()
igtlTypeMacro (Object, LightObject)
void Print (std::ostream &os) const
int PushDataIntoPacketBuffer (igtlUint8 *UDPPacket, igtlUint16 PacketLen)
void Register () const override
int SendBufferedDataWithInterval (igtl::UDPServerSocket::Pointer &socket, int interval)
void SetCSRC (igtl_uint32 identifier)
Set the Contributing source identifier. different device has different CSRC.
void SetDebug (bool debugFlag) const
void SetFCFS (bool isFCFS)
void SetMSGHeader (igtl_uint8 *header)
Set the current msg header.
void SetReferenceCount (int) override
void SetRTPPayloadLength (unsigned int payloadLength)
void SetRTPPayloadType (igtl_uint8 payLoadType)
void SetSeqNum (igtl_uint16 num)
Set the sequencen number at the rtp header.
void SetSSRC (igtl_uint32 identifier)
Set the synchronization source identifier, different session has different SSRC.
void UnRegister () const override
igtl::MessageBase::Pointer UnWrapMessage (igtl_uint8 *messageContent, int totMsgLen)
int UnWrapPacketWithTypeAndName (const char *deviceType, const char *deviceName)
int WrapMessageAndPushToBuffer (igtl_uint8 *messagePackPointer, int msgtotalLen)
int WrapMessageAndSend (igtl::UDPServerSocket::Pointer &socket, igtl_uint8 *messagePackPointer, int msgtotalLen)
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Data Fields
igtl_uint16 fragmentNumber
std::vector< igtl_uint16 > fragmentNumberList
igtl::SimpleMutexLock * glock
igtl_uint32 messageID
std::vector< igtl_uint64 > PacketBeforeSendTimeStampList
int packetIntervalTime
std::vector< igtl_uint64 > PacketSendTimeStampList
std::vector< igtl_uint64 > PacketTotalLengthList
std::map< igtl_uint32, igtl::UnWrappedMessage * > unWrappedMessages
Protected Member Functions
igtl_uint8 * GetPackPointer ()
Gets a pointer to the scalar data (for fragmented pack support).
MessageRTPWrapper ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
int WrapMessage (igtl_uint8 *messageContent, int bodyMsgLen)
~MessageRTPWrapper ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 155 of file igtlMessageRTPWrapper.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
PacketStatus
enum igtl::MessageRTPWrapper::PacketStatus
Enumerator
PacketReady
WaitingForAnotherMSG
ProcessFragment
MessageReady
ToUnpackAnotherMSG
WaitingForAnotherPacket
Definition at line 162 of file igtlMessageRTPWrapper.h.
Constructor & Destructor Documentation
MessageRTPWrapper()
igtl::MessageRTPWrapper::MessageRTPWrapper () protected
Definition at line 21 of file igtlMessageRTPWrapper.cxx.
References fragmentNumber, fragmentNumberList, glock, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, igtl::LightObject::New(), igtl::SimpleMutexLock::New(), igtl::Object::Object(), PacketBeforeSendTimeStampList, packetIntervalTime, PacketReady, PacketSendTimeStampList, PacketTotalLengthList, and RTP_PAYLOAD_LENGTH.
~MessageRTPWrapper()
igtl::MessageRTPWrapper::~MessageRTPWrapper () protected
Definition at line 50 of file igtlMessageRTPWrapper.cxx.
References glock, and unWrappedMessages.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetCurMSGLocation()
int igtl::MessageRTPWrapper::GetCurMSGLocation () inline
Definition at line 231 of file igtlMessageRTPWrapper.h.
Referenced by WrapMessageAndPushToBuffer(), and WrapMessageAndSend().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetInCommingPackets()
PacketBuffer igtl::MessageRTPWrapper::GetInCommingPackets () inline
Get the incomming UDP packet.
Definition at line 229 of file igtlMessageRTPWrapper.h.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetNumberODataFragments()
int igtl::MessageRTPWrapper::GetNumberODataFragments () inline
Gets the number of fragments for the packed (serialized) data. Returns numberOfDataFrag.
Definition at line 190 of file igtlMessageRTPWrapper.h.
GetNumberODataFragToSent()
int igtl::MessageRTPWrapper::GetNumberODataFragToSent () inline
Gets the number of fragments to be sent for the packed (serialized) data. Returns numberOfDataFragToSent.
Definition at line 193 of file igtlMessageRTPWrapper.h.
GetOutGoingPackets()
PacketBuffer igtl::MessageRTPWrapper::GetOutGoingPackets () inline
Get the wrapped outgoing UDP packet.
Definition at line 226 of file igtlMessageRTPWrapper.h.
GetPackedMSGLocation()
int igtl::MessageRTPWrapper::GetPackedMSGLocation () inline
Definition at line 233 of file igtlMessageRTPWrapper.h.
Referenced by WrapMessageAndPushToBuffer(), and WrapMessageAndSend().
GetPackPointer()
igtl_uint8 * igtl::MessageRTPWrapper::GetPackPointer () inline protected
Gets a pointer to the scalar data (for fragmented pack support).
Definition at line 251 of file igtlMessageRTPWrapper.h.
Referenced by WrapMessageAndSend().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetRTPPayloadLength()
unsigned int igtl::MessageRTPWrapper::GetRTPPayloadLength () inline
Definition at line 239 of file igtlMessageRTPWrapper.h.
GetRTPPayLoadType()
igtl_uint8 igtl::MessageRTPWrapper::GetRTPPayLoadType () inline
Definition at line 199 of file igtlMessageRTPWrapper.h.
GetRTPWrapperStatus()
int igtl::MessageRTPWrapper::GetRTPWrapperStatus () inline
Definition at line 235 of file igtlMessageRTPWrapper.h.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlTypeMacro()
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
PushDataIntoPacketBuffer()
int igtl::MessageRTPWrapper::PushDataIntoPacketBuffer (igtlUint8 * UDPPacket, igtlUint16 PacketLen)
Definition at line 120 of file igtlMessageRTPWrapper.cxx.
References glock, and PacketMaximumBufferNum.
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SendBufferedDataWithInterval()
int igtl::MessageRTPWrapper::SendBufferedDataWithInterval (igtl::UDPServerSocket::Pointer & socket, int interval)
Definition at line 146 of file igtlMessageRTPWrapper.cxx.
References glock.
SetCSRC()
void igtl::MessageRTPWrapper::SetCSRC (igtl_uint32 identifier)
Set the Contributing source identifier. different device has different CSRC.
Definition at line 102 of file igtlMessageRTPWrapper.cxx.
References BYTE_SWAP_INT32, and igtl_is_little_endian().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetFCFS()
void igtl::MessageRTPWrapper::SetFCFS (bool isFCFS) inline
Definition at line 195 of file igtlMessageRTPWrapper.h.
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetMSGHeader()
void igtl::MessageRTPWrapper::SetMSGHeader (igtl_uint8 * header)
Set the current msg header.
Left shift the lower byte of the message ID by two bytes. and fill the last two byte with NoFragmentIndicator only valid if the messageID is less than 2^16.
Definition at line 82 of file igtlMessageRTPWrapper.cxx.
References FragmentIndexBytes, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, messageID, and NoFragmentIndicator.
Referenced by WrapMessageAndPushToBuffer(), and WrapMessageAndSend().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetRTPPayloadLength()
void igtl::MessageRTPWrapper::SetRTPPayloadLength (unsigned int payloadLength) inline
Definition at line 237 of file igtlMessageRTPWrapper.h.
SetRTPPayloadType()
void igtl::MessageRTPWrapper::SetRTPPayloadType (igtl_uint8 payLoadType) inline
Definition at line 197 of file igtlMessageRTPWrapper.h.
SetSeqNum()
void igtl::MessageRTPWrapper::SetSeqNum (igtl_uint16 num)
Set the sequencen number at the rtp header.
Definition at line 111 of file igtlMessageRTPWrapper.cxx.
References BYTE_SWAP_INT16, and igtl_is_little_endian().
SetSSRC()
void igtl::MessageRTPWrapper::SetSSRC (igtl_uint32 identifier)
Set the synchronization source identifier, different session has different SSRC.
Definition at line 93 of file igtlMessageRTPWrapper.cxx.
References BYTE_SWAP_INT32, and igtl_is_little_endian().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
UnWrapMessage()
igtl::MessageBase::Pointer igtl::MessageRTPWrapper::UnWrapMessage (igtl_uint8 * messageContent, int totMsgLen)
Definition at line 601 of file igtlMessageRTPWrapper.cxx.
UnWrapPacketWithTypeAndName()
int igtl::MessageRTPWrapper::UnWrapPacketWithTypeAndName (const char * deviceType, const char * deviceName)
Definition at line 234 of file igtlMessageRTPWrapper.cxx.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, FragmentBeginIndicator, FragmentEndIndicator, FragmentIndexBytes, glock, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, igtl_is_little_endian(), igtl::UnWrappedMessage::messageDataLength, messageID, igtl::UnWrappedMessage::messagePackPointer, MessageReady, NoFragmentIndicator, ReorderBufferMaximumSize, RTP_HEADER_LENGTH, unWrappedMessages, and WaitingForAnotherPacket.
WrapMessage()
int igtl::MessageRTPWrapper::WrapMessage (igtl_uint8 * messageContent, int bodyMsgLen) protected
Definition at line 468 of file igtlMessageRTPWrapper.cxx.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, FragmentBeginIndicator, FragmentEndIndicator, FragmentIndexBytes, fragmentNumber, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, igtl_is_little_endian(), NoFragmentIndicator, PacketReady, ProcessFragment, and RTP_HEADER_LENGTH.
Referenced by WrapMessageAndPushToBuffer(), and WrapMessageAndSend().
WrapMessageAndPushToBuffer()
int igtl::MessageRTPWrapper::WrapMessageAndPushToBuffer (igtl_uint8 * messagePackPointer, int msgtotalLen)
Definition at line 192 of file igtlMessageRTPWrapper.cxx.
References GetCurMSGLocation(), GetPackedMSGLocation(), glock, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, PacketMaximumBufferNum, PacketReady, PacketTotalLengthList, ProcessFragment, SetMSGHeader(), and WrapMessage().
WrapMessageAndSend()
int igtl::MessageRTPWrapper::WrapMessageAndSend (igtl::UDPServerSocket::Pointer & socket, igtl_uint8 * messagePackPointer, int msgtotalLen)
Definition at line 409 of file igtlMessageRTPWrapper.cxx.
References fragmentNumber, fragmentNumberList, GetCurMSGLocation(), GetPackedMSGLocation(), GetPackPointer(), glock, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, PacketBeforeSendTimeStampList, packetIntervalTime, PacketReady, PacketSendTimeStampList, PacketTotalLengthList, ProcessFragment, SetMSGHeader(), and WrapMessage().
Field Documentation
fragmentNumber
igtl_uint16 igtl::MessageRTPWrapper::fragmentNumber
Definition at line 173 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), WrapMessage(), and WrapMessageAndSend().
fragmentNumberList
std::vector<igtl_uint16> igtl::MessageRTPWrapper::fragmentNumberList
Definition at line 187 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), and WrapMessageAndSend().
glock
igtl::SimpleMutexLock* igtl::MessageRTPWrapper::glock
Definition at line 243 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), PushDataIntoPacketBuffer(), SendBufferedDataWithInterval(), UnWrapPacketWithTypeAndName(), WrapMessageAndPushToBuffer(), WrapMessageAndSend(), and ~MessageRTPWrapper().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
messageID
igtl_uint32 igtl::MessageRTPWrapper::messageID
Definition at line 172 of file igtlMessageRTPWrapper.h.
Referenced by SetMSGHeader(), and UnWrapPacketWithTypeAndName().
PacketBeforeSendTimeStampList
std::vector<igtl_uint64> igtl::MessageRTPWrapper::PacketBeforeSendTimeStampList
Definition at line 185 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), and WrapMessageAndSend().
packetIntervalTime
int igtl::MessageRTPWrapper::packetIntervalTime
The message get fragmented and sent in different packets. The packets sending should have some interval in the function WrapMessageAndSend(), otherwize the network demanding would be too high to cause packet loss This variable need to be set according to the network bandwidth and the RTPPayload size
Definition at line 179 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), and WrapMessageAndSend().
PacketSendTimeStampList
std::vector<igtl_uint64> igtl::MessageRTPWrapper::PacketSendTimeStampList
Definition at line 181 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), and WrapMessageAndSend().
PacketTotalLengthList
std::vector<igtl_uint64> igtl::MessageRTPWrapper::PacketTotalLengthList
Definition at line 183 of file igtlMessageRTPWrapper.h.
Referenced by MessageRTPWrapper(), WrapMessageAndPushToBuffer(), and WrapMessageAndSend().
unWrappedMessages
std::map<igtl_uint32, igtl::UnWrappedMessage*> igtl::MessageRTPWrapper::unWrappedMessages
Definition at line 241 of file igtlMessageRTPWrapper.h.
Referenced by UnWrapPacketWithTypeAndName(), and ~MessageRTPWrapper().
The documentation for this class was generated from the following files:
igtlMessageRTPWrapper.h
igtlMessageRTPWrapper.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012