webSocketClient Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
webSocketClient Class Reference
#include <igtlWebClientSocket.h>
Public Types
typedef websocketpp::client< websocketpp::config::asio_client > client
typedef websocketpp::lib::lock_guard< websocketpp::lib::mutex > scoped_lock
Public Member Functions
int ConnectToServer (const char *hostName, int port)
void on_close (websocketpp::connection_hdl)
void on_fail (websocketpp::connection_hdl)
void on_message (websocketpp::connection_hdl hdl, message_ptr msg)
void on_open (websocketpp::connection_hdl)
int Receive (void *data, int &length)
int Send (const void *data, int length)
webSocketClient ()
Detailed Description
Definition at line 36 of file igtlWebClientSocket.h.
Member Typedef Documentation
client
typedef websocketpp::client<websocketpp::config::asio_client> webSocketClient::client
Definition at line 38 of file igtlWebClientSocket.h.
scoped_lock
typedef websocketpp::lib::lock_guard<websocketpp::lib::mutex> webSocketClient::scoped_lock
Definition at line 39 of file igtlWebClientSocket.h.
Constructor & Destructor Documentation
webSocketClient()
webSocketClient::webSocketClient ()
Definition at line 11 of file igtlWebClientSocket.cxx.
References on_close(), on_fail(), on_message(), and on_open().
Member Function Documentation
ConnectToServer()
int webSocketClient::ConnectToServer (const char * hostName, int port)
Definition at line 31 of file igtlWebClientSocket.cxx.
on_close()
void webSocketClient::on_close (websocketpp::connection_hdl)
Definition at line 70 of file igtlWebClientSocket.cxx.
Referenced by webSocketClient().
on_fail()
void webSocketClient::on_fail (websocketpp::connection_hdl)
Definition at line 79 of file igtlWebClientSocket.cxx.
Referenced by webSocketClient().
on_message()
void webSocketClient::on_message (websocketpp::connection_hdl hdl, message_ptr msg)
Definition at line 87 of file igtlWebClientSocket.cxx.
Referenced by webSocketClient().
on_open()
void webSocketClient::on_open (websocketpp::connection_hdl)
Definition at line 61 of file igtlWebClientSocket.cxx.
Referenced by webSocketClient().
Receive()
int webSocketClient::Receive (void * data, int & length)
Definition at line 97 of file igtlWebClientSocket.cxx.
Send()
int webSocketClient::Send (const void * data, int length)
Definition at line 125 of file igtlWebClientSocket.cxx.
The documentation for this class was generated from the following files:
igtlWebClientSocket.h
igtlWebClientSocket.cxx
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012