igtl::PolyDataPointArray Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::PolyDataPointArray Class Reference
#include <igtlPolyDataMessage.h>
Public Types
typedef SmartPointer< const Self > ConstPointer
typedef std::vector< igtlFloat32 > Point
A vector to represent coordinates of a point.
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
int AddPoint (igtlFloat32 *point)
int AddPoint (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Adds a point 'point' specified by 'x', 'y' and 'z'.
void Clear ()
Clears the all points in the list.
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
int GetNumberOfPoints ()
Gets the number of points in the list.
int GetPoint (unsigned int id, igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
Gets the coordinates of the point specified by 'id'.
int GetPoint (unsigned int id, igtlFloat32 *point)
Gets the coordinates of the point specified by 'id'.
virtual int GetReferenceCount () const
igtlNewMacro (igtl::PolyDataPointArray)
igtlRangeBasedForHeaderMemberMacro (std::vector< Point >)
Implement support for C++11 ranged for loops.
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::PolyDataPointArray, igtl::Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
void SetNumberOfPoints (int n)
Sets the number of points. This function will change the size of the list.
int SetPoint (unsigned int id, igtlFloat32 *point)
int SetPoint (unsigned int id, igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Substitutes the point specified by 'id' with a point specified by 'x', 'y' and 'z'.
void SetReferenceCount (int) override
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
PolyDataPointArray ()
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
~PolyDataPointArray ()
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
Definition at line 104 of file igtlPolyDataMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Point
typedef std::vector<igtlFloat32> igtl::PolyDataPointArray::Point
A vector to represent coordinates of a point.
Definition at line 109 of file igtlPolyDataMessage.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Constructor & Destructor Documentation
PolyDataPointArray()
igtl::PolyDataPointArray::PolyDataPointArray () protected
Definition at line 33 of file igtlPolyDataMessage.cxx.
References Clear(), and igtl::Object::Object().
Referenced by igtlNewMacro().
~PolyDataPointArray()
igtl::PolyDataPointArray::~PolyDataPointArray () protected
Definition at line 39 of file igtlPolyDataMessage.cxx.
Member Function Documentation
AddPoint() [1/2]
int igtl::PolyDataPointArray::AddPoint (igtlFloat32 * point)
Adds a point specified by 'point' to the list. The 'point' contains the x, y, and z coordinates of the point.
Definition at line 90 of file igtlPolyDataMessage.cxx.
Referenced by igtlNewMacro().
AddPoint() [2/2]
int igtl::PolyDataPointArray::AddPoint (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Adds a point 'point' specified by 'x', 'y' and 'z'.
Definition at line 102 of file igtlPolyDataMessage.cxx.
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
Clear()
void igtl::PolyDataPointArray::Clear ()
Clears the all points in the list.
Definition at line 43 of file igtlPolyDataMessage.cxx.
Referenced by igtlNewMacro(), and PolyDataPointArray().
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetNumberOfPoints()
int igtl::PolyDataPointArray::GetNumberOfPoints ()
Gets the number of points in the list.
Definition at line 59 of file igtlPolyDataMessage.cxx.
Referenced by igtlNewMacro().
GetPoint() [1/2]
int igtl::PolyDataPointArray::GetPoint (unsigned int id, igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the coordinates of the point specified by 'id'.
Definition at line 114 of file igtlPolyDataMessage.cxx.
Referenced by igtlNewMacro().
GetPoint() [2/2]
int igtl::PolyDataPointArray::GetPoint (unsigned int id, igtlFloat32 * point)
Gets the coordinates of the point specified by 'id'.
Definition at line 127 of file igtlPolyDataMessage.cxx.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::PolyDataPointArray::igtlNewMacro (igtl::PolyDataPointArray)
References AddPoint(), Clear(), GetNumberOfPoints(), GetPoint(), PolyDataPointArray(), SetNumberOfPoints(), and SetPoint().
igtlRangeBasedForHeaderMemberMacro()
igtl::PolyDataPointArray::igtlRangeBasedForHeaderMemberMacro (std::vector< Point >)
Implement support for C++11 ranged for loops.
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::PolyDataPointArray::igtlTypeMacro (igtl::PolyDataPointArray , igtl::Object)
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetNumberOfPoints()
void igtl::PolyDataPointArray::SetNumberOfPoints (int n)
Sets the number of points. This function will change the size of the list.
Definition at line 48 of file igtlPolyDataMessage.cxx.
Referenced by igtlNewMacro().
SetPoint() [1/2]
int igtl::PolyDataPointArray::SetPoint (unsigned int id, igtlFloat32 * point)
Substitutes the point specified by 'id' with a point specified by 'point'. The 'point' contains the x, y, and z coordinates of the point.
Definition at line 64 of file igtlPolyDataMessage.cxx.
Referenced by igtlNewMacro().
SetPoint() [2/2]
int igtl::PolyDataPointArray::SetPoint (unsigned int id, igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Substitutes the point specified by 'id' with a point specified by 'x', 'y' and 'z'.
Definition at line 77 of file igtlPolyDataMessage.cxx.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlPolyDataMessage.h
igtlPolyDataMessage.cxx
Generated at Tue Sep 9 2025 15:29:16 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012