igtl::TrajectoryElement Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::TrajectoryElement Class Reference
TrajectoryElement class is used to manage a trajectory in TrajectoryMessage class.
#include <igtlTrajectoryMessage.h>
Public Types
enum {
TYPE_ENTRY_ONLY = 1 ,
TYPE_TARGET_ONLY = 2 ,
TYPE_ENTRY_TARGET = 3
}
Types of trajectory.
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
void GetEntryPosition (igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
Gets the entry position.
void GetEntryPosition (igtlFloat32 *position)
Sets the entry position using an array of x, y, and z coordinates.
const char * GetGroupName ()
Gets the group name.
const char * GetName ()
Gets the name of the trajectory.
virtual const char * GetNameOfClass () const
const char * GetOwner ()
Gets the owner of the trajectory.
igtlFloat32 GetRadius ()
Gets the radius.
virtual int GetReferenceCount () const
void GetRGBA (igtlUint8 &r, igtlUint8 &g, igtlUint8 &b, igtlUint8 &a)
Gets the color of the trajectory.
void GetRGBA (igtlUint8 *rgba)
Gets the color of the trajectory. An array of r, g, b and alpha is stored in 'rgba'.
void GetTargetPosition (igtlFloat32 &x, igtlFloat32 &y, igtlFloat32 &z)
Gets the target position.
void GetTargetPosition (igtlFloat32 *position)
Gets the target position. Stores an array of x, y, and z coordinates in 'position'.
igtlUint8 GetType ()
Gets the trajectory type. The returned value is either TYPE_ENTRY_ONLY, TYPE_TARGET_ONLY, or TYPE_ENTRY_TARGET.
igtlNewMacro (igtl::TrajectoryElement)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (igtl::TrajectoryElement, igtl::Object)
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
void SetEntryPosition (igtlFloat32 position[3])
Sets the entry position using an array.
void SetEntryPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the entry position.
int SetGroupName (const char *grpname)
Sets the group name e.g. "Trajectory".
int SetName (const char *name)
Sets the name of the trajectory.
int SetOwner (const char *owner)
Sets the owner of the trajectory. 'owner' must be a name of image.
void SetRadius (igtlFloat32 radius)
Sets the radius.
void SetReferenceCount (int) override
void SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the trajectory by r, g, b and alpha.
void SetRGBA (igtlUint8 rgba[4])
Sets the color of the trajectory using an array of r, g, b and alpha.
void SetTargetPosition (igtlFloat32 position[3])
Sets the target position using an array of x, y, and z coordinates.
void SetTargetPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the target position.
int SetType (igtlUint8 type)
Sets the trajectory type. 'type' must be either TYPE_ENTRY_ONLY, TYPE_TARGET_ONLY, or TYPE_ENTRY_TARGET.
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
TrajectoryElement ()
~TrajectoryElement ()
Protected Attributes
igtlFloat32 m_EntryPosition [3]
Coordinate of the entry point.
std::string m_GroupName
Can be "Labeled Trajectory", "Landmark", Fiducial", ...
std::string m_Name
name / description (< 64 bytes)
std::string m_Owner
Device name of the ower image.
igtlFloat32 m_Radius
Radius of the trajectory. Can be 0.
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
igtlUint8 m_RGBA [4]
Color in R/G/B/A.
igtlFloat32 m_TargetPosition [3]
Coordinate of the target point.
igtlUint8 m_Type
Trajectory type (see TYPE_* constants)
Detailed Description
TrajectoryElement class is used to manage a trajectory in TrajectoryMessage class.
Definition at line 32 of file igtlTrajectoryMessage.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Types of trajectory.
Enumerator
TYPE_ENTRY_ONLY
TYPE_TARGET_ONLY
TYPE_ENTRY_TARGET
Definition at line 39 of file igtlTrajectoryMessage.h.
Constructor & Destructor Documentation
TrajectoryElement()
igtl::TrajectoryElement::TrajectoryElement () protected
Definition at line 32 of file igtlTrajectoryMessage.cxx.
References m_EntryPosition, m_GroupName, m_Name, m_Owner, m_Radius, m_RGBA, m_TargetPosition, m_Type, igtl::Object::Object(), and TYPE_TARGET_ONLY.
~TrajectoryElement()
igtl::TrajectoryElement::~TrajectoryElement () protected
Definition at line 52 of file igtlTrajectoryMessage.cxx.
Member Function Documentation
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetEntryPosition() [1/2]
void igtl::TrajectoryElement::GetEntryPosition (igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the entry position.
Definition at line 161 of file igtlTrajectoryMessage.cxx.
References m_EntryPosition.
GetEntryPosition() [2/2]
void igtl::TrajectoryElement::GetEntryPosition (igtlFloat32 * position)
Sets the entry position using an array of x, y, and z coordinates.
Definition at line 153 of file igtlTrajectoryMessage.cxx.
References m_EntryPosition.
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGroupName()
const char * igtl::TrajectoryElement::GetGroupName () inline
Gets the group name.
Definition at line 57 of file igtlTrajectoryMessage.h.
References m_GroupName.
GetName()
const char * igtl::TrajectoryElement::GetName () inline
Gets the name of the trajectory.
Definition at line 51 of file igtlTrajectoryMessage.h.
References m_Name.
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetOwner()
const char * igtl::TrajectoryElement::GetOwner () inline
Gets the owner of the trajectory.
Definition at line 110 of file igtlTrajectoryMessage.h.
References m_Owner.
GetRadius()
igtlFloat32 igtl::TrajectoryElement::GetRadius () inline
Gets the radius.
Definition at line 104 of file igtlTrajectoryMessage.h.
References m_Radius.
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GetRGBA() [1/2]
void igtl::TrajectoryElement::GetRGBA (igtlUint8 & r, igtlUint8 & g, igtlUint8 & b, igtlUint8 & a)
Gets the color of the trajectory.
Definition at line 129 of file igtlTrajectoryMessage.cxx.
References m_RGBA.
GetRGBA() [2/2]
void igtl::TrajectoryElement::GetRGBA (igtlUint8 * rgba)
Gets the color of the trajectory. An array of r, g, b and alpha is stored in 'rgba'.
Definition at line 119 of file igtlTrajectoryMessage.cxx.
References m_RGBA.
GetTargetPosition() [1/2]
void igtl::TrajectoryElement::GetTargetPosition (igtlFloat32 & x, igtlFloat32 & y, igtlFloat32 & z)
Gets the target position.
Definition at line 193 of file igtlTrajectoryMessage.cxx.
References m_TargetPosition.
GetTargetPosition() [2/2]
void igtl::TrajectoryElement::GetTargetPosition (igtlFloat32 * position)
Gets the target position. Stores an array of x, y, and z coordinates in 'position'.
Definition at line 185 of file igtlTrajectoryMessage.cxx.
References m_TargetPosition.
GetType()
igtlUint8 igtl::TrajectoryElement::GetType () inline
Gets the trajectory type. The returned value is either TYPE_ENTRY_ONLY, TYPE_TARGET_ONLY, or TYPE_ENTRY_TARGET.
Definition at line 62 of file igtlTrajectoryMessage.h.
References m_Type.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::TrajectoryElement::igtlNewMacro (igtl::TrajectoryElement)
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::TrajectoryElement::igtlTypeMacro (igtl::TrajectoryElement , igtl::Object)
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetEntryPosition() [1/2]
void igtl::TrajectoryElement::SetEntryPosition (igtlFloat32 position[3])
Sets the entry position using an array.
Definition at line 137 of file igtlTrajectoryMessage.cxx.
References m_EntryPosition.
SetEntryPosition() [2/2]
void igtl::TrajectoryElement::SetEntryPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the entry position.
Definition at line 145 of file igtlTrajectoryMessage.cxx.
References m_EntryPosition.
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetGroupName()
int igtl::TrajectoryElement::SetGroupName (const char * grpname)
Sets the group name e.g. "Trajectory".
Definition at line 71 of file igtlTrajectoryMessage.cxx.
References IGTL_TRAJECTORY_LEN_GROUP_NAME, and m_GroupName.
SetName()
int igtl::TrajectoryElement::SetName (const char * name)
Sets the name of the trajectory.
Definition at line 57 of file igtlTrajectoryMessage.cxx.
References IGTL_TRAJECTORY_LEN_NAME, and m_Name.
SetOwner()
int igtl::TrajectoryElement::SetOwner (const char * owner)
Sets the owner of the trajectory. 'owner' must be a name of image.
Definition at line 201 of file igtlTrajectoryMessage.cxx.
References IGTL_TRAJECTORY_LEN_OWNER, and m_Owner.
SetRadius()
void igtl::TrajectoryElement::SetRadius (igtlFloat32 radius) inline
Sets the radius.
Definition at line 101 of file igtlTrajectoryMessage.h.
References m_Radius.
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
SetRGBA() [1/2]
void igtl::TrajectoryElement::SetRGBA (igtlUint8 r, igtlUint8 g, igtlUint8 b, igtlUint8 a)
Sets the color of the trajectory by r, g, b and alpha.
Definition at line 110 of file igtlTrajectoryMessage.cxx.
References m_RGBA.
SetRGBA() [2/2]
void igtl::TrajectoryElement::SetRGBA (igtlUint8 rgba[4])
Sets the color of the trajectory using an array of r, g, b and alpha.
Definition at line 101 of file igtlTrajectoryMessage.cxx.
References m_RGBA.
SetTargetPosition() [1/2]
void igtl::TrajectoryElement::SetTargetPosition (igtlFloat32 position[3])
Sets the target position using an array of x, y, and z coordinates.
Definition at line 169 of file igtlTrajectoryMessage.cxx.
References m_TargetPosition.
SetTargetPosition() [2/2]
void igtl::TrajectoryElement::SetTargetPosition (igtlFloat32 x, igtlFloat32 y, igtlFloat32 z)
Sets the target position.
Definition at line 177 of file igtlTrajectoryMessage.cxx.
References m_TargetPosition.
SetType()
int igtl::TrajectoryElement::SetType (igtlUint8 type)
Sets the trajectory type. 'type' must be either TYPE_ENTRY_ONLY, TYPE_TARGET_ONLY, or TYPE_ENTRY_TARGET.
Definition at line 85 of file igtlTrajectoryMessage.cxx.
References m_Type, TYPE_ENTRY_ONLY, TYPE_ENTRY_TARGET, and TYPE_TARGET_ONLY.
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_EntryPosition
igtlFloat32 igtl::TrajectoryElement::m_EntryPosition[3] protected
Coordinate of the entry point.
Definition at line 131 of file igtlTrajectoryMessage.h.
Referenced by GetEntryPosition(), GetEntryPosition(), SetEntryPosition(), SetEntryPosition(), and TrajectoryElement().
m_GroupName
std::string igtl::TrajectoryElement::m_GroupName protected
Can be "Labeled Trajectory", "Landmark", Fiducial", ...
Definition at line 122 of file igtlTrajectoryMessage.h.
Referenced by GetGroupName(), SetGroupName(), and TrajectoryElement().
m_Name
std::string igtl::TrajectoryElement::m_Name protected
name / description (< 64 bytes)
Definition at line 119 of file igtlTrajectoryMessage.h.
Referenced by GetName(), SetName(), and TrajectoryElement().
m_Owner
std::string igtl::TrajectoryElement::m_Owner protected
Device name of the ower image.
Definition at line 140 of file igtlTrajectoryMessage.h.
Referenced by GetOwner(), SetOwner(), and TrajectoryElement().
m_Radius
igtlFloat32 igtl::TrajectoryElement::m_Radius protected
Radius of the trajectory. Can be 0.
Definition at line 137 of file igtlTrajectoryMessage.h.
Referenced by GetRadius(), SetRadius(), and TrajectoryElement().
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
m_RGBA
igtlUint8 igtl::TrajectoryElement::m_RGBA[4] protected
Color in R/G/B/A.
Definition at line 128 of file igtlTrajectoryMessage.h.
Referenced by GetRGBA(), GetRGBA(), SetRGBA(), SetRGBA(), and TrajectoryElement().
m_TargetPosition
igtlFloat32 igtl::TrajectoryElement::m_TargetPosition[3] protected
Coordinate of the target point.
Definition at line 134 of file igtlTrajectoryMessage.h.
Referenced by GetTargetPosition(), GetTargetPosition(), SetTargetPosition(), SetTargetPosition(), and TrajectoryElement().
m_Type
igtlUint8 igtl::TrajectoryElement::m_Type protected
Trajectory type (see TYPE_* constants)
Definition at line 125 of file igtlTrajectoryMessage.h.
Referenced by GetType(), SetType(), and TrajectoryElement().
The documentation for this class was generated from the following files:
igtlTrajectoryMessage.h
igtlTrajectoryMessage.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012