igtl::VideoStreamIGTLinkServer::encodedFrame Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::VideoStreamIGTLinkServer::encodedFrame Class Reference
#include <igtlVideoStreamIGTLinkServer.h>
Public Member Functions
encodedFrame ()
encodedFrame (encodedFrame const &anotherFrame)
~encodedFrame ()
Data Fields
igtl_uint32 messageDataLength
unsigned char messagePackPointer [RTP_PAYLOAD_LENGTH *(16384-2)]
Detailed Description
Definition at line 197 of file igtlVideoStreamIGTLinkServer.h.
Constructor & Destructor Documentation
encodedFrame() [1/2]
igtl::VideoStreamIGTLinkServer::encodedFrame::encodedFrame () inline
Definition at line 200 of file igtlVideoStreamIGTLinkServer.h.
References messageDataLength.
Referenced by encodedFrame().
encodedFrame() [2/2]
igtl::VideoStreamIGTLinkServer::encodedFrame::encodedFrame (encodedFrame const & anotherFrame) inline
Definition at line 201 of file igtlVideoStreamIGTLinkServer.h.
References encodedFrame().
~encodedFrame()
igtl::VideoStreamIGTLinkServer::encodedFrame::~encodedFrame () inline
Definition at line 202 of file igtlVideoStreamIGTLinkServer.h.
Field Documentation
messageDataLength
igtl_uint32 igtl::VideoStreamIGTLinkServer::encodedFrame::messageDataLength
Definition at line 204 of file igtlVideoStreamIGTLinkServer.h.
Referenced by encodedFrame(), igtl::VideoStreamIGTLinkServer::EncodeFile(), igtl::VideoStreamIGTLinkServer::SendOriginalData(), and igtl::ThreadFunctionSendPacket().
messagePackPointer
unsigned char igtl::VideoStreamIGTLinkServer::encodedFrame::messagePackPointer[RTP_PAYLOAD_LENGTH *(16384-2)]
Definition at line 203 of file igtlVideoStreamIGTLinkServer.h.
Referenced by igtl::VideoStreamIGTLinkServer::EncodeFile(), igtl::VideoStreamIGTLinkServer::SendOriginalData(), and igtl::ThreadFunctionSendPacket().
The documentation for this class was generated from the following file:
igtlVideoStreamIGTLinkServer.h
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012