igtl::Unit Class Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::Unit Class Reference
#include <igtlUnit.h>
Public Types
enum {
SI_BASE_NONE = 0x00 ,
SI_BASE_METER = 0x01 ,
SI_BASE_GRAM = 0x02 ,
SI_BASE_SECOND = 0x03 ,
SI_BASE_AMPERE = 0x04 ,
SI_BASE_KELVIN = 0x05 ,
SI_BASE_MOLE = 0x06 ,
SI_BASE_CANDELA = 0x07 ,
SI_DERIVED_RADIAN = 0x08 ,
SI_DERIVED_STERADIAN = 0x09 ,
SI_DERIVED_HERTZ = 0x0A ,
SI_DERIVED_NEWTON = 0x0B ,
SI_DERIVED_PASCAL = 0x0C ,
SI_DERIVED_JOULE = 0x0D ,
SI_DERIVED_WATT = 0x0E ,
SI_DERIVED_COULOMB = 0x0F ,
SI_DERIVED_VOLT = 0x10 ,
SI_DERIVED_FARAD = 0x11 ,
SI_DERIVED_OHM = 0x12 ,
SI_DERIVED_SIEMENS = 0x13 ,
SI_DERIVED_WEBER = 0x14 ,
SI_DERIVED_TESLA = 0x15 ,
SI_DERIVED_HENRY = 0x16 ,
SI_DERIVED_LUMEN = 0x17 ,
SI_DERIVED_LUX = 0x18 ,
SI_DERIVED_BECQUEREL = 0x19 ,
SI_DERIVED_GRAY = 0x1A ,
SI_DERIVED_SIEVERT = 0x1B ,
SI_NUM_UNIT_TYPES = 0x1C
}
SI Units.
enum {
SI_PREFIX_NONE = 0x0 ,
SI_PREFIX_DEKA = 0x1 ,
SI_PREFIX_HECTO = 0x2 ,
SI_PREFIX_KILO = 0x3 ,
SI_PREFIX_MEGA = 0x4 ,
SI_PREFIX_GIGA = 0x5 ,
SI_PREFIX_TERA = 0x6 ,
SI_PREFIX_PETA = 0x7 ,
SI_PREFIX_DECI = 0x9 ,
SI_PREFIX_CENTI = 0xA ,
SI_PREFIX_MILLI = 0xB ,
SI_PREFIX_MICRO = 0xC ,
SI_PREFIX_NANO = 0xD ,
SI_PREFIX_PICO = 0xE ,
SI_PREFIX_FEMTO = 0xF
}
SI Prefix.
typedef SmartPointer< const Self > ConstPointer
typedef SmartPointer< Self > Pointer
typedef LightObject Self
Public Member Functions
int Append (int unit, int exp)
Appends a unit with exponential.
LightObject::Pointer CreateAnother () const override
virtual void DebugOff () const
virtual void DebugOn () const
virtual void Delete ()
bool GetDebug () const
virtual const char * GetNameOfClass () const
virtual int GetReferenceCount () const
igtlNewMacro (Self)
igtlTypeMacro (Object, LightObject)
igtlTypeMacro (Unit, Object)
void Init ()
Initializes the class.
igtlUnit Pack ()
Packs (or serializes) the unit into a 64-bit value.
void Print (std::ostream &os) const
void Register () const override
void SetDebug (bool debugFlag) const
int SetPrefix (int prefix)
Sets the SI prefix.
void SetReferenceCount (int) override
int Unpack (igtlUnit unit)
Unpacks the unit from a 64-bit value.
void UnRegister () const override
Static Public Member Functions
static void BreakOnError ()
static bool GetGlobalWarningDisplay ()
static void GlobalWarningDisplayOff ()
static void GlobalWarningDisplayOn ()
static Pointer New ()
static void SetGlobalWarningDisplay (bool flag)
Protected Member Functions
virtual void PrintHeader (std::ostream &os) const
virtual void PrintSelf (std::ostream &os) const override
virtual void PrintTrailer (std::ostream &os) const
Unit ()
constructor
virtual ~Unit ()
destructor
Protected Attributes
volatile int m_ReferenceCount
SimpleFastMutexLock m_ReferenceCountLock
Detailed Description
The Unit class provides a general way to describe unites defined in International System of Unites (SI) in its 8-byte (or 64-bit) field. The field is designed to specifiy a unit consisting of SI-prefix (e.g. milli, micro, kilo etc...) and combination of SI-base and/or SI-derived unites. The bites in the field are assigned as follows:
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-... |PREFIX | UNIT0 | EXP0 | UNIT1 | EXP1 | UNIT2 | EXP2 +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-... 0 1 2 3 4
...-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ EXP2 | UNIT3 | EXP3 | UNIT4 | EXP4 | UNIT5 | EXP5 | ...-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ 4 5 6 7
Definition at line 44 of file igtlUnit.h.
Member Typedef Documentation
ConstPointer
typedef SmartPointer<const Self> igtl::LightObject::ConstPointer inherited
Definition at line 64 of file igtlLightObject.h.
Pointer
typedef SmartPointer<Self> igtl::LightObject::Pointer inherited
Definition at line 63 of file igtlLightObject.h.
Self
typedef LightObject igtl::LightObject::Self inherited
Standard clas typedefs.
Definition at line 62 of file igtlLightObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
SI Units.
Enumerator
SI_BASE_NONE
SI_BASE_METER
SI_BASE_GRAM
SI_BASE_SECOND
SI_BASE_AMPERE
SI_BASE_KELVIN
SI_BASE_MOLE
SI_BASE_CANDELA
SI_DERIVED_RADIAN
SI_DERIVED_STERADIAN
SI_DERIVED_HERTZ
SI_DERIVED_NEWTON
SI_DERIVED_PASCAL
SI_DERIVED_JOULE
SI_DERIVED_WATT
SI_DERIVED_COULOMB
SI_DERIVED_VOLT
SI_DERIVED_FARAD
SI_DERIVED_OHM
SI_DERIVED_SIEMENS
SI_DERIVED_WEBER
SI_DERIVED_TESLA
SI_DERIVED_HENRY
SI_DERIVED_LUMEN
SI_DERIVED_LUX
SI_DERIVED_BECQUEREL
SI_DERIVED_GRAY
SI_DERIVED_SIEVERT
SI_NUM_UNIT_TYPES
Definition at line 68 of file igtlUnit.h.
anonymous enum
anonymous enum
SI Prefix.
Enumerator
SI_PREFIX_NONE
SI_PREFIX_DEKA
SI_PREFIX_HECTO
SI_PREFIX_KILO
SI_PREFIX_MEGA
SI_PREFIX_GIGA
SI_PREFIX_TERA
SI_PREFIX_PETA
SI_PREFIX_DECI
SI_PREFIX_CENTI
SI_PREFIX_MILLI
SI_PREFIX_MICRO
SI_PREFIX_NANO
SI_PREFIX_PICO
SI_PREFIX_FEMTO
Definition at line 49 of file igtlUnit.h.
Constructor & Destructor Documentation
Unit()
igtl::Unit::Unit () protected
constructor
Definition at line 23 of file igtlUnit.cxx.
References Init(), and igtl::Object::Object().
Referenced by igtlNewMacro(), and igtlTypeMacro().
~Unit()
igtl::Unit::~Unit () protected virtual
destructor
Definition at line 30 of file igtlUnit.cxx.
Member Function Documentation
Append()
int igtl::Unit::Append (int unit, int exp)
Appends a unit with exponential.
Definition at line 62 of file igtlUnit.cxx.
References SI_NUM_UNIT_TYPES.
Referenced by igtlNewMacro().
BreakOnError()
void igtl::LightObject::BreakOnError () static inherited
This method is called when igtlExceptionMacro executes. It allows the debugger to break on error.
Definition at line 138 of file igtlLightObject.cxx.
CreateAnother()
LightObject::Pointer igtl::Object::CreateAnother () const override virtual inherited
Create an object from an instance, potentially deferring to a factory. This method allows you to create an instance of an object that is exactly the same type as the referring object. This is useful in cases where an object has been cast back to a base class.
Reimplemented from igtl::LightObject.
Definition at line 244 of file igtlObject.cxx.
References igtl::SmartPointer< TObjectType >::GetPointer(), and New().
Referenced by igtlTypeMacro().
DebugOff()
void igtl::Object::DebugOff () const virtual inherited
Turn debugging output off.
Definition at line 265 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
DebugOn()
void igtl::Object::DebugOn () const virtual inherited
Turn debugging output on.
Definition at line 254 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
Delete()
void igtl::LightObject::Delete () virtual inherited
Delete an igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C delete method will not work with reference counting.
Delete a igtl object. This method should always be used to delete an object when the new operator was used to create it. Using the C++ delete method will not work with reference counting.
Definition at line 77 of file igtlLightObject.cxx.
References UnRegister().
GetDebug()
bool igtl::Object::GetDebug () const inherited
Get the value of the debug flag.
Definition at line 276 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetGlobalWarningDisplay()
bool igtl::Object::GetGlobalWarningDisplay () static inherited
Get the value of the global debug output control flag.
Definition at line 393 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
GetNameOfClass()
virtual const char * igtl::LightObject::GetNameOfClass () const inline virtual inherited
Return the name of this class as a string. Used by the object factory (implemented in New()) to instantiate objects of a named type. Also used for debugging and other output information.
Definition at line 84 of file igtlLightObject.h.
Referenced by PrintHeader().
GetReferenceCount()
virtual int igtl::LightObject::GetReferenceCount () const inline virtual inherited
Gets the reference count on this object.
Definition at line 109 of file igtlLightObject.h.
References m_ReferenceCount.
GlobalWarningDisplayOff()
void igtl::Object::GlobalWarningDisplayOff () inline static inherited
Definition at line 111 of file igtlObject.h.
References SetGlobalWarningDisplay().
GlobalWarningDisplayOn()
void igtl::Object::GlobalWarningDisplayOn () inline static inherited
Definition at line 109 of file igtlObject.h.
References SetGlobalWarningDisplay().
igtlNewMacro()
igtl::Unit::igtlNewMacro (Self)
References Append(), Init(), Pack(), SetPrefix(), Unit(), and Unpack().
igtlTypeMacro() [1/2]
igtl::Object::igtlTypeMacro (Object , LightObject) inherited
Standard part of all igtl objects.
References CreateAnother(), DebugOff(), DebugOn(), GetDebug(), GetGlobalWarningDisplay(), igtl::LightObject::LightObject(), New(), Object(), Register(), SetDebug(), SetGlobalWarningDisplay(), SetReferenceCount(), and UnRegister().
igtlTypeMacro() [2/2]
igtl::Unit::igtlTypeMacro (Unit , Object)
References igtl::Object::Object(), and Unit().
Init()
void igtl::Unit::Init ()
Initializes the class.
Definition at line 35 of file igtlUnit.cxx.
References SI_BASE_NONE, and SI_PREFIX_NONE.
Referenced by igtlNewMacro(), Unit(), and Unpack().
New()
Object::Pointer igtl::Object::New () static inherited
Method for creation through the object factory.
Definition at line 230 of file igtlObject.cxx.
References igtl::ObjectFactory< T >::Create(), Object(), and UnRegister().
Referenced by CreateAnother(), and igtlTypeMacro().
Pack()
igtlUnit igtl::Unit::Pack ()
Packs (or serializes) the unit into a 64-bit value.
Definition at line 88 of file igtlUnit.cxx.
References igtl_unit_data::exp, igtl_unit_init(), igtl_unit_pack(), igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtlNewMacro(), and igtl::SensorMessage::SetUnit().
Print()
void igtl::LightObject::Print (std::ostream & os) const inherited
Cause the object to print itself out.
Avoid DLL boundary problems. This function will be common to all igtl objects. It just calls the header/self/trailer virtual print methods, which can be overriden by subclasses (any igtl object).
Definition at line 124 of file igtlLightObject.cxx.
References PrintHeader(), PrintSelf(), and PrintTrailer().
Referenced by igtl::operator<<().
PrintHeader()
void igtl::LightObject::PrintHeader (std::ostream & os) const protected virtual inherited
Define a default print header for all objects.
Definition at line 248 of file igtlLightObject.cxx.
References GetNameOfClass().
Referenced by Print().
PrintSelf()
void igtl::Object::PrintSelf (std::ostream & os) const override protected virtual inherited
Methods invoked by Print() to print information about the object including superclasses. Typically not called by the user (use Print() instead) but used in the hierarchical print process to combine the output of several classes.
Chaining method to print an object's instance variables, as well as its superclasses.
Reimplemented from igtl::LightObject.
Reimplemented in igtl::ClientSocket, igtl::FastMutexLock, igtl::GeneralSocket, igtl::MultiThreader, igtl::MutexLock, igtl::ObjectFactoryBase, igtl::ServerSocket, igtl::Socket, igtl::TimeStamp, igtl::UDPClientSocket, and igtl::UDPServerSocket.
Definition at line 537 of file igtlObject.cxx.
PrintTrailer()
void igtl::LightObject::PrintTrailer (std::ostream & os) const protected virtual inherited
Define a default print trailer for all objects.
Definition at line 259 of file igtlLightObject.cxx.
Referenced by Print().
Register()
void igtl::Object::Register () const override virtual inherited
Return this objects modified time. Update the modification time for this object. Many filters rely on the modification time to determine if they need to recompute their data. Increase the reference count (mark as used by another object).
Return the modification for this object. Make sure this object's modified time is greater than all others. Increase the reference count (mark as used by another object).
Reimplemented from igtl::LightObject.
Definition at line 321 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), and igtl::ObjectFactoryBase::RegisterFactory().
SetDebug()
void igtl::Object::SetDebug (bool debugFlag) const inherited
Set the value of the debug flag. A non-zero value turns debugging on.
Definition at line 287 of file igtlObject.cxx.
Referenced by igtlTypeMacro().
SetGlobalWarningDisplay()
void igtl::Object::SetGlobalWarningDisplay (bool val) static inherited
This is a global flag that controls whether any debug, warning or error messages are displayed.
Set the value of the global debug output control flag.
Definition at line 382 of file igtlObject.cxx.
Referenced by GlobalWarningDisplayOff(), GlobalWarningDisplayOn(), and igtlTypeMacro().
SetPrefix()
int igtl::Unit::SetPrefix (int prefix)
Sets the SI prefix.
Definition at line 48 of file igtlUnit.cxx.
References SI_PREFIX_FEMTO, and SI_PREFIX_NONE.
Referenced by igtlNewMacro().
SetReferenceCount()
void igtl::Object::SetReferenceCount (int ref) override virtual inherited
Sets the reference count (use with care)
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 359 of file igtlObject.cxx.
References igtlDebugMacro.
Referenced by igtlTypeMacro().
Unpack()
int igtl::Unit::Unpack (igtlUnit unit)
Unpacks the unit from a 64-bit value.
Definition at line 105 of file igtlUnit.cxx.
References igtl_unit_data::exp, igtl_unit_unpack(), Init(), igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::SensorMessage::GetUnit(), and igtlNewMacro().
UnRegister()
void igtl::Object::UnRegister () const override virtual inherited
Decrease the reference count (release by another object).
If there is a delete method, invoke it.
Reimplemented from igtl::LightObject.
Definition at line 336 of file igtlObject.cxx.
References igtlDebugMacro, and igtl::LightObject::m_ReferenceCount.
Referenced by igtlTypeMacro(), New(), and igtl::ObjectFactoryBase::UnRegisterFactory().
Field Documentation
m_ReferenceCount
volatile int igtl::LightObject::m_ReferenceCount mutable protected inherited
Number of uses of this object by other objects.
Definition at line 129 of file igtlLightObject.h.
Referenced by GetReferenceCount(), LightObject(), PrintSelf(), Register(), igtl::Object::Register(), SetReferenceCount(), UnRegister(), igtl::Object::UnRegister(), and ~LightObject().
m_ReferenceCountLock
SimpleFastMutexLock igtl::LightObject::m_ReferenceCountLock mutable protected inherited
Mutex lock to protect modification to the reference count
Definition at line 132 of file igtlLightObject.h.
Referenced by Register(), SetReferenceCount(), and UnRegister().
The documentation for this class was generated from the following files:
igtlUnit.h
igtlUnit.cxx
Generated at Tue Sep 9 2025 15:29:18 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012