igtl::SmartPointer< TObjectType > Class Template Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl::SmartPointer< TObjectType > Class Template Reference
Implements transparent reference counting.
#include <igtlSmartPointer.h>
Public Types
typedef TObjectType ObjectType
Public Member Functions
ObjectType * GetPointer () const
bool IsNotNull () const
bool IsNull () const
operator ObjectType * () const
template<typename R>
bool operator!= (R r) const
ObjectType * operator-> () const
bool operator< (const SmartPointer &r) const
bool operator<= (const SmartPointer &r) const
SmartPointer & operator= (const SmartPointer &r)
SmartPointer & operator= (ObjectType *r)
template<typename R>
bool operator== (R r) const
bool operator> (const SmartPointer &r) const
bool operator>= (const SmartPointer &r) const
ObjectType * Print (std::ostream &os) const
SmartPointer ()
SmartPointer (const SmartPointer< ObjectType > &p)
SmartPointer (ObjectType *p)
~SmartPointer ()
Detailed Description
template<class TObjectType>
class igtl::SmartPointer< TObjectType >
Implements transparent reference counting.
SmartPointer implements reference counting by overloading operator -> (and *) among others. This allows natural interface to the class referred to by the pointer without having to invoke special Register()/UnRegister() methods directly.
To compile / test this class Windows: cl SmartPointerTest.cxx; .\SmartPointerTest.exe linux: c++ SmartPointerTest.cxx ./a.out other: CCcompiler SmartPointerTest.cxx ./a.out
Definition at line 56 of file igtlSmartPointer.h.
Member Typedef Documentation
ObjectType
template<class TObjectType> typedef TObjectType igtl::SmartPointer< TObjectType >::ObjectType
Definition at line 59 of file igtlSmartPointer.h.
Constructor & Destructor Documentation
SmartPointer() [1/3]
template<class TObjectType> igtl::SmartPointer< TObjectType >::SmartPointer () inline
Constructor
Definition at line 62 of file igtlSmartPointer.h.
SmartPointer() [2/3]
template<class TObjectType> igtl::SmartPointer< TObjectType >::SmartPointer (const SmartPointer< ObjectType > & p) inline
Copy constructor
Definition at line 66 of file igtlSmartPointer.h.
SmartPointer() [3/3]
template<class TObjectType> igtl::SmartPointer< TObjectType >::SmartPointer (ObjectType * p) inline
Constructor to pointer p
Definition at line 71 of file igtlSmartPointer.h.
~SmartPointer()
template<class TObjectType> igtl::SmartPointer< TObjectType >::~SmartPointer () inline
Destructor
Definition at line 76 of file igtlSmartPointer.h.
Member Function Documentation
GetPointer()
template<class TObjectType> ObjectType * igtl::SmartPointer< TObjectType >::GetPointer () const inline
Access function to pointer.
Definition at line 106 of file igtlSmartPointer.h.
Referenced by igtl::ObjectFactory< T >::Create(), igtl::Object::CreateAnother(), igtl::CreateObjectFunction< T >::CreateObject(), and igtl::SmartPointer< Self >::operator=().
IsNotNull()
template<class TObjectType> bool igtl::SmartPointer< TObjectType >::IsNotNull () const inline
Test if the pointer has been initialized
Definition at line 91 of file igtlSmartPointer.h.
Referenced by igtl::SessionManager::Connect(), igtl::MessageFactory::CreateReceiveMessage(), igtl::MessageFactory::CreateSendMessage(), igtl::MessageFactory::GetMessage(), igtl::ImageMetaMessage::PackContent(), igtl::ThreadFunctionServer(), and igtl::PolyDataMessage::UnpackContent().
IsNull()
template<class TObjectType> bool igtl::SmartPointer< TObjectType >::IsNull () const inline
Definition at line 93 of file igtlSmartPointer.h.
operator ObjectType *()
template<class TObjectType> igtl::SmartPointer< TObjectType >::operator ObjectType * () const inline
Return pointer to object.
Definition at line 87 of file igtlSmartPointer.h.
operator!=()
template<class TObjectType> template<typename R> bool igtl::SmartPointer< TObjectType >::operator!= (R r) const inline
Definition at line 102 of file igtlSmartPointer.h.
operator->()
template<class TObjectType> ObjectType * igtl::SmartPointer< TObjectType >::operator-> () const inline
Overload operator ->
Definition at line 83 of file igtlSmartPointer.h.
operator<()
template<class TObjectType> bool igtl::SmartPointer< TObjectType >::operator< (const SmartPointer< TObjectType > & r) const inline
Comparison of pointers. Less than comparison.
Definition at line 110 of file igtlSmartPointer.h.
operator<=()
template<class TObjectType> bool igtl::SmartPointer< TObjectType >::operator<= (const SmartPointer< TObjectType > & r) const inline
Comparison of pointers. Less than or equal to comparison.
Definition at line 118 of file igtlSmartPointer.h.
operator=() [1/2]
template<class TObjectType> SmartPointer & igtl::SmartPointer< TObjectType >::operator= (const SmartPointer< TObjectType > & r) inline
Overload operator assignment.
Definition at line 126 of file igtlSmartPointer.h.
operator=() [2/2]
template<class TObjectType> SmartPointer & igtl::SmartPointer< TObjectType >::operator= (ObjectType * r) inline
Overload operator assignment.
Definition at line 130 of file igtlSmartPointer.h.
operator==()
template<class TObjectType> template<typename R> bool igtl::SmartPointer< TObjectType >::operator== (R r) const inline
Template comparison operators.
Definition at line 98 of file igtlSmartPointer.h.
operator>()
template<class TObjectType> bool igtl::SmartPointer< TObjectType >::operator> (const SmartPointer< TObjectType > & r) const inline
Comparison of pointers. Greater than comparison.
Definition at line 114 of file igtlSmartPointer.h.
operator>=()
template<class TObjectType> bool igtl::SmartPointer< TObjectType >::operator>= (const SmartPointer< TObjectType > & r) const inline
Comparison of pointers. Greater than or equal to comparison.
Definition at line 122 of file igtlSmartPointer.h.
Print()
template<class TObjectType> ObjectType * igtl::SmartPointer< TObjectType >::Print (std::ostream & os) const inline
Function to print object pointed to
Definition at line 143 of file igtlSmartPointer.h.
Referenced by igtl::operator<<().
The documentation for this class was generated from the following file:
igtlSmartPointer.h
Generated at Tue Sep 9 2025 15:29:17 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012