igtl_point.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_point.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_point.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_point_convert_byte_order (igtl_point_element *pointlist, int nitem)
igtl_uint64 igtl_export igtl_point_get_crc (igtl_point_element *pointlist, int nitem)
Function Documentation
igtl_point_convert_byte_order()
void igtl_export igtl_point_convert_byte_order (igtl_point_element * pointlist, int nelem)
Converts endianness of each element in an array of igtl_igtl_point_element from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_point.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), igtl_point_element::position, and igtl_point_element::radius.
Referenced by igtl::PointMessage::PackContent(), and igtl::PointMessage::UnpackContent().
igtl_point_get_crc()
igtl_uint64 igtl_export igtl_point_get_crc (igtl_point_element * pointlist, int nelem)
Calculates CRC of point message
Definition at line 45 of file igtl_point.c.
References crc64(), igtl_export, and IGTL_POINT_ELEMENT_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012