igtl_transform.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_transform.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
Macros
#define IGTL_TRANSFORM_SIZE 48
Functions
void igtl_export igtl_transform_convert_byte_order (igtl_float32 *transform)
igtl_uint64 igtl_export igtl_transform_get_crc (igtl_float32 *transform)
Macro Definition Documentation
IGTL_TRANSFORM_SIZE
#define IGTL_TRANSFORM_SIZE 48
Definition at line 21 of file igtl_transform.h.
Referenced by igtl::TransformMessage::CalculateContentBufferSize().
Function Documentation
igtl_transform_convert_byte_order()
void igtl_export igtl_transform_convert_byte_order (igtl_float32 * transform)
Converts endianness of each member variable in igtl_image_header from host byte order to network byte order, or vice versa.
Definition at line 22 of file igtl_transform.c.
References BYTE_SWAP_INT32, igtl_export, and igtl_is_little_endian().
Referenced by igtl::TransformMessage::PackContent(), and igtl::TransformMessage::UnpackContent().
igtl_transform_get_crc()
igtl_uint64 igtl_export igtl_transform_get_crc (igtl_float32 * transform)
Calculates CRC of transform data.
Definition at line 39 of file igtl_transform.c.
References crc64(), and igtl_export.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012