igtl_util.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_util.h File Reference
#include <stdio.h>
#include "igtl_win32header.h"
#include "igtl_types.h"
Macros
#define BYTE_SWAP_INT16(S)
#define BYTE_SWAP_INT32(L)
#define BYTE_SWAP_INT64(LL)
#define IGTL_SCALAR_COMPLEX 13
#define IGTL_SCALAR_FLOAT32 10
#define IGTL_SCALAR_FLOAT64 11
#define IGTL_SCALAR_INT16 4
#define IGTL_SCALAR_INT32 6
#define IGTL_SCALAR_INT8 2
#define IGTL_SCALAR_UINT16 5
#define IGTL_SCALAR_UINT32 7
#define IGTL_SCALAR_UINT8 3
Functions
igtl_uint64 igtl_export crc64 (unsigned char *data, igtl_uint64 len, igtl_uint64 crc)
igtl_uint32 igtl_export igtl_frac_to_nanosec (igtl_uint32 frac)
igtl_uint32 igtl_export igtl_get_scalar_size (int type)
int igtl_export igtl_is_little_endian ()
void igtl_export igtl_message_dump_hex (FILE *stream, const void *message, int max_size)
igtl_uint32 igtl_export igtl_nanosec_to_frac (igtl_uint32 nanosec)
Macro Definition Documentation
BYTE_SWAP_INT16
#define BYTE_SWAP_INT16 (S)
Value:
                            (((S) & 0xFF) << 8 \
                            | (((S) >> 8) & 0xFF))
Byte order conversion macros
Definition at line 41 of file igtl_util.h.
Referenced by igtl_bind_pack_normal(), igtl_bind_pack_request(), igtl_bind_unpack_normal(), igtl_bind_unpack_request(), igtl_colortable_convert_byte_order(), igtl_command_convert_byte_order(), igtl_frame_convert_byte_order(), igtl_header_convert_byte_order(), igtl_image_convert_byte_order(), igtl_image_get_crc(), igtl_imgmeta_convert_byte_order(), igtl_lbmeta_convert_byte_order(), igtl_ndarray_pack(), igtl_ndarray_unpack(), igtl_query_convert_byte_order(), igtl_status_convert_byte_order(), igtl_string_convert_byte_order(), igtl_videometa_convert_byte_order(), igtl::MessageRTPWrapper::SetSeqNum(), igtl::MessageRTPWrapper::UnWrapPacketWithTypeAndName(), igtl::MessageRTPWrapper::WrapMessage(), and igtl::WriteTimeInfo().
BYTE_SWAP_INT32
#define BYTE_SWAP_INT32 (L)
Value:
                            ((BYTE_SWAP_INT16 ((L) & 0xFFFF) << 16) \
                            | BYTE_SWAP_INT16 (((L) >> 16) & 0xFFFF))
Definition at line 43 of file igtl_util.h.
Referenced by igtl_command_convert_byte_order(), igtl_frame_convert_byte_order(), igtl_image_convert_byte_order(), igtl_ndarray_pack(), igtl_ndarray_unpack(), igtl_point_convert_byte_order(), igtl_polydata_convert_byteorder_topology(), igtl_polydata_pack(), igtl_polydata_unpack(), igtl_position_convert_byte_order(), igtl_position_convert_byte_order_position_only(), igtl_position_convert_byte_order_quaternion3(), igtl_qtdata_convert_byte_order(), igtl_qtrans_convert_byte_order(), igtl_query_convert_byte_order(), igtl_stt_qtdata_convert_byte_order(), igtl_stt_tdata_convert_byte_order(), igtl_stt_video_convert_byte_order(), igtl_tdata_convert_byte_order(), igtl_trajectory_convert_byte_order(), igtl_transform_convert_byte_order(), igtl_videometa_convert_byte_order(), igtl::UDPServerSocket::IsMulticastAddreesValid(), igtl::MessageRTPWrapper::SetCSRC(), igtl::MessageRTPWrapper::SetSSRC(), igtl::MessageRTPWrapper::UnWrapPacketWithTypeAndName(), igtl::MessageRTPWrapper::WrapMessage(), and igtl::WriteTimeInfo().
BYTE_SWAP_INT64
#define BYTE_SWAP_INT64 (LL)
Value:
                             ((BYTE_SWAP_INT32 ((LL) & 0xFFFFFFFF) << 32) \
                             | BYTE_SWAP_INT32 (((LL) >> 32) & 0xFFFFFFFF))
Definition at line 45 of file igtl_util.h.
Referenced by igtl_bind_pack(), igtl_bind_pack_normal(), igtl_bind_unpack(), igtl_bind_unpack_normal(), igtl_header_convert_byte_order(), igtl_imgmeta_convert_byte_order(), igtl_ndarray_pack(), igtl_ndarray_unpack(), igtl_sensor_convert_byte_order(), igtl_status_convert_byte_order(), and igtl_videometa_convert_byte_order().
IGTL_SCALAR_COMPLEX
#define IGTL_SCALAR_COMPLEX 13
Definition at line 37 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_FLOAT32
#define IGTL_SCALAR_FLOAT32 10
Definition at line 35 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_FLOAT64
#define IGTL_SCALAR_FLOAT64 11
Definition at line 36 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_INT16
#define IGTL_SCALAR_INT16 4
Definition at line 31 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_INT32
#define IGTL_SCALAR_INT32 6
Definition at line 33 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_INT8
#define IGTL_SCALAR_INT8 2
Definition at line 29 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_UINT16
#define IGTL_SCALAR_UINT16 5
Definition at line 32 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_UINT32
#define IGTL_SCALAR_UINT32 7
Definition at line 34 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
IGTL_SCALAR_UINT8
#define IGTL_SCALAR_UINT8 3
Definition at line 30 of file igtl_util.h.
Referenced by igtl_get_scalar_size().
Function Documentation
crc64()
igtl_uint64 igtl_export crc64 (unsigned char * data, igtl_uint64 len, igtl_uint64 crc)
Definition at line 24 of file igtl_util.c.
References igtl_export.
Referenced by igtl_bind_get_crc(), igtl_capability_get_crc(), igtl_colortable_get_crc(), igtl_command_get_crc(), igtl_image_get_crc(), igtl_imgmeta_get_crc(), igtl_lbmeta_get_crc(), igtl_ndarray_get_crc(), igtl_point_get_crc(), igtl_polydata_get_crc(), igtl_position_get_crc(), igtl_qtdata_get_crc(), igtl_qtrans_get_crc(), igtl_query_get_crc(), igtl_rts_qtdata_get_crc(), igtl_rts_tdata_get_crc(), igtl_sensor_get_crc(), igtl_status_get_crc(), igtl_string_get_crc(), igtl_stt_qtdata_get_crc(), igtl_stt_tdata_get_crc(), igtl_stt_video_get_crc(), igtl_tdata_get_crc(), igtl_trajectory_get_crc(), igtl_transform_get_crc(), igtl_videometa_get_crc(), igtl::ImageMessage2::Pack(), igtl::MessageBase::Pack(), and igtl::MessageBase::UnpackBody().
igtl_frac_to_nanosec()
igtl_uint32 igtl_export igtl_frac_to_nanosec (igtl_uint32 frac)
Definition at line 193 of file igtl_util.c.
References igtl_export.
Referenced by igtl::MessageBase::GetTimeStamp(), and igtl::TimeStamp::SetTime().
igtl_get_scalar_size()
igtl_uint32 igtl_export igtl_get_scalar_size (int type)
Gets size of scalar. Type should be IGTL_SCALAR_*
Definition at line 246 of file igtl_util.c.
References igtl_export, IGTL_SCALAR_COMPLEX, IGTL_SCALAR_FLOAT32, IGTL_SCALAR_FLOAT64, IGTL_SCALAR_INT16, IGTL_SCALAR_INT32, IGTL_SCALAR_INT8, IGTL_SCALAR_UINT16, IGTL_SCALAR_UINT32, and IGTL_SCALAR_UINT8.
igtl_is_little_endian()
int igtl_export igtl_is_little_endian ()
Tests endian of the host
Definition at line 17 of file igtl_util.c.
References igtl_export.
Referenced by igtl::H264Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::H265Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::igtlAV1Encoder::EncodeSingleFrameIntoVideoMSG(), igtl::VP9Encoder::EncodeSingleFrameIntoVideoMSG(), igtl_bind_pack(), igtl_bind_pack_normal(), igtl_bind_pack_request(), igtl_bind_unpack(), igtl_bind_unpack_normal(), igtl_bind_unpack_request(), igtl_colortable_convert_byte_order(), igtl_command_convert_byte_order(), igtl_frame_convert_byte_order(), igtl_header_convert_byte_order(), igtl_image_convert_byte_order(), igtl_image_get_crc(), igtl_imgmeta_convert_byte_order(), igtl_lbmeta_convert_byte_order(), igtl_ndarray_pack(), igtl_ndarray_unpack(), igtl_point_convert_byte_order(), igtl_polydata_convert_byteorder_topology(), igtl_polydata_pack(), igtl_polydata_unpack(), igtl_position_convert_byte_order(), igtl_position_convert_byte_order_position_only(), igtl_position_convert_byte_order_quaternion3(), igtl_qtdata_convert_byte_order(), igtl_qtrans_convert_byte_order(), igtl_query_convert_byte_order(), igtl_sensor_convert_byte_order(), igtl_status_convert_byte_order(), igtl_string_convert_byte_order(), igtl_stt_qtdata_convert_byte_order(), igtl_stt_tdata_convert_byte_order(), igtl_stt_video_convert_byte_order(), igtl_tdata_convert_byte_order(), igtl_trajectory_convert_byte_order(), igtl_transform_convert_byte_order(), igtl_videometa_convert_byte_order(), igtl::UDPServerSocket::IsMulticastAddreesValid(), igtl::GenericEncoder::PackUncompressedData(), igtl::VideoStreamIGTLinkServer::SendOriginalData(), igtl::MessageRTPWrapper::SetCSRC(), igtl::MessageRTPWrapper::SetSeqNum(), igtl::MessageRTPWrapper::SetSSRC(), igtl::MessageRTPWrapper::UnWrapPacketWithTypeAndName(), igtl::MessageRTPWrapper::WrapMessage(), and igtl::WriteTimeInfo().
igtl_message_dump_hex()
void igtl_export igtl_message_dump_hex (FILE * stream, const void * message, int max_size)
Definition at line 212 of file igtl_util.c.
References igtl_export.
igtl_nanosec_to_frac()
igtl_uint32 igtl_export igtl_nanosec_to_frac (igtl_uint32 nanosec)
Converts nanosecond to fraction / fraction to nanosec.
Definition at line 168 of file igtl_util.c.
References igtl_export.
Referenced by igtl::TimeStamp::GetTimeStampUint64(), and igtl::MessageBase::SetTimeStamp().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012