igtl_lbmeta.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_lbmeta.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_lbmeta.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_lbmeta_convert_byte_order (igtl_lbmeta_element *metalist, int nitem)
igtl_uint64 igtl_export igtl_lbmeta_get_crc (igtl_lbmeta_element *metalist, int nitem)
Function Documentation
igtl_lbmeta_convert_byte_order()
void igtl_export igtl_lbmeta_convert_byte_order (igtl_lbmeta_element * metalist, int nitem)
Converts endianness of each member variable in igtl_lbmeta_element from host byte order to network byte order, or vice versa.
Definition at line 22 of file igtl_lbmeta.c.
References BYTE_SWAP_INT16, igtl_export, igtl_is_little_endian(), and igtl_lbmeta_element::size.
Referenced by igtl::LabelMetaMessage::PackContent(), and igtl::LabelMetaMessage::UnpackContent().
igtl_lbmeta_get_crc()
igtl_uint64 igtl_export igtl_lbmeta_get_crc (igtl_lbmeta_element * metalist, int nitem)
Calculates CRC of image meta data body.
Definition at line 40 of file igtl_lbmeta.c.
References crc64(), igtl_export, and IGTL_LBMETA_ELEMENT_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012