igtl_videometa.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_videometa.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_videometa.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_videometa_convert_byte_order (igtl_videometa_element *metalist, int nitem)
igtl_uint64 igtl_export igtl_videometa_get_crc (igtl_videometa_element *metalist, int nitem)
void igtl_export igtl_videometa_get_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_videometa_element *element)
void igtl_export igtl_videometa_get_matrix_4x4 (float _matrix[4][4], igtl_videometa_element *element)
void igtl_export igtl_videometa_set_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_videometa_element *element)
void igtl_export igtl_videometa_set_matrix_4x4 (float _matrix[4][4], igtl_videometa_element *element)
Function Documentation
igtl_videometa_convert_byte_order()
void igtl_export igtl_videometa_convert_byte_order (igtl_videometa_element * metalist, int nitem)
Converts endianness of each member variable in igtl_videometa_element from host byte order to network byte order, or vice versa.
Definition at line 138 of file igtl_videometa.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, BYTE_SWAP_INT64, igtl_videometa_element::focal_length, igtl_export, igtl_is_little_endian(), igtl_videometa_element::matrix, igtl_videometa_element::size, and igtl_videometa_element::zoom_level.
Referenced by igtl::VideoMetaMessage::PackContent(), and igtl::VideoMetaMessage::UnpackContent().
igtl_videometa_get_crc()
igtl_uint64 igtl_export igtl_videometa_get_crc (igtl_videometa_element * metalist, int nitem)
Clculates CRC of video meta data body.
Definition at line 179 of file igtl_videometa.c.
References crc64(), igtl_export, and IGTL_VIDEOMETA_ELEMENT_SIZE.
igtl_videometa_get_matrix()
void igtl_export igtl_videometa_get_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_videometa_element * element)
Definition at line 55 of file igtl_videometa.c.
References igtl_export, and igtl_videometa_element::matrix.
Referenced by igtl::VideoMetaMessage::UnpackContent().
igtl_videometa_get_matrix_4x4()
void igtl_export igtl_videometa_get_matrix_4x4 (float _matrix[4][4], igtl_videometa_element * element)
Gets the image orientation/origin matrix in 4x4 format
Definition at line 115 of file igtl_videometa.c.
References igtl_export, and igtl_videometa_element::matrix.
igtl_videometa_set_matrix()
void igtl_export igtl_videometa_set_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_videometa_element * element)
Generates image orientation/origin matrix from spacing, origin and normal vectors.
Definition at line 21 of file igtl_videometa.c.
References igtl_export, and igtl_videometa_element::matrix.
Referenced by igtl::VideoMetaMessage::PackContent().
igtl_videometa_set_matrix_4x4()
void igtl_export igtl_videometa_set_matrix_4x4 (float _matrix[4][4], igtl_videometa_element * element)
Sets the image orientation/origin matrix in 4x4 format
Definition at line 39 of file igtl_videometa.c.
References igtl_export, and igtl_videometa_element::matrix.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012