igtl_polydata.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_polydata.c File Reference
#include <stdlib.h>
#include <string.h>
#include "igtl_polydata.h"
#include "igtl_util.h"
Functions
int igtl_export igtl_polydata_alloc_info (igtl_polydata_info *info)
int igtl_polydata_convert_byteorder_topology (igtl_uint32 *dst, igtl_uint32 *src, igtl_uint32 size)
int igtl_export igtl_polydata_free_info (igtl_polydata_info *info)
igtl_uint64 igtl_export igtl_polydata_get_crc (igtl_polydata_info *info, int type, void *polydata_message)
igtl_uint64 igtl_export igtl_polydata_get_size (igtl_polydata_info *info, int type)
void igtl_export igtl_polydata_init_info (igtl_polydata_info *info)
int igtl_export igtl_polydata_pack (igtl_polydata_info *info, void *byte_array, int type)
int igtl_export igtl_polydata_unpack (int type, void *byte_array, igtl_polydata_info *info, igtl_uint64 size)
Function Documentation
igtl_polydata_alloc_info()
int igtl_export igtl_polydata_alloc_info (igtl_polydata_info * info)
Allocates free arrays in polydata_info. Note that igtl_polydata_alloc_info() does not allocate memory for 'name' and 'data' in each igtl_polydata_attribute. Those elements have to be allocated in the developers responsibility. igtl_polydata_free_info() function assumes that igtl_polydata_info is allocated by igtl_polydata_alloc_info() and all memory blocks pointed from igtl_polydata_attribute have been allocated by malloc(). Return 1 if the array is successfully allocated/freed.
Points
Vertices
Lines
Polygons
Triangle strips
Attributes
Definition at line 46 of file igtl_polydata.c.
References igtl_polydata_info::attributes, igtl_polydata_attribute::data, igtl_polydata_info::header, igtl_export, igtl_polydata_info::lines, igtl_polydata_attribute::n, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_attribute::ncomponents, igtl_polydata_header::nlines, igtl_polydata_header::npoints, igtl_polydata_header::npolygons, igtl_polydata_header::ntriangle_strips, igtl_polydata_header::nvertices, igtl_polydata_info::points, igtl_polydata_info::polygons, igtl_polydata_header::size_lines, igtl_polydata_header::size_polygons, igtl_polydata_header::size_triangle_strips, igtl_polydata_header::size_vertices, igtl_polydata_info::triangle_strips, igtl_polydata_attribute::type, and igtl_polydata_info::vertices.
Referenced by igtl_polydata_unpack(), and igtl::PolyDataMessage::PackContent().
igtl_polydata_convert_byteorder_topology()
int igtl_polydata_convert_byteorder_topology (igtl_uint32 * dst, igtl_uint32 * src, igtl_uint32 size)
Definition at line 234 of file igtl_polydata.c.
References BYTE_SWAP_INT32, and igtl_is_little_endian().
Referenced by igtl_polydata_pack(), and igtl_polydata_unpack().
igtl_polydata_free_info()
int igtl_export igtl_polydata_free_info (igtl_polydata_info * info)
Points
Vertices
Lines
Polygons
Triangle strips
Attributes
Definition at line 168 of file igtl_polydata.c.
References igtl_polydata_info::attributes, igtl_polydata_attribute::data, igtl_polydata_info::header, igtl_export, igtl_polydata_info::lines, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_info::points, igtl_polydata_info::polygons, igtl_polydata_info::triangle_strips, and igtl_polydata_info::vertices.
Referenced by igtl::PolyDataMessage::PackContent().
igtl_polydata_get_crc()
igtl_uint64 igtl_export igtl_polydata_get_crc (igtl_polydata_info * info, int type, void * polydata_message)
Calculates CRC of POLYDATA message. Note that 'info' is used only for getting size of the message.
Definition at line 738 of file igtl_polydata.c.
References crc64(), igtl_export, and igtl_polydata_get_size().
igtl_polydata_get_size()
igtl_uint64 igtl_export igtl_polydata_get_size (igtl_polydata_info * info, int type)
igtl_polydata_get_size() calculates the size of polydata header, consisting of POLYDATA hearder section (including number of child messages) and name table section based on a igtl_polydata_header. The size returned from this function does not include size of child message data. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro.
Definition at line 668 of file igtl_polydata.c.
References igtl_polydata_info::attributes, igtl_polydata_info::header, igtl_export, IGTL_POLY_ATTR_TYPE_NORMAL, IGTL_POLY_ATTR_TYPE_SCALAR, IGTL_POLY_ATTR_TYPE_VECTOR, IGTL_POLY_MAX_ATTR_NAME_LEN, igtl_polydata_attribute::n, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_attribute::ncomponents, igtl_polydata_header::npoints, igtl_polydata_header::size_lines, igtl_polydata_header::size_polygons, igtl_polydata_header::size_triangle_strips, igtl_polydata_header::size_vertices, and igtl_polydata_attribute::type.
Referenced by igtl::PolyDataMessage::CalculateContentBufferSize(), and igtl_polydata_get_crc().
igtl_polydata_init_info()
void igtl_export igtl_polydata_init_info (igtl_polydata_info * info)
Initializes igtl_polydata_info
Definition at line 22 of file igtl_polydata.c.
References igtl_polydata_info::attributes, igtl_polydata_info::header, igtl_export, igtl_polydata_info::lines, igtl_polydata_header::nattributes, igtl_polydata_header::nlines, igtl_polydata_header::npoints, igtl_polydata_header::npolygons, igtl_polydata_header::ntriangle_strips, igtl_polydata_header::nvertices, igtl_polydata_info::points, igtl_polydata_info::polygons, igtl_polydata_header::size_lines, igtl_polydata_header::size_polygons, igtl_polydata_header::size_triangle_strips, igtl_polydata_header::size_vertices, igtl_polydata_info::triangle_strips, and igtl_polydata_info::vertices.
Referenced by igtl::SetPolyDataInfo(), and igtl::PolyDataMessage::UnpackContent().
igtl_polydata_pack()
int igtl_export igtl_polydata_pack (igtl_polydata_info * info, void * byte_array, int type)
Converts an igtl_polydata_info structure to a byte array. 'byte_array' should be allocated prior to calling igtl_polydata_pack() with memory size calculated by igtl_polydata_get_size(). 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 465 of file igtl_polydata.c.
References igtl_polydata_info::attributes, BYTE_SWAP_INT32, igtl_polydata_attribute::data, igtl_polydata_info::header, igtl_export, igtl_is_little_endian(), IGTL_POLY_ATTR_TYPE_NORMAL, IGTL_POLY_ATTR_TYPE_SCALAR, IGTL_POLY_ATTR_TYPE_TCOORDS, IGTL_POLY_ATTR_TYPE_VECTOR, IGTL_POLY_MAX_ATTR_NAME_LEN, igtl_polydata_convert_byteorder_topology(), igtl_polydata_info::lines, igtl_polydata_attribute::n, igtl_polydata_attribute_header::n, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_attribute::ncomponents, igtl_polydata_attribute_header::ncomponents, igtl_polydata_header::nlines, igtl_polydata_header::npoints, igtl_polydata_header::npolygons, igtl_polydata_header::ntriangle_strips, igtl_polydata_header::nvertices, igtl_polydata_info::points, igtl_polydata_info::polygons, igtl_polydata_header::size_lines, igtl_polydata_header::size_polygons, igtl_polydata_header::size_triangle_strips, igtl_polydata_header::size_vertices, igtl_polydata_info::triangle_strips, igtl_polydata_attribute::type, igtl_polydata_attribute_header::type, and igtl_polydata_info::vertices.
Referenced by igtl::PolyDataMessage::PackContent().
igtl_polydata_unpack()
int igtl_export igtl_polydata_unpack (int type, void * byte_array, igtl_polydata_info * info, igtl_uint64 size)
Extracts information about child messages in a byte array of POLYDATA messages and store it in a igtl_polydata_info structure. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 272 of file igtl_polydata.c.
References igtl_polydata_info::attributes, BYTE_SWAP_INT32, igtl_polydata_attribute::data, igtl_polydata_info::header, igtl_export, igtl_is_little_endian(), IGTL_POLY_ATTR_TYPE_NORMAL, IGTL_POLY_ATTR_TYPE_SCALAR, IGTL_POLY_ATTR_TYPE_VECTOR, IGTL_POLY_MAX_ATTR_NAME_LEN, igtl_polydata_alloc_info(), igtl_polydata_convert_byteorder_topology(), igtl_polydata_info::lines, igtl_polydata_attribute::n, igtl_polydata_attribute_header::n, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_attribute::ncomponents, igtl_polydata_attribute_header::ncomponents, igtl_polydata_header::nlines, igtl_polydata_header::npoints, igtl_polydata_header::npolygons, igtl_polydata_header::ntriangle_strips, igtl_polydata_header::nvertices, igtl_polydata_info::points, igtl_polydata_info::polygons, igtl_polydata_header::size_lines, igtl_polydata_header::size_polygons, igtl_polydata_header::size_triangle_strips, igtl_polydata_header::size_vertices, igtl_polydata_info::triangle_strips, igtl_polydata_attribute::type, igtl_polydata_attribute_header::type, and igtl_polydata_info::vertices.
Referenced by igtl::PolyDataMessage::UnpackContent().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012