igtl_sensor.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_sensor.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
#include "igtl_unit.h"
Data Structures
struct igtl_sensor_header
Macros
#define IGTL_SENSOR_HEADER_SIZE 10
Functions
void igtl_export igtl_sensor_convert_byte_order (igtl_sensor_header *header, igtl_float64 *data)
igtl_uint64 igtl_export igtl_sensor_get_crc (igtl_sensor_header *header, igtl_float64 *data)
igtl_uint32 igtl_export igtl_sensor_get_data_size (igtl_sensor_header *header)
Macro Definition Documentation
IGTL_SENSOR_HEADER_SIZE
#define IGTL_SENSOR_HEADER_SIZE 10
Definition at line 24 of file igtl_sensor.h.
Referenced by igtl_sensor_get_crc().
Function Documentation
igtl_sensor_convert_byte_order()
void igtl_export igtl_sensor_convert_byte_order (igtl_sensor_header * header, igtl_float64 * data)
This function converts endianness from host byte order to network byte order, or vice versa.
Definition at line 32 of file igtl_sensor.c.
References BYTE_SWAP_INT64, igtl_export, igtl_is_little_endian(), igtl_sensor_header::larray, and igtl_sensor_header::unit.
Referenced by igtl::SensorMessage::PackContent(), and igtl::SensorMessage::UnpackContent().
igtl_sensor_get_crc()
igtl_uint64 igtl_export igtl_sensor_get_crc (igtl_sensor_header * header, igtl_float64 * data)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 52 of file igtl_sensor.c.
References crc64(), igtl_export, IGTL_SENSOR_HEADER_SIZE, and igtl_sensor_header::larray.
igtl_sensor_get_data_size()
igtl_uint32 igtl_export igtl_sensor_get_data_size (igtl_sensor_header * header)
This function calculates size of the pixel array, which will be transferred with the specified header.
Definition at line 21 of file igtl_sensor.c.
References igtl_export, and igtl_sensor_header::larray.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012