igtl_qtdata.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_qtdata.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_qtdata.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_qtdata_convert_byte_order (igtl_qtdata_element *qtdatalist, int nitem)
igtl_uint64 igtl_export igtl_qtdata_get_crc (igtl_qtdata_element *qtdatalist, int nitem)
void igtl_export igtl_rts_qtdata_convert_byte_order (igtl_rts_qtdata *rts_qtdata)
igtl_uint64 igtl_export igtl_rts_qtdata_get_crc (igtl_rts_qtdata *rts_qtdata)
void igtl_export igtl_stt_qtdata_convert_byte_order (igtl_stt_qtdata *stt_qtdata)
igtl_uint64 igtl_export igtl_stt_qtdata_get_crc (igtl_stt_qtdata *stt_qtdata)
Function Documentation
igtl_qtdata_convert_byte_order()
void igtl_export igtl_qtdata_convert_byte_order (igtl_qtdata_element * qtdatalist, int nelem)
Byte order conversion for an array of QTDATA, STT_QTDATA and RTS_QTDATA data structure Converts endianness of each element in an array of igtl_qtdata_element from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_qtdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), igtl_qtdata_element::position, and igtl_qtdata_element::quaternion.
Referenced by igtl::QuaternionTrackingDataMessage::PackContent(), and igtl::QuaternionTrackingDataMessage::UnpackContent().
igtl_qtdata_get_crc()
igtl_uint64 igtl_export igtl_qtdata_get_crc (igtl_qtdata_element * qtdatalist, int nelem)
Calculates CRC of QTDATA, STT_QTDATA and RTS_QTDATA messages
Definition at line 67 of file igtl_qtdata.c.
References crc64(), igtl_export, and IGTL_QTDATA_ELEMENT_SIZE.
igtl_rts_qtdata_convert_byte_order()
void igtl_export igtl_rts_qtdata_convert_byte_order (igtl_rts_qtdata * rts_qtdata)
Definition at line 61 of file igtl_qtdata.c.
References igtl_export.
Referenced by igtl::RTSQuaternionTrackingDataMessage::PackContent(), and igtl::RTSQuaternionTrackingDataMessage::UnpackContent().
igtl_rts_qtdata_get_crc()
igtl_uint64 igtl_export igtl_rts_qtdata_get_crc (igtl_rts_qtdata * rts_qtdata)
Definition at line 94 of file igtl_qtdata.c.
References crc64(), igtl_export, and IGTL_RTS_QTDATA_SIZE.
igtl_stt_qtdata_convert_byte_order()
void igtl_export igtl_stt_qtdata_convert_byte_order (igtl_stt_qtdata * stt_qtdata)
Definition at line 49 of file igtl_qtdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_stt_qtdata::resolution.
Referenced by igtl::StartQuaternionTrackingDataMessage::PackContent(), and igtl::StartQuaternionTrackingDataMessage::UnpackContent().
igtl_stt_qtdata_get_crc()
igtl_uint64 igtl_export igtl_stt_qtdata_get_crc (igtl_stt_qtdata * stt_qtdata)
Definition at line 84 of file igtl_qtdata.c.
References crc64(), igtl_export, and IGTL_STT_QTDATA_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012