igtl_status.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_status.c File Reference
#include <string.h>
#include "igtl_status.h"
#include "igtl_util.h"
#include <stdio.h>
Functions
void igtl_export igtl_status_convert_byte_order (igtl_status_header *status)
igtl_uint64 igtl_export igtl_status_get_crc (igtl_status_header *status, igtl_uint32 msglen, const char *msg)
Function Documentation
igtl_status_convert_byte_order()
void igtl_export igtl_status_convert_byte_order (igtl_status_header * status)
Converts endianness of each member variable in igtl_status_header from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_status.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT64, igtl_status_header::code, igtl_export, igtl_is_little_endian(), and igtl_status_header::subcode.
Referenced by igtl::StatusMessage::PackContent(), and igtl::StatusMessage::UnpackContent().
igtl_status_get_crc()
igtl_uint64 igtl_export igtl_status_get_crc (igtl_status_header * status, igtl_uint32 msglen, const char * msg)
Calculates CRC of status data body including status message part
Definition at line 32 of file igtl_status.c.
References crc64(), igtl_export, and IGTL_STATUS_HEADER_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012