igtl_bind.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_bind.h File Reference
#include "igtl_win32header.h"
#include "igtl_header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_bind_child_info
struct igtl_bind_info
Functions
int igtl_export igtl_bind_alloc_info (igtl_bind_info *bind_info, igtl_uint16 ncmessages)
int igtl_export igtl_bind_free_info (igtl_bind_info *bind_info)
igtl_uint64 igtl_export igtl_bind_get_crc (igtl_bind_info *info, int type, void *bind_message)
igtl_uint64 igtl_export igtl_bind_get_size (igtl_bind_info *info, int type)
void igtl_export igtl_bind_init_info (igtl_bind_info *bind_info)
int igtl_export igtl_bind_pack (igtl_bind_info *info, void *byte_array, int type)
int igtl_export igtl_bind_unpack (int type, void *byte_array, igtl_bind_info *info, igtl_uint64 size)
Function Documentation
igtl_bind_alloc_info()
int igtl_export igtl_bind_alloc_info (igtl_bind_info * bind_info, igtl_uint16 ncmessages)
Allocates an array of igtl_bind_child_info in bind_info with length of 'ncmessages.' Returns 1 if the array is successfully allocated/freed
Definition at line 35 of file igtl_bind.c.
References igtl_bind_info::child_info_array, igtl_export, and igtl_bind_info::ncmessages.
Referenced by igtl_bind_unpack_normal(), igtl_bind_unpack_request(), igtl::BindMessage::PackContent(), igtl::GetBindMessage::PackContent(), and igtl::StartBindMessage::PackContent().
igtl_bind_free_info()
int igtl_export igtl_bind_free_info (igtl_bind_info * bind_info)
Frees an array of igtl_bind_child_info in bind_info with length of 'ncmessages.' Returns 1 if the array is successfully allocated/freed
Definition at line 61 of file igtl_bind.c.
References igtl_bind_info::child_info_array, igtl_export, and igtl_bind_info::ncmessages.
Referenced by igtl::BindMessage::PackContent(), igtl::GetBindMessage::PackContent(), and igtl::StartBindMessage::PackContent().
igtl_bind_get_crc()
igtl_uint64 igtl_export igtl_bind_get_crc (igtl_bind_info * info, int type, void * bind_message)
Calculates CRC of BIND message. Note that 'info' is used only for getting size of the message.
Definition at line 690 of file igtl_bind.c.
References igtl_bind_info::child_info_array, crc64(), igtl_bind_get_size(), igtl_export, IGTL_TYPE_PREFIX_NONE, igtl_bind_info::ncmessages, igtl_bind_child_info::ptr, and igtl_bind_child_info::size.
igtl_bind_get_size()
igtl_uint64 igtl_export igtl_bind_get_size (igtl_bind_info * info, int type)
igtl_bind_get_size() calculates the size of bind header, consisting of BIND hearder section (including number of child messages) and name table section based on a igtl_bind_header. The size returned from this function does not include size of child message data. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro.
Definition at line 655 of file igtl_bind.c.
References igtl_bind_get_size_normal(), igtl_bind_get_size_request(), igtl_export, IGTL_TYPE_PREFIX_GET, IGTL_TYPE_PREFIX_NONE, IGTL_TYPE_PREFIX_RTS, IGTL_TYPE_PREFIX_STP, and IGTL_TYPE_PREFIX_STT.
Referenced by igtl_bind_get_crc(), and igtl::BindMessage::PackContent().
igtl_bind_init_info()
void igtl_export igtl_bind_init_info (igtl_bind_info * bind_info)
Initializes igtl_bind_info
Definition at line 22 of file igtl_bind.c.
References igtl_bind_info::child_info_array, igtl_export, igtl_bind_info::ncmessages, igtl_bind_info::request_all, igtl_bind_info::resol, and igtl_bind_info::status.
Referenced by igtl::BindMessage::PackContent(), igtl::GetBindMessage::PackContent(), and igtl::StartBindMessage::PackContent().
igtl_bind_pack()
int igtl_export igtl_bind_pack (igtl_bind_info * info, void * byte_array, int type)
Packs BIND message. Converts an igtl_bind_info structure to a byte array. 'byte_array' should be allocated prior to calling igtl_bind_pack() with memory size calculated by igtl_bind_get_size(). 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 529 of file igtl_bind.c.
References BYTE_SWAP_INT64, igtl_bind_pack_normal(), igtl_bind_pack_request(), igtl_export, igtl_is_little_endian(), IGTL_TYPE_PREFIX_GET, IGTL_TYPE_PREFIX_NONE, IGTL_TYPE_PREFIX_RTS, IGTL_TYPE_PREFIX_STP, IGTL_TYPE_PREFIX_STT, igtl_bind_info::resol, and igtl_bind_info::status.
Referenced by igtl::BindMessage::PackContent(), igtl::GetBindMessage::PackContent(), and igtl::StartBindMessage::PackContent().
igtl_bind_unpack()
int igtl_export igtl_bind_unpack (int type, void * byte_array, igtl_bind_info * info, igtl_uint64 size)
Unpacks BIND message. Extracts information about child messages in a byte array of BIND messages and store it in a igtl_bind_info structure. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 292 of file igtl_bind.c.
References BYTE_SWAP_INT64, igtl_bind_unpack_normal(), igtl_bind_unpack_request(), igtl_export, igtl_is_little_endian(), IGTL_TYPE_PREFIX_GET, IGTL_TYPE_PREFIX_NONE, IGTL_TYPE_PREFIX_RTS, IGTL_TYPE_PREFIX_STP, IGTL_TYPE_PREFIX_STT, igtl_bind_info::resol, and igtl_bind_info::status.
Referenced by igtl::BindMessage::UnpackContent(), igtl::GetBindMessage::UnpackContent(), and igtl::StartBindMessage::UnpackContent().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012