igtl_unit.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_unit.h File Reference
#include "igtl_types.h"
#include "igtl_win32header.h"
#include "igtl_unit.h"
Data Structures
struct igtl_unit_data
Macros
#define IGTL_UNIT_PREFIX_CENTI 0xA /* centi (1e-2) */
#define IGTL_UNIT_PREFIX_DECI 0x9 /* deci (1e-1) */
#define IGTL_UNIT_PREFIX_DEKA 0x1 /* deka (deca) (1e1) */
#define IGTL_UNIT_PREFIX_FEMTO 0xF /* femto (1e-15) */
#define IGTL_UNIT_PREFIX_GIGA 0x5 /* giga (1e9) */
#define IGTL_UNIT_PREFIX_HECTO 0x2 /* hecto (1e2) */
#define IGTL_UNIT_PREFIX_KILO 0x3 /* kilo (1e3) */
#define IGTL_UNIT_PREFIX_MEGA 0x4 /* mega (1e6) */
#define IGTL_UNIT_PREFIX_MICRO 0xC /* micro (1e-6) */
#define IGTL_UNIT_PREFIX_MILLI 0xB /* milli (1e-3) */
#define IGTL_UNIT_PREFIX_NANO 0xD /* nano (1e-9) */
#define IGTL_UNIT_PREFIX_NONE 0x0 /* None */
#define IGTL_UNIT_PREFIX_PETA 0x7 /* peta (1e15) */
#define IGTL_UNIT_PREFIX_PICO 0xE /* pico (1e-12) */
#define IGTL_UNIT_PREFIX_TERA 0x6 /* tera (1e12) */
#define IGTL_UNIT_SI_BASE_AMPERE 0x04 /* ampere */
#define IGTL_UNIT_SI_BASE_CANDELA 0x07 /* candela */
#define IGTL_UNIT_SI_BASE_GRAM 0x02 /* gram */
#define IGTL_UNIT_SI_BASE_KELVIN 0x05 /* kelvin */
#define IGTL_UNIT_SI_BASE_METER 0x01 /* meter */
#define IGTL_UNIT_SI_BASE_MOLE 0x06 /* mole */
#define IGTL_UNIT_SI_BASE_NONE 0x00
#define IGTL_UNIT_SI_BASE_SECOND 0x03 /* second */
#define IGTL_UNIT_SI_DERIVED_BECQUEREL 0x19 /* becquerel /second */
#define IGTL_UNIT_SI_DERIVED_COULOMB 0x0F /* coulomb second-ampere */
#define IGTL_UNIT_SI_DERIVED_FARAD 0x11 /* farad second^4-ampere^2/meter^2-kilogram */
#define IGTL_UNIT_SI_DERIVED_GRAY 0x1A /* gray meter^2/second^2 */
#define IGTL_UNIT_SI_DERIVED_HENRY 0x16 /* henry meter^2-kilogram/second^2-ampere^2 */
#define IGTL_UNIT_SI_DERIVED_HERTZ 0x0A /* hertz /second */
#define IGTL_UNIT_SI_DERIVED_JOULE 0x0D /* joule meter^2-kilogram/second^2 */
#define IGTL_UNIT_SI_DERIVED_LUMEN 0x17 /* lumen candela-steradian */
#define IGTL_UNIT_SI_DERIVED_LUX 0x18 /* lux candela-steradian/meter^2 */
#define IGTL_UNIT_SI_DERIVED_NEWTON 0x0B /* newton meter-kilogram/second^2 */
#define IGTL_UNIT_SI_DERIVED_OHM 0x12 /* ohm meter^2-kilogram/second^3-ampere^2 */
#define IGTL_UNIT_SI_DERIVED_PASCAL 0x0C /* pascal kilogram/meter-second^2 */
#define IGTL_UNIT_SI_DERIVED_RADIAN 0x08 /* radian meter/meter */
#define IGTL_UNIT_SI_DERIVED_SIEMENS 0x13 /* siemens second^3-ampere^2/meter^2-kilogram */
#define IGTL_UNIT_SI_DERIVED_SIEVERT 0x1B /* sievert meter^2/second^2 */
#define IGTL_UNIT_SI_DERIVED_STERADIAN 0x09 /* steradian meter^2/meter^2 */
#define IGTL_UNIT_SI_DERIVED_TESLA 0x15 /* tesla kilogram/second^2-ampere */
#define IGTL_UNIT_SI_DERIVED_VOLT 0x10 /* volt meter^2-kilogram/second^3-ampere */
#define IGTL_UNIT_SI_DERIVED_WATT 0x0E /* watt meter^2-kilogram/second^3 */
#define IGTL_UNIT_SI_DERIVED_WEBER 0x14 /* weber meter^2-kilogram/second^2-ampere */
Typedefs
typedef igtl_uint64 igtl_unit
Functions
void igtl_export igtl_unit_init (igtl_unit_data *data)
igtl_unit igtl_export igtl_unit_pack (igtl_unit_data *data)
int igtl_export igtl_unit_unpack (igtl_unit pack, igtl_unit_data *data)
Macro Definition Documentation
IGTL_UNIT_PREFIX_CENTI
#define IGTL_UNIT_PREFIX_CENTI 0xA /* centi (1e-2) */
Definition at line 33 of file igtl_unit.h.
IGTL_UNIT_PREFIX_DECI
#define IGTL_UNIT_PREFIX_DECI 0x9 /* deci (1e-1) */
Definition at line 32 of file igtl_unit.h.
IGTL_UNIT_PREFIX_DEKA
#define IGTL_UNIT_PREFIX_DEKA 0x1 /* deka (deca) (1e1) */
Definition at line 25 of file igtl_unit.h.
IGTL_UNIT_PREFIX_FEMTO
#define IGTL_UNIT_PREFIX_FEMTO 0xF /* femto (1e-15) */
Definition at line 38 of file igtl_unit.h.
IGTL_UNIT_PREFIX_GIGA
#define IGTL_UNIT_PREFIX_GIGA 0x5 /* giga (1e9) */
Definition at line 29 of file igtl_unit.h.
IGTL_UNIT_PREFIX_HECTO
#define IGTL_UNIT_PREFIX_HECTO 0x2 /* hecto (1e2) */
Definition at line 26 of file igtl_unit.h.
IGTL_UNIT_PREFIX_KILO
#define IGTL_UNIT_PREFIX_KILO 0x3 /* kilo (1e3) */
Definition at line 27 of file igtl_unit.h.
IGTL_UNIT_PREFIX_MEGA
#define IGTL_UNIT_PREFIX_MEGA 0x4 /* mega (1e6) */
Definition at line 28 of file igtl_unit.h.
IGTL_UNIT_PREFIX_MICRO
#define IGTL_UNIT_PREFIX_MICRO 0xC /* micro (1e-6) */
Definition at line 35 of file igtl_unit.h.
IGTL_UNIT_PREFIX_MILLI
#define IGTL_UNIT_PREFIX_MILLI 0xB /* milli (1e-3) */
Definition at line 34 of file igtl_unit.h.
IGTL_UNIT_PREFIX_NANO
#define IGTL_UNIT_PREFIX_NANO 0xD /* nano (1e-9) */
Definition at line 36 of file igtl_unit.h.
IGTL_UNIT_PREFIX_NONE
#define IGTL_UNIT_PREFIX_NONE 0x0 /* None */
Definition at line 24 of file igtl_unit.h.
IGTL_UNIT_PREFIX_PETA
#define IGTL_UNIT_PREFIX_PETA 0x7 /* peta (1e15) */
Definition at line 31 of file igtl_unit.h.
IGTL_UNIT_PREFIX_PICO
#define IGTL_UNIT_PREFIX_PICO 0xE /* pico (1e-12) */
Definition at line 37 of file igtl_unit.h.
IGTL_UNIT_PREFIX_TERA
#define IGTL_UNIT_PREFIX_TERA 0x6 /* tera (1e12) */
Definition at line 30 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_AMPERE
#define IGTL_UNIT_SI_BASE_AMPERE 0x04 /* ampere */
Definition at line 45 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_CANDELA
#define IGTL_UNIT_SI_BASE_CANDELA 0x07 /* candela */
Definition at line 48 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_GRAM
#define IGTL_UNIT_SI_BASE_GRAM 0x02 /* gram */
Definition at line 43 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_KELVIN
#define IGTL_UNIT_SI_BASE_KELVIN 0x05 /* kelvin */
Definition at line 46 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_METER
#define IGTL_UNIT_SI_BASE_METER 0x01 /* meter */
Definition at line 42 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_MOLE
#define IGTL_UNIT_SI_BASE_MOLE 0x06 /* mole */
Definition at line 47 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_NONE
#define IGTL_UNIT_SI_BASE_NONE 0x00
Definition at line 41 of file igtl_unit.h.
IGTL_UNIT_SI_BASE_SECOND
#define IGTL_UNIT_SI_BASE_SECOND 0x03 /* second */
Definition at line 44 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_BECQUEREL
#define IGTL_UNIT_SI_DERIVED_BECQUEREL 0x19 /* becquerel /second */
Definition at line 68 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_COULOMB
#define IGTL_UNIT_SI_DERIVED_COULOMB 0x0F /* coulomb second-ampere */
Definition at line 58 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_FARAD
#define IGTL_UNIT_SI_DERIVED_FARAD 0x11 /* farad second^4-ampere^2/meter^2-kilogram */
Definition at line 60 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_GRAY
#define IGTL_UNIT_SI_DERIVED_GRAY 0x1A /* gray meter^2/second^2 */
Definition at line 69 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_HENRY
#define IGTL_UNIT_SI_DERIVED_HENRY 0x16 /* henry meter^2-kilogram/second^2-ampere^2 */
Definition at line 65 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_HERTZ
#define IGTL_UNIT_SI_DERIVED_HERTZ 0x0A /* hertz /second */
Definition at line 53 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_JOULE
#define IGTL_UNIT_SI_DERIVED_JOULE 0x0D /* joule meter^2-kilogram/second^2 */
Definition at line 56 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_LUMEN
#define IGTL_UNIT_SI_DERIVED_LUMEN 0x17 /* lumen candela-steradian */
Definition at line 66 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_LUX
#define IGTL_UNIT_SI_DERIVED_LUX 0x18 /* lux candela-steradian/meter^2 */
Definition at line 67 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_NEWTON
#define IGTL_UNIT_SI_DERIVED_NEWTON 0x0B /* newton meter-kilogram/second^2 */
Definition at line 54 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_OHM
#define IGTL_UNIT_SI_DERIVED_OHM 0x12 /* ohm meter^2-kilogram/second^3-ampere^2 */
Definition at line 61 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_PASCAL
#define IGTL_UNIT_SI_DERIVED_PASCAL 0x0C /* pascal kilogram/meter-second^2 */
Definition at line 55 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_RADIAN
#define IGTL_UNIT_SI_DERIVED_RADIAN 0x08 /* radian meter/meter */
Definition at line 51 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_SIEMENS
#define IGTL_UNIT_SI_DERIVED_SIEMENS 0x13 /* siemens second^3-ampere^2/meter^2-kilogram */
Definition at line 62 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_SIEVERT
#define IGTL_UNIT_SI_DERIVED_SIEVERT 0x1B /* sievert meter^2/second^2 */
Definition at line 70 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_STERADIAN
#define IGTL_UNIT_SI_DERIVED_STERADIAN 0x09 /* steradian meter^2/meter^2 */
Definition at line 52 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_TESLA
#define IGTL_UNIT_SI_DERIVED_TESLA 0x15 /* tesla kilogram/second^2-ampere */
Definition at line 64 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_VOLT
#define IGTL_UNIT_SI_DERIVED_VOLT 0x10 /* volt meter^2-kilogram/second^3-ampere */
Definition at line 59 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_WATT
#define IGTL_UNIT_SI_DERIVED_WATT 0x0E /* watt meter^2-kilogram/second^3 */
Definition at line 57 of file igtl_unit.h.
IGTL_UNIT_SI_DERIVED_WEBER
#define IGTL_UNIT_SI_DERIVED_WEBER 0x14 /* weber meter^2-kilogram/second^2-ampere */
Definition at line 63 of file igtl_unit.h.
Typedef Documentation
igtl_unit
typedef igtl_uint64 igtl_unit
Definition at line 72 of file igtl_unit.h.
Function Documentation
igtl_unit_init()
void igtl_export igtl_unit_init (igtl_unit_data * data)
Definition at line 22 of file igtl_unit.c.
References igtl_unit_data::exp, igtl_export, igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::Unit::Pack().
igtl_unit_pack()
igtl_unit igtl_export igtl_unit_pack (igtl_unit_data * data)
Definition at line 36 of file igtl_unit.c.
References igtl_unit_data::exp, igtl_export, igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::Unit::Pack().
igtl_unit_unpack()
int igtl_export igtl_unit_unpack (igtl_unit pack, igtl_unit_data * data)
Definition at line 67 of file igtl_unit.c.
References igtl_unit_data::exp, igtl_export, igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::Unit::Unpack().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012