igtl_ndarray.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_ndarray.c File Reference
#include <stdlib.h>
#include <string.h>
#include "igtl_ndarray.h"
#include "igtl_util.h"
Functions
int igtl_export igtl_ndarray_alloc_info (igtl_ndarray_info *info, const igtl_uint16 *size)
int igtl_export igtl_ndarray_free_info (igtl_ndarray_info *info)
igtl_uint64 igtl_export igtl_ndarray_get_crc (igtl_ndarray_info *info, int type, void *data)
igtl_uint32 igtl_ndarray_get_nbyte (int type)
igtl_uint64 igtl_export igtl_ndarray_get_size (igtl_ndarray_info *info, int type)
void igtl_export igtl_ndarray_init_info (igtl_ndarray_info *info)
int igtl_export igtl_ndarray_pack (igtl_ndarray_info *info, void *byte_array, int type)
int igtl_export igtl_ndarray_unpack (int type, void *byte_array, igtl_ndarray_info *info, igtl_uint64 pack_size)
Function Documentation
igtl_ndarray_alloc_info()
int igtl_export igtl_ndarray_alloc_info (igtl_ndarray_info * info, const igtl_uint16 * size)
Allocates size array and ND-array pointed from igtl_ndarray_info. 'type' and 'dim' in igtl_ndarray_info must be specified before calling igtl_ndarray_alloc_info().
For example: Given info->type = 10 (i.e. 4 bytes), info->dim = 2 and size[dim] = {2, 3}, the amount of memory allocated is 2 * 3 * 4 = 24 bytes.
Definition at line 66 of file igtl_ndarray.c.
References igtl_ndarray_info::array, igtl_ndarray_info::dim, igtl_export, igtl_ndarray_get_nbyte(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl_ndarray_unpack(), and igtl::NDArrayMessage::PackContent().
igtl_ndarray_free_info()
int igtl_export igtl_ndarray_free_info (igtl_ndarray_info * info)
Frees ndarray
Definition at line 103 of file igtl_ndarray.c.
References igtl_ndarray_info::array, igtl_export, and igtl_ndarray_info::size.
igtl_ndarray_get_crc()
igtl_uint64 igtl_export igtl_ndarray_get_crc (igtl_ndarray_info * info, int type, void * byte_array)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 374 of file igtl_ndarray.c.
References crc64(), igtl_export, and igtl_ndarray_get_size().
igtl_ndarray_get_nbyte()
igtl_uint32 igtl_ndarray_get_nbyte (int type)
Definition at line 32 of file igtl_ndarray.c.
References IGTL_NDARRAY_STYPE_TYPE_COMPLEX, IGTL_NDARRAY_STYPE_TYPE_FLOAT32, IGTL_NDARRAY_STYPE_TYPE_FLOAT64, IGTL_NDARRAY_STYPE_TYPE_INT16, IGTL_NDARRAY_STYPE_TYPE_INT32, IGTL_NDARRAY_STYPE_TYPE_INT8, IGTL_NDARRAY_STYPE_TYPE_UINT16, IGTL_NDARRAY_STYPE_TYPE_UINT32, and IGTL_NDARRAY_STYPE_TYPE_UINT8.
Referenced by igtl_ndarray_alloc_info(), igtl_ndarray_get_size(), igtl_ndarray_pack(), and igtl_ndarray_unpack().
igtl_ndarray_get_size()
igtl_uint64 igtl_export igtl_ndarray_get_size (igtl_ndarray_info * info, int type)
Calculates size of N-D array body including size table (defined by UINT16[dim]) and array data.
Definition at line 352 of file igtl_ndarray.c.
References igtl_ndarray_info::dim, igtl_export, igtl_ndarray_get_nbyte(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl_ndarray_get_crc().
igtl_ndarray_init_info()
void igtl_export igtl_ndarray_init_info (igtl_ndarray_info * info)
Initializes igtl_ndarray_info
Definition at line 22 of file igtl_ndarray.c.
References igtl_ndarray_info::array, igtl_ndarray_info::dim, igtl_export, igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl_ndarray_unpack(), and igtl::NDArrayMessage::PackContent().
igtl_ndarray_pack()
int igtl_export igtl_ndarray_pack (igtl_ndarray_info * info, void * byte_array, int type)
Converts an igtl_ndarray_info structure to a byte array. 'byte_array' should be allocated prior to calling igtl_ndarray_pack() with memory size calculated by igtl_ndarray_get_size(). 'type' argument specifies a message type prefix (none, or GET_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 241 of file igtl_ndarray.c.
References igtl_ndarray_info::array, BYTE_SWAP_INT16, BYTE_SWAP_INT32, BYTE_SWAP_INT64, igtl_ndarray_info::dim, igtl_export, igtl_is_little_endian(), igtl_ndarray_get_nbyte(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl::NDArrayMessage::PackContent().
igtl_ndarray_unpack()
int igtl_export igtl_ndarray_unpack (int type, void * byte_array, igtl_ndarray_info * info, igtl_uint64 pack_size)
Unpacks and extracts information in a byte array of NDARRAY messages and store it in a igtl_ndarray_info structure. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 118 of file igtl_ndarray.c.
References igtl_ndarray_info::array, BYTE_SWAP_INT16, BYTE_SWAP_INT32, BYTE_SWAP_INT64, igtl_ndarray_info::dim, igtl_export, igtl_is_little_endian(), igtl_ndarray_alloc_info(), igtl_ndarray_get_nbyte(), igtl_ndarray_init_info(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl::NDArrayMessage::UnpackContent().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012