igtl_trajectory.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_trajectory.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_trajectory.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_trajectory_convert_byte_order (igtl_trajectory_element *trajectorylist, int nitem)
igtl_uint64 igtl_export igtl_trajectory_get_crc (igtl_trajectory_element *trajectorylist, int nitem)
Function Documentation
igtl_trajectory_convert_byte_order()
void igtl_export igtl_trajectory_convert_byte_order (igtl_trajectory_element * trajectorylist, int nelem)
Converts endianness of each element in an array of igtl_igtl_trajectory_element from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_trajectory.c.
References BYTE_SWAP_INT32, igtl_trajectory_element::entry_pos, igtl_export, igtl_is_little_endian(), igtl_trajectory_element::radius, and igtl_trajectory_element::target_pos.
Referenced by igtl::TrajectoryMessage::PackContent(), and igtl::TrajectoryMessage::UnpackContent().
igtl_trajectory_get_crc()
igtl_uint64 igtl_export igtl_trajectory_get_crc (igtl_trajectory_element * trajectorylist, int nelem)
Calculates CRC of trajectory message
Definition at line 47 of file igtl_trajectory.c.
References crc64(), igtl_export, and IGTL_TRAJECTORY_ELEMENT_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012