igtl_tdata.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_tdata.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_rts_tdata
struct igtl_stt_tdata
struct igtl_tdata_element
Macros
#define IGTL_RTS_TDATA_SIZE 1
#define IGTL_STT_TDATA_LEN_COORDNAME 32 /* Maximum length of coordinate system name */
#define IGTL_STT_TDATA_SIZE 36
#define IGTL_TDATA_ELEMENT_SIZE 70
#define igtl_tdata_get_data_n(size)
#define igtl_tdata_get_data_size(n)
#define IGTL_TDATA_LEN_NAME 20 /* Maximum length of tracking instrument name */
#define IGTL_TDATA_TYPE_3D 3 /* 3D instrument (only tip of the instrument defined) */
#define IGTL_TDATA_TYPE_5D
#define IGTL_TDATA_TYPE_6D 2 /* 6D instrument (regular instrument) */
#define IGTL_TDATA_TYPE_TRACKER 1 /* Tracker */
Functions
void igtl_export igtl_rts_tdata_convert_byte_order (igtl_rts_tdata *rts_tdata)
igtl_uint64 igtl_export igtl_rts_tdata_get_crc (igtl_rts_tdata *rts_tdata)
void igtl_export igtl_stt_tdata_convert_byte_order (igtl_stt_tdata *stt_tdata)
igtl_uint64 igtl_export igtl_stt_tdata_get_crc (igtl_stt_tdata *stt_tdata)
void igtl_export igtl_tdata_convert_byte_order (igtl_tdata_element *tdatalist, int nelem)
igtl_uint64 igtl_export igtl_tdata_get_crc (igtl_tdata_element *tdatalist, int nelem)
Macro Definition Documentation
IGTL_RTS_TDATA_SIZE
#define IGTL_RTS_TDATA_SIZE 1
Definition at line 24 of file igtl_tdata.h.
Referenced by igtl::RTSTrackingDataMessage::CalculateContentBufferSize(), and igtl_rts_tdata_get_crc().
IGTL_STT_TDATA_LEN_COORDNAME
#define IGTL_STT_TDATA_LEN_COORDNAME 32 /* Maximum length of coordinate system name */
Definition at line 27 of file igtl_tdata.h.
Referenced by igtl::StartTrackingDataMessage::PackContent(), igtl::StartTrackingDataMessage::SetCoordinateName(), and igtl::StartTrackingDataMessage::UnpackContent().
IGTL_STT_TDATA_SIZE
#define IGTL_STT_TDATA_SIZE 36
Definition at line 23 of file igtl_tdata.h.
Referenced by igtl::StartTrackingDataMessage::CalculateContentBufferSize(), and igtl_stt_tdata_get_crc().
IGTL_TDATA_ELEMENT_SIZE
#define IGTL_TDATA_ELEMENT_SIZE 70
Definition at line 22 of file igtl_tdata.h.
Referenced by igtl::TrackingDataMessage::CalculateContentBufferSize(), and igtl_tdata_get_crc().
igtl_tdata_get_data_n
#define igtl_tdata_get_data_n (size)
Value:
((size) / IGTL_TDATA_ELEMENT_SIZE)
igtl_tdata_get_data_n(size) calculates the number of tdatas in the body, based on the body size. This function may be used when a client program parses a TDATA message.
Definition at line 68 of file igtl_tdata.h.
Referenced by igtl::TrackingDataMessage::UnpackContent().
igtl_tdata_get_data_size
#define igtl_tdata_get_data_size (n)
Value:
((n) * IGTL_TDATA_ELEMENT_SIZE)
igtl_tdata_get_data_size(n) calculates the size of body based on the number of tdatas. The size of body is used in the message header.
Definition at line 64 of file igtl_tdata.h.
IGTL_TDATA_LEN_NAME
#define IGTL_TDATA_LEN_NAME 20 /* Maximum length of tracking instrument name */
Definition at line 26 of file igtl_tdata.h.
Referenced by igtl::TrackingDataMessage::PackContent(), igtl::TrackingDataElement::SetName(), and igtl::TrackingDataMessage::UnpackContent().
IGTL_TDATA_TYPE_3D
#define IGTL_TDATA_TYPE_3D 3 /* 3D instrument (only tip of the instrument defined) */
Definition at line 31 of file igtl_tdata.h.
IGTL_TDATA_TYPE_5D
#define IGTL_TDATA_TYPE_5D
Value:
                                                 4  /* 5D instrument (tip and handle are defined,
                                                 but not the normal vector) */
Definition at line 32 of file igtl_tdata.h.
IGTL_TDATA_TYPE_6D
#define IGTL_TDATA_TYPE_6D 2 /* 6D instrument (regular instrument) */
Definition at line 30 of file igtl_tdata.h.
IGTL_TDATA_TYPE_TRACKER
#define IGTL_TDATA_TYPE_TRACKER 1 /* Tracker */
Definition at line 29 of file igtl_tdata.h.
Function Documentation
igtl_rts_tdata_convert_byte_order()
void igtl_export igtl_rts_tdata_convert_byte_order (igtl_rts_tdata * rts_tdata)
Definition at line 55 of file igtl_tdata.c.
References igtl_export.
Referenced by igtl::RTSTrackingDataMessage::PackContent(), and igtl::RTSTrackingDataMessage::UnpackContent().
igtl_rts_tdata_get_crc()
igtl_uint64 igtl_export igtl_rts_tdata_get_crc (igtl_rts_tdata * rts_tdata)
Definition at line 88 of file igtl_tdata.c.
References crc64(), igtl_export, and IGTL_RTS_TDATA_SIZE.
igtl_stt_tdata_convert_byte_order()
void igtl_export igtl_stt_tdata_convert_byte_order (igtl_stt_tdata * stt_tdata)
Definition at line 43 of file igtl_tdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_stt_tdata::resolution.
Referenced by igtl::StartTrackingDataMessage::PackContent(), and igtl::StartTrackingDataMessage::UnpackContent().
igtl_stt_tdata_get_crc()
igtl_uint64 igtl_export igtl_stt_tdata_get_crc (igtl_stt_tdata * stt_tdata)
Definition at line 78 of file igtl_tdata.c.
References crc64(), igtl_export, and IGTL_STT_TDATA_SIZE.
igtl_tdata_convert_byte_order()
void igtl_export igtl_tdata_convert_byte_order (igtl_tdata_element * tdatalist, int nelem)
Converts endianness of each element in an array of igtl_tdata_element from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_tdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_tdata_element::transform.
Referenced by igtl::TrackingDataMessage::PackContent(), and igtl::TrackingDataMessage::UnpackContent().
igtl_tdata_get_crc()
igtl_uint64 igtl_export igtl_tdata_get_crc (igtl_tdata_element * tdatalist, int nelem)
Calculates CRC of TDATA, STT_TDATA and RTS_TDATA messages.
Definition at line 61 of file igtl_tdata.c.
References crc64(), igtl_export, and IGTL_TDATA_ELEMENT_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012