igtl_image.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_image.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_image.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_image_convert_byte_order (igtl_image_header *header)
igtl_uint64 igtl_export igtl_image_get_crc (igtl_image_header *header, void *image)
igtl_uint64 igtl_export igtl_image_get_data_size (igtl_image_header *header)
void igtl_export igtl_image_get_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_image_header *header)
void igtl_export igtl_image_get_matrix_4x4 (float _matrix[4][4], igtl_image_header *header)
void igtl_export igtl_image_set_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_image_header *header)
void igtl_export igtl_image_set_matrix_4x4 (float _matrix[4][4], igtl_image_header *header)
Function Documentation
igtl_image_convert_byte_order()
void igtl_export igtl_image_convert_byte_order (igtl_image_header * header)
Converts endianness of each member variable in igtl_image_header from host byte order to network byte order, or vice versa.
Definition at line 174 of file igtl_image.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, igtl_image_header::header_version, igtl_export, igtl_is_little_endian(), igtl_image_header::matrix, igtl_image_header::size, igtl_image_header::subvol_offset, and igtl_image_header::subvol_size.
Referenced by igtl::ImageMessage2::PackContent(), igtl::ImageMessage::PackContent(), igtl::ImageMessage2::UnpackContent(), and igtl::ImageMessage::UnpackContent().
igtl_image_get_crc()
igtl_uint64 igtl_export igtl_image_get_crc (igtl_image_header * header, void * image)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 209 of file igtl_image.c.
References BYTE_SWAP_INT16, crc64(), igtl_export, IGTL_IMAGE_HEADER_SIZE, IGTL_IMAGE_STYPE_TYPE_INT16, IGTL_IMAGE_STYPE_TYPE_INT32, IGTL_IMAGE_STYPE_TYPE_INT8, IGTL_IMAGE_STYPE_TYPE_UINT16, IGTL_IMAGE_STYPE_TYPE_UINT32, IGTL_IMAGE_STYPE_TYPE_UINT8, igtl_is_little_endian(), igtl_image_header::scalar_type, and igtl_image_header::subvol_size.
igtl_image_get_data_size()
igtl_uint64 igtl_export igtl_image_get_data_size (igtl_image_header * header)
Calculates size of the pixel array, which will be transferred with the specified header.
Definition at line 21 of file igtl_image.c.
References igtl_export, IGTL_IMAGE_STYPE_TYPE_INT16, IGTL_IMAGE_STYPE_TYPE_INT32, IGTL_IMAGE_STYPE_TYPE_INT8, IGTL_IMAGE_STYPE_TYPE_UINT16, IGTL_IMAGE_STYPE_TYPE_UINT32, IGTL_IMAGE_STYPE_TYPE_UINT8, igtl_image_header::scalar_type, and igtl_image_header::subvol_size.
igtl_image_get_matrix()
void igtl_export igtl_image_get_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_image_header * header)
Definition at line 91 of file igtl_image.c.
References igtl_export, and igtl_image_header::matrix.
Referenced by igtl::ImageMessage2::UnpackContent(), and igtl::ImageMessage::UnpackContent().
igtl_image_get_matrix_4x4()
void igtl_export igtl_image_get_matrix_4x4 (float _matrix[4][4], igtl_image_header * header)
Gets the image orientation/origin matrix in 4x4 format
Definition at line 151 of file igtl_image.c.
References igtl_export, and igtl_image_header::matrix.
igtl_image_set_matrix()
void igtl_export igtl_image_set_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_image_header * header)
Generates image orientation/origin matrix from spacing, origin and normal vectors.
Definition at line 57 of file igtl_image.c.
References igtl_export, and igtl_image_header::matrix.
Referenced by igtl::ImageMessage2::PackContent(), and igtl::ImageMessage::PackContent().
igtl_image_set_matrix_4x4()
void igtl_export igtl_image_set_matrix_4x4 (float _matrix[4][4], igtl_image_header * header)
Sets the image orientation/origin matrix in 4x4 format
Definition at line 75 of file igtl_image.c.
References igtl_export, and igtl_image_header::matrix.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012