igtl_command.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_command.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_command_header
Macros
#define IGTL_COMMAND_HEADER_SIZE 138
#define IGTL_COMMAND_NAME_SIZE 128
Functions
void igtl_export igtl_command_convert_byte_order (igtl_command_header *header)
igtl_uint64 igtl_export igtl_command_get_crc (igtl_command_header *header, void *command)
Macro Definition Documentation
IGTL_COMMAND_HEADER_SIZE
#define IGTL_COMMAND_HEADER_SIZE 138
Definition at line 23 of file igtl_command.h.
Referenced by igtl_command_get_crc().
IGTL_COMMAND_NAME_SIZE
#define IGTL_COMMAND_NAME_SIZE 128
Definition at line 24 of file igtl_command.h.
Referenced by igtl::CommandMessage::CommandMessage(), igtl::CommandMessage::PackContent(), igtl::RTSCommandMessage::SetCommandErrorString(), igtl::RTSCommandMessage::SetCommandErrorString(), igtl::CommandMessage::SetCommandName(), and igtl::CommandMessage::UnpackContent().
Function Documentation
igtl_command_convert_byte_order()
void igtl_export igtl_command_convert_byte_order (igtl_command_header * header)
Converts endian-ness from host byte order to network byte order, or vice versa. NOTE: It is developer's responsibility to have the command body with BOM (byte order mark) or in big endian order.
Definition at line 22 of file igtl_command.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, igtl_command_header::commandId, igtl_command_header::encoding, igtl_export, igtl_is_little_endian(), and igtl_command_header::length.
Referenced by igtl_command_get_crc(), igtl::CommandMessage::PackContent(), and igtl::CommandMessage::UnpackContent().
igtl_command_get_crc()
igtl_uint64 igtl_export igtl_command_get_crc (igtl_command_header * header, void * command)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 34 of file igtl_command.c.
References crc64(), igtl_command_convert_byte_order(), IGTL_COMMAND_HEADER_SIZE, igtl_export, and igtl_command_header::length.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012