igtl_tdata.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_tdata.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_tdata.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_rts_tdata_convert_byte_order (igtl_rts_tdata *rts_tdata)
igtl_uint64 igtl_export igtl_rts_tdata_get_crc (igtl_rts_tdata *rts_tdata)
void igtl_export igtl_stt_tdata_convert_byte_order (igtl_stt_tdata *stt_tdata)
igtl_uint64 igtl_export igtl_stt_tdata_get_crc (igtl_stt_tdata *stt_tdata)
void igtl_export igtl_tdata_convert_byte_order (igtl_tdata_element *tdatalist, int nitem)
igtl_uint64 igtl_export igtl_tdata_get_crc (igtl_tdata_element *tdatalist, int nitem)
Function Documentation
igtl_rts_tdata_convert_byte_order()
void igtl_export igtl_rts_tdata_convert_byte_order (igtl_rts_tdata * rts_tdata)
Definition at line 55 of file igtl_tdata.c.
References igtl_export.
Referenced by igtl::RTSTrackingDataMessage::PackContent(), and igtl::RTSTrackingDataMessage::UnpackContent().
igtl_rts_tdata_get_crc()
igtl_uint64 igtl_export igtl_rts_tdata_get_crc (igtl_rts_tdata * rts_tdata)
Definition at line 88 of file igtl_tdata.c.
References crc64(), igtl_export, and IGTL_RTS_TDATA_SIZE.
igtl_stt_tdata_convert_byte_order()
void igtl_export igtl_stt_tdata_convert_byte_order (igtl_stt_tdata * stt_tdata)
Definition at line 43 of file igtl_tdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_stt_tdata::resolution.
Referenced by igtl::StartTrackingDataMessage::PackContent(), and igtl::StartTrackingDataMessage::UnpackContent().
igtl_stt_tdata_get_crc()
igtl_uint64 igtl_export igtl_stt_tdata_get_crc (igtl_stt_tdata * stt_tdata)
Definition at line 78 of file igtl_tdata.c.
References crc64(), igtl_export, and IGTL_STT_TDATA_SIZE.
igtl_tdata_convert_byte_order()
void igtl_export igtl_tdata_convert_byte_order (igtl_tdata_element * tdatalist, int nelem)
Converts endianness of each element in an array of igtl_tdata_element from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_tdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_tdata_element::transform.
Referenced by igtl::TrackingDataMessage::PackContent(), and igtl::TrackingDataMessage::UnpackContent().
igtl_tdata_get_crc()
igtl_uint64 igtl_export igtl_tdata_get_crc (igtl_tdata_element * tdatalist, int nelem)
Calculates CRC of TDATA, STT_TDATA and RTS_TDATA messages.
Definition at line 61 of file igtl_tdata.c.
References crc64(), igtl_export, and IGTL_TDATA_ELEMENT_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012