igtl_unit.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_unit.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_unit.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_unit_init (igtl_unit_data *data)
igtl_unit igtl_export igtl_unit_pack (igtl_unit_data *data)
int igtl_export igtl_unit_unpack (igtl_unit pack, igtl_unit_data *data)
Function Documentation
igtl_unit_init()
void igtl_export igtl_unit_init (igtl_unit_data * data)
Definition at line 22 of file igtl_unit.c.
References igtl_unit_data::exp, igtl_export, igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::Unit::Pack().
igtl_unit_pack()
igtl_unit igtl_export igtl_unit_pack (igtl_unit_data * data)
Definition at line 36 of file igtl_unit.c.
References igtl_unit_data::exp, igtl_export, igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::Unit::Pack().
igtl_unit_unpack()
int igtl_export igtl_unit_unpack (igtl_unit pack, igtl_unit_data * data)
Definition at line 67 of file igtl_unit.c.
References igtl_unit_data::exp, igtl_export, igtl_unit_data::prefix, and igtl_unit_data::unit.
Referenced by igtl::Unit::Unpack().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012