igtl_video.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_video.c File Reference
#include <string.h>
#include <math.h>
#include "igtl_video.h"
#include "igtl_util.h"
Functions
void igtl_export igtl_frame_convert_byte_order (igtl_frame_header *header)
void igtl_export igtl_frame_get_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_frame_header *header)
void igtl_export igtl_frame_get_matrix_4x4 (float _matrix[4][4], igtl_frame_header *header)
void igtl_export igtl_frame_set_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_frame_header *header)
void igtl_export igtl_frame_set_matrix_4x4 (float _matrix[4][4], igtl_frame_header *header)
void igtl_export igtl_stt_video_convert_byte_order (igtl_stt_video *stt_video)
igtl_uint64 igtl_export igtl_stt_video_get_crc (igtl_stt_video *stt_video)
Function Documentation
igtl_frame_convert_byte_order()
void igtl_export igtl_frame_convert_byte_order (igtl_frame_header * header)
Definition at line 42 of file igtl_video.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, igtl_frame_header::frameType, igtl_frame_header::header_version, igtl_export, igtl_is_little_endian(), igtl_frame_header::matrix, igtl_frame_header::size, igtl_frame_header::subvol_offset, and igtl_frame_header::subvol_size.
Referenced by igtl::VideoMessage::PackContent(), and igtl::VideoMessage::UnpackContent().
igtl_frame_get_matrix()
void igtl_export igtl_frame_get_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_frame_header * header)
Definition at line 102 of file igtl_video.c.
References igtl_export, and igtl_frame_header::matrix.
Referenced by igtl::VideoMessage::UnpackContent().
igtl_frame_get_matrix_4x4()
void igtl_export igtl_frame_get_matrix_4x4 (float _matrix[4][4], igtl_frame_header * header)
Definition at line 161 of file igtl_video.c.
References igtl_export, and igtl_frame_header::matrix.
igtl_frame_set_matrix()
void igtl_export igtl_frame_set_matrix (float spacing[3], float origin[3], float norm_i[3], float norm_j[3], float norm_k[3], igtl_frame_header * header)
Definition at line 68 of file igtl_video.c.
References igtl_export, and igtl_frame_header::matrix.
Referenced by igtl::VideoMessage::PackContent().
igtl_frame_set_matrix_4x4()
void igtl_export igtl_frame_set_matrix_4x4 (float _matrix[4][4], igtl_frame_header * header)
Definition at line 86 of file igtl_video.c.
References igtl_export, and igtl_frame_header::matrix.
igtl_stt_video_convert_byte_order()
void igtl_export igtl_stt_video_convert_byte_order (igtl_stt_video * stt_video)
Converts endianness of each element in an array of or vice versa.
Definition at line 21 of file igtl_video.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_stt_video::time_interval.
Referenced by igtl::StartVideoMessage::PackContent(), and igtl::StartVideoMessage::UnpackContent().
igtl_stt_video_get_crc()
igtl_uint64 igtl_export igtl_stt_video_get_crc (igtl_stt_video * stt_video)
Calculates, STT_VIDEO messages.
Definition at line 33 of file igtl_video.c.
References crc64(), igtl_export, and IGTL_STT_VIDEO_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012