igtl_qtdata.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_qtdata.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_qtdata_element
struct igtl_rts_qtdata
struct igtl_stt_qtdata
Macros
#define IGTL_QTDATA_ELEMENT_SIZE 50
#define igtl_qtdata_get_data_n(size)
#define igtl_qtdata_get_data_size(n)
#define IGTL_QTDATA_LEN_NAME 20 /* Maximum length of tracking instrument name */
#define IGTL_QTDATA_TYPE_3D 3 /* 3D instrument (only tip of the instrument defined) */
#define IGTL_QTDATA_TYPE_5D
#define IGTL_QTDATA_TYPE_6D 2 /* 6D instrument (regular instrument) */
#define IGTL_QTDATA_TYPE_TRACKER 1 /* Tracker */
#define IGTL_RTS_QTDATA_SIZE 1
#define IGTL_STT_QTDATA_LEN_COORDNAME 32 /* Maximum length of coordinate system name */
#define IGTL_STT_QTDATA_SIZE 36
Functions
void igtl_export igtl_qtdata_convert_byte_order (igtl_qtdata_element *qtdatalist, int nelem)
igtl_uint64 igtl_export igtl_qtdata_get_crc (igtl_qtdata_element *qtdatalist, int nelem)
void igtl_export igtl_rts_qtdata_convert_byte_order (igtl_rts_qtdata *rts_qtdata)
igtl_uint64 igtl_export igtl_rts_qtdata_get_crc (igtl_rts_qtdata *rts_qtdata)
void igtl_export igtl_stt_qtdata_convert_byte_order (igtl_stt_qtdata *stt_qtdata)
igtl_uint64 igtl_export igtl_stt_qtdata_get_crc (igtl_stt_qtdata *stt_qtdata)
Macro Definition Documentation
IGTL_QTDATA_ELEMENT_SIZE
#define IGTL_QTDATA_ELEMENT_SIZE 50
Definition at line 22 of file igtl_qtdata.h.
Referenced by igtl::QuaternionTrackingDataMessage::CalculateContentBufferSize(), and igtl_qtdata_get_crc().
igtl_qtdata_get_data_n
#define igtl_qtdata_get_data_n (size)
Value:
((size) / IGTL_QTDATA_ELEMENT_SIZE)
igtl_qtdata_get_data_n(size) calculates the number of qtdatas in the body, based on the body size. This function may be used when a client program parses a QTDATA message.
Definition at line 69 of file igtl_qtdata.h.
Referenced by igtl::QuaternionTrackingDataMessage::UnpackContent().
igtl_qtdata_get_data_size
#define igtl_qtdata_get_data_size (n)
Value:
((n) * IGTL_QTDATA_ELEMENT_SIZE)
igtl_qtdata_get_data_size(n) calculates the size of body based on the number of qtdatas. The size of body is used in the message header.
Definition at line 65 of file igtl_qtdata.h.
IGTL_QTDATA_LEN_NAME
#define IGTL_QTDATA_LEN_NAME 20 /* Maximum length of tracking instrument name */
Definition at line 26 of file igtl_qtdata.h.
Referenced by igtl::QuaternionTrackingDataMessage::PackContent(), igtl::QuaternionTrackingDataElement::SetName(), and igtl::QuaternionTrackingDataMessage::UnpackContent().
IGTL_QTDATA_TYPE_3D
#define IGTL_QTDATA_TYPE_3D 3 /* 3D instrument (only tip of the instrument defined) */
Definition at line 31 of file igtl_qtdata.h.
IGTL_QTDATA_TYPE_5D
#define IGTL_QTDATA_TYPE_5D
Value:
                                                  4  /* 5D instrument (tip and handle are defined,
                                                  but not the normal vector) */
Definition at line 32 of file igtl_qtdata.h.
IGTL_QTDATA_TYPE_6D
#define IGTL_QTDATA_TYPE_6D 2 /* 6D instrument (regular instrument) */
Definition at line 30 of file igtl_qtdata.h.
IGTL_QTDATA_TYPE_TRACKER
#define IGTL_QTDATA_TYPE_TRACKER 1 /* Tracker */
Definition at line 29 of file igtl_qtdata.h.
IGTL_RTS_QTDATA_SIZE
#define IGTL_RTS_QTDATA_SIZE 1
Definition at line 24 of file igtl_qtdata.h.
Referenced by igtl::RTSQuaternionTrackingDataMessage::CalculateContentBufferSize(), and igtl_rts_qtdata_get_crc().
IGTL_STT_QTDATA_LEN_COORDNAME
#define IGTL_STT_QTDATA_LEN_COORDNAME 32 /* Maximum length of coordinate system name */
Definition at line 27 of file igtl_qtdata.h.
Referenced by igtl::StartQuaternionTrackingDataMessage::PackContent(), igtl::StartQuaternionTrackingDataMessage::SetCoordinateName(), and igtl::StartQuaternionTrackingDataMessage::UnpackContent().
IGTL_STT_QTDATA_SIZE
#define IGTL_STT_QTDATA_SIZE 36
Definition at line 23 of file igtl_qtdata.h.
Referenced by igtl::StartQuaternionTrackingDataMessage::CalculateContentBufferSize(), and igtl_stt_qtdata_get_crc().
Function Documentation
igtl_qtdata_convert_byte_order()
void igtl_export igtl_qtdata_convert_byte_order (igtl_qtdata_element * qtdatalist, int nelem)
Byte order conversion for an array of QTDATA, STT_QTDATA and RTS_QTDATA data structure Converts endianness of each element in an array of igtl_qtdata_element from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_qtdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), igtl_qtdata_element::position, and igtl_qtdata_element::quaternion.
Referenced by igtl::QuaternionTrackingDataMessage::PackContent(), and igtl::QuaternionTrackingDataMessage::UnpackContent().
igtl_qtdata_get_crc()
igtl_uint64 igtl_export igtl_qtdata_get_crc (igtl_qtdata_element * qtdatalist, int nelem)
Calculates CRC of QTDATA, STT_QTDATA and RTS_QTDATA messages
Definition at line 67 of file igtl_qtdata.c.
References crc64(), igtl_export, and IGTL_QTDATA_ELEMENT_SIZE.
igtl_rts_qtdata_convert_byte_order()
void igtl_export igtl_rts_qtdata_convert_byte_order (igtl_rts_qtdata * rts_qtdata)
Definition at line 61 of file igtl_qtdata.c.
References igtl_export.
Referenced by igtl::RTSQuaternionTrackingDataMessage::PackContent(), and igtl::RTSQuaternionTrackingDataMessage::UnpackContent().
igtl_rts_qtdata_get_crc()
igtl_uint64 igtl_export igtl_rts_qtdata_get_crc (igtl_rts_qtdata * rts_qtdata)
Definition at line 94 of file igtl_qtdata.c.
References crc64(), igtl_export, and IGTL_RTS_QTDATA_SIZE.
igtl_stt_qtdata_convert_byte_order()
void igtl_export igtl_stt_qtdata_convert_byte_order (igtl_stt_qtdata * stt_qtdata)
Definition at line 49 of file igtl_qtdata.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_stt_qtdata::resolution.
Referenced by igtl::StartQuaternionTrackingDataMessage::PackContent(), and igtl::StartQuaternionTrackingDataMessage::UnpackContent().
igtl_stt_qtdata_get_crc()
igtl_uint64 igtl_export igtl_stt_qtdata_get_crc (igtl_stt_qtdata * stt_qtdata)
Definition at line 84 of file igtl_qtdata.c.
References crc64(), igtl_export, and IGTL_STT_QTDATA_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012