igtl_colortable.c File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_colortable.c File Reference
#include "igtl_util.h"
#include "igtl_colortable.h"
Functions
void igtl_export igtl_colortable_convert_byte_order (igtl_colortable_header *header, void *table)
igtl_uint64 igtl_export igtl_colortable_get_crc (igtl_colortable_header *header, void *table)
igtl_uint64 igtl_export igtl_colortable_get_table_size (igtl_colortable_header *header)
Function Documentation
igtl_colortable_convert_byte_order()
void igtl_export igtl_colortable_convert_byte_order (igtl_colortable_header * header, void * table)
Converts endianness of each element in an array of igtl_igtl_colortable_header and color table from host byte order to network byte order, or vice versa (if necessary). The function automatically determins the endian type of the host.
Definition at line 49 of file igtl_colortable.c.
References BYTE_SWAP_INT16, IGTL_COLORTABLE_INDEX_UINT16, IGTL_COLORTABLE_MAP_UINT16, igtl_export, igtl_is_little_endian(), igtl_colortable_header::indexType, and igtl_colortable_header::mapType.
Referenced by igtl::ColorTableMessage::PackContent(), and igtl::ColorTableMessage::UnpackContent().
igtl_colortable_get_crc()
igtl_uint64 igtl_export igtl_colortable_get_crc (igtl_colortable_header * header, void * table)
Calculates CRC of color table message
Definition at line 70 of file igtl_colortable.c.
References crc64(), igtl_colortable_get_table_size(), IGTL_COLORTABLE_HEADER_SIZE, and igtl_export.
igtl_colortable_get_table_size()
igtl_uint64 igtl_export igtl_colortable_get_table_size (igtl_colortable_header * header)
igtl_colortable_get_data_size(n) calculates the size of body based on the index and map types. The size of body is used in the message header. igtl_colortable_get_data_n(size) calculates the number of images in the body, based on the body size. This function may be used when a client program parses a COLORTABLE message.
Definition at line 18 of file igtl_colortable.c.
References IGTL_COLORTABLE_INDEX_UINT8, IGTL_COLORTABLE_MAP_UINT16, IGTL_COLORTABLE_MAP_UINT8, igtl_export, igtl_colortable_header::indexType, and igtl_colortable_header::mapType.
Referenced by igtl::ColorTableMessage::GetColorTableSize(), and igtl_colortable_get_crc().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012