igtl_status.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_status.h File Reference
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_status_header
Macros
#define IGTL_STATUS_ACCESS_DENIED 5
#define IGTL_STATUS_BUSY 6
#define IGTL_STATUS_CHECKSUM_ERROR 9 /* Checksum error */
#define IGTL_STATUS_CONFIG_ERROR 10 /* Configuration error */
#define IGTL_STATUS_DISABLED 15 /* Device disabled */
#define IGTL_STATUS_ERROR_NAME_LENGTH 20
#define IGTL_STATUS_HARDWARE_FAILURE 18 /* Hardware failure */
#define IGTL_STATUS_HEADER_SIZE 30
#define IGTL_STATUS_ILLEGAL_INSTRUCTION 12 /* Illegal/Unknown instruction */
#define IGTL_STATUS_INVALID 0
#define IGTL_STATUS_MANUAL_MODE 14 /* Manual mode (device does not accept commands) */
#define IGTL_STATUS_NOT_FOUND 4 /* file, configuration, device etc */
#define IGTL_STATUS_NOT_PRESENT 16 /* Device not present */
#define IGTL_STATUS_NOT_READY 13 /* Device not ready (starting up)*/
#define IGTL_STATUS_OK 1
#define IGTL_STATUS_OVERFLOW 8 /* Overflow / Can't be reached */
#define IGTL_STATUS_PANICK_MODE 3 /* emergency */
#define IGTL_STATUS_RESOURCE_ERROR 11 /* Not enough resource (memory, storage etc) */
#define IGTL_STATUS_SHUT_DOWN 19 /* Exiting / shut down in progress */
#define IGTL_STATUS_TIME_OUT 7 /* Time out / Connection lost */
#define IGTL_STATUS_UNKNOWN_ERROR 2
#define IGTL_STATUS_UNKNOWN_VERSION 17 /* Device version not known */
Functions
void igtl_export igtl_status_convert_byte_order (igtl_status_header *status)
igtl_uint64 igtl_export igtl_status_get_crc (igtl_status_header *status, igtl_uint32 msglen, const char *msg)
Macro Definition Documentation
IGTL_STATUS_ACCESS_DENIED
#define IGTL_STATUS_ACCESS_DENIED 5
Definition at line 32 of file igtl_status.h.
IGTL_STATUS_BUSY
#define IGTL_STATUS_BUSY 6
Definition at line 33 of file igtl_status.h.
IGTL_STATUS_CHECKSUM_ERROR
#define IGTL_STATUS_CHECKSUM_ERROR 9 /* Checksum error */
Definition at line 36 of file igtl_status.h.
IGTL_STATUS_CONFIG_ERROR
#define IGTL_STATUS_CONFIG_ERROR 10 /* Configuration error */
Definition at line 37 of file igtl_status.h.
IGTL_STATUS_DISABLED
#define IGTL_STATUS_DISABLED 15 /* Device disabled */
Definition at line 42 of file igtl_status.h.
IGTL_STATUS_ERROR_NAME_LENGTH
#define IGTL_STATUS_ERROR_NAME_LENGTH 20
Definition at line 23 of file igtl_status.h.
Referenced by igtl::StatusMessage::PackContent(), igtl::StatusMessage::SetErrorName(), and igtl::StatusMessage::UnpackContent().
IGTL_STATUS_HARDWARE_FAILURE
#define IGTL_STATUS_HARDWARE_FAILURE 18 /* Hardware failure */
Definition at line 45 of file igtl_status.h.
IGTL_STATUS_HEADER_SIZE
#define IGTL_STATUS_HEADER_SIZE 30
Definition at line 21 of file igtl_status.h.
Referenced by igtl::StatusMessage::CalculateContentBufferSize(), igtl_status_get_crc(), igtl::StatusMessage::PackContent(), and igtl::StatusMessage::UnpackContent().
IGTL_STATUS_ILLEGAL_INSTRUCTION
#define IGTL_STATUS_ILLEGAL_INSTRUCTION 12 /* Illegal/Unknown instruction */
Definition at line 39 of file igtl_status.h.
IGTL_STATUS_INVALID
#define IGTL_STATUS_INVALID 0
Definition at line 27 of file igtl_status.h.
IGTL_STATUS_MANUAL_MODE
#define IGTL_STATUS_MANUAL_MODE 14 /* Manual mode (device does not accept commands) */
Definition at line 41 of file igtl_status.h.
IGTL_STATUS_NOT_FOUND
#define IGTL_STATUS_NOT_FOUND 4 /* file, configuration, device etc */
Definition at line 31 of file igtl_status.h.
IGTL_STATUS_NOT_PRESENT
#define IGTL_STATUS_NOT_PRESENT 16 /* Device not present */
Definition at line 43 of file igtl_status.h.
IGTL_STATUS_NOT_READY
#define IGTL_STATUS_NOT_READY 13 /* Device not ready (starting up)*/
Definition at line 40 of file igtl_status.h.
IGTL_STATUS_OK
#define IGTL_STATUS_OK 1
Definition at line 28 of file igtl_status.h.
IGTL_STATUS_OVERFLOW
#define IGTL_STATUS_OVERFLOW 8 /* Overflow / Can't be reached */
Definition at line 35 of file igtl_status.h.
IGTL_STATUS_PANICK_MODE
#define IGTL_STATUS_PANICK_MODE 3 /* emergency */
Definition at line 30 of file igtl_status.h.
IGTL_STATUS_RESOURCE_ERROR
#define IGTL_STATUS_RESOURCE_ERROR 11 /* Not enough resource (memory, storage etc) */
Definition at line 38 of file igtl_status.h.
IGTL_STATUS_SHUT_DOWN
#define IGTL_STATUS_SHUT_DOWN 19 /* Exiting / shut down in progress */
Definition at line 46 of file igtl_status.h.
IGTL_STATUS_TIME_OUT
#define IGTL_STATUS_TIME_OUT 7 /* Time out / Connection lost */
Definition at line 34 of file igtl_status.h.
IGTL_STATUS_UNKNOWN_ERROR
#define IGTL_STATUS_UNKNOWN_ERROR 2
Definition at line 29 of file igtl_status.h.
IGTL_STATUS_UNKNOWN_VERSION
#define IGTL_STATUS_UNKNOWN_VERSION 17 /* Device version not known */
Definition at line 44 of file igtl_status.h.
Function Documentation
igtl_status_convert_byte_order()
void igtl_export igtl_status_convert_byte_order (igtl_status_header * status)
Converts endianness of each member variable in igtl_status_header from host byte order to network byte order, or vice versa.
Definition at line 21 of file igtl_status.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT64, igtl_status_header::code, igtl_export, igtl_is_little_endian(), and igtl_status_header::subcode.
Referenced by igtl::StatusMessage::PackContent(), and igtl::StatusMessage::UnpackContent().
igtl_status_get_crc()
igtl_uint64 igtl_export igtl_status_get_crc (igtl_status_header * status, igtl_uint32 msglen, const char * msg)
Calculates CRC of status data body including status message part
Definition at line 32 of file igtl_status.c.
References crc64(), igtl_export, and IGTL_STATUS_HEADER_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012