igtl_ndarray.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_ndarray.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_ndarray_info
Macros
#define IGTL_NDARRAY_HEADER_SIZE 2
#define IGTL_NDARRAY_HOST_TO_NETWORK 0
#define IGTL_NDARRAY_NETWORK_TO_HOST 1
#define IGTL_NDARRAY_STYPE_TYPE_COMPLEX 13
#define IGTL_NDARRAY_STYPE_TYPE_FLOAT32 10
#define IGTL_NDARRAY_STYPE_TYPE_FLOAT64 11
#define IGTL_NDARRAY_STYPE_TYPE_INT16 4
#define IGTL_NDARRAY_STYPE_TYPE_INT32 6
#define IGTL_NDARRAY_STYPE_TYPE_INT8 2
#define IGTL_NDARRAY_STYPE_TYPE_UINT16 5
#define IGTL_NDARRAY_STYPE_TYPE_UINT32 7
#define IGTL_NDARRAY_STYPE_TYPE_UINT8 3
Functions
int igtl_export igtl_ndarray_alloc_info (igtl_ndarray_info *info, const igtl_uint16 *size)
int igtl_export igtl_ndarray_free_info (igtl_ndarray_info *info)
igtl_uint64 igtl_export igtl_ndarray_get_crc (igtl_ndarray_info *info, int type, void *byte_array)
igtl_uint64 igtl_export igtl_ndarray_get_size (igtl_ndarray_info *info, int type)
void igtl_export igtl_ndarray_init_info (igtl_ndarray_info *info)
int igtl_export igtl_ndarray_pack (igtl_ndarray_info *info, void *byte_array, int type)
int igtl_export igtl_ndarray_unpack (int type, void *byte_array, igtl_ndarray_info *info, igtl_uint64 pack_size)
Macro Definition Documentation
IGTL_NDARRAY_HEADER_SIZE
#define IGTL_NDARRAY_HEADER_SIZE 2
Definition at line 23 of file igtl_ndarray.h.
IGTL_NDARRAY_HOST_TO_NETWORK
#define IGTL_NDARRAY_HOST_TO_NETWORK 0
Definition at line 36 of file igtl_ndarray.h.
IGTL_NDARRAY_NETWORK_TO_HOST
#define IGTL_NDARRAY_NETWORK_TO_HOST 1
Definition at line 37 of file igtl_ndarray.h.
IGTL_NDARRAY_STYPE_TYPE_COMPLEX
#define IGTL_NDARRAY_STYPE_TYPE_COMPLEX 13
Definition at line 34 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_FLOAT32
#define IGTL_NDARRAY_STYPE_TYPE_FLOAT32 10
Definition at line 32 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_FLOAT64
#define IGTL_NDARRAY_STYPE_TYPE_FLOAT64 11
Definition at line 33 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_INT16
#define IGTL_NDARRAY_STYPE_TYPE_INT16 4
Definition at line 28 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_INT32
#define IGTL_NDARRAY_STYPE_TYPE_INT32 6
Definition at line 30 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_INT8
#define IGTL_NDARRAY_STYPE_TYPE_INT8 2
Definition at line 26 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_UINT16
#define IGTL_NDARRAY_STYPE_TYPE_UINT16 5
Definition at line 29 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_UINT32
#define IGTL_NDARRAY_STYPE_TYPE_UINT32 7
Definition at line 31 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
IGTL_NDARRAY_STYPE_TYPE_UINT8
#define IGTL_NDARRAY_STYPE_TYPE_UINT8 3
Definition at line 27 of file igtl_ndarray.h.
Referenced by igtl_ndarray_get_nbyte().
Function Documentation
igtl_ndarray_alloc_info()
int igtl_export igtl_ndarray_alloc_info (igtl_ndarray_info * info, const igtl_uint16 * size)
Allocates size array and ND-array pointed from igtl_ndarray_info. 'type' and 'dim' in igtl_ndarray_info must be specified before calling igtl_ndarray_alloc_info().
For example: Given info->type = 10 (i.e. 4 bytes), info->dim = 2 and size[dim] = {2, 3}, the amount of memory allocated is 2 * 3 * 4 = 24 bytes.
Definition at line 66 of file igtl_ndarray.c.
References igtl_ndarray_info::array, igtl_ndarray_info::dim, igtl_export, igtl_ndarray_get_nbyte(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl_ndarray_unpack(), and igtl::NDArrayMessage::PackContent().
igtl_ndarray_free_info()
int igtl_export igtl_ndarray_free_info (igtl_ndarray_info * info)
Frees ndarray
Definition at line 103 of file igtl_ndarray.c.
References igtl_ndarray_info::array, igtl_export, and igtl_ndarray_info::size.
igtl_ndarray_get_crc()
igtl_uint64 igtl_export igtl_ndarray_get_crc (igtl_ndarray_info * info, int type, void * byte_array)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 374 of file igtl_ndarray.c.
References crc64(), igtl_export, and igtl_ndarray_get_size().
igtl_ndarray_get_size()
igtl_uint64 igtl_export igtl_ndarray_get_size (igtl_ndarray_info * info, int type)
Calculates size of N-D array body including size table (defined by UINT16[dim]) and array data.
Definition at line 352 of file igtl_ndarray.c.
References igtl_ndarray_info::dim, igtl_export, igtl_ndarray_get_nbyte(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl_ndarray_get_crc().
igtl_ndarray_init_info()
void igtl_export igtl_ndarray_init_info (igtl_ndarray_info * info)
Initializes igtl_ndarray_info
Definition at line 22 of file igtl_ndarray.c.
References igtl_ndarray_info::array, igtl_ndarray_info::dim, igtl_export, igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl_ndarray_unpack(), and igtl::NDArrayMessage::PackContent().
igtl_ndarray_pack()
int igtl_export igtl_ndarray_pack (igtl_ndarray_info * info, void * byte_array, int type)
Converts an igtl_ndarray_info structure to a byte array. 'byte_array' should be allocated prior to calling igtl_ndarray_pack() with memory size calculated by igtl_ndarray_get_size(). 'type' argument specifies a message type prefix (none, or GET_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 241 of file igtl_ndarray.c.
References igtl_ndarray_info::array, BYTE_SWAP_INT16, BYTE_SWAP_INT32, BYTE_SWAP_INT64, igtl_ndarray_info::dim, igtl_export, igtl_is_little_endian(), igtl_ndarray_get_nbyte(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl::NDArrayMessage::PackContent().
igtl_ndarray_unpack()
int igtl_export igtl_ndarray_unpack (int type, void * byte_array, igtl_ndarray_info * info, igtl_uint64 pack_size)
Unpacks and extracts information in a byte array of NDARRAY messages and store it in a igtl_ndarray_info structure. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 118 of file igtl_ndarray.c.
References igtl_ndarray_info::array, BYTE_SWAP_INT16, BYTE_SWAP_INT32, BYTE_SWAP_INT64, igtl_ndarray_info::dim, igtl_export, igtl_is_little_endian(), igtl_ndarray_alloc_info(), igtl_ndarray_get_nbyte(), igtl_ndarray_init_info(), igtl_ndarray_info::size, and igtl_ndarray_info::type.
Referenced by igtl::NDArrayMessage::UnpackContent().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012