igtl_query.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_query.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_query_header
Macros
#define IGTL_QUERY_DATE_TYPE_SIZE 32
#define IGTL_QUERY_HEADER_SIZE 38
Functions
void igtl_export igtl_query_convert_byte_order (igtl_query_header *header)
igtl_uint64 igtl_export igtl_query_get_crc (igtl_query_header *header, void *query)
Macro Definition Documentation
IGTL_QUERY_DATE_TYPE_SIZE
#define IGTL_QUERY_DATE_TYPE_SIZE 32
Definition at line 24 of file igtl_query.h.
Referenced by igtl::QueryMessage::PackContent(), igtl::QueryMessage::SetDataType(), and igtl::QueryMessage::UnpackContent().
IGTL_QUERY_HEADER_SIZE
#define IGTL_QUERY_HEADER_SIZE 38
Definition at line 23 of file igtl_query.h.
Referenced by igtl::QueryMessage::CalculateContentBufferSize(), and igtl_query_get_crc().
Function Documentation
igtl_query_convert_byte_order()
void igtl_export igtl_query_convert_byte_order (igtl_query_header * header)
Converts endian-ness from host byte order to network byte order, or vice versa. NOTE: It is developer's responsibility to have the command body with BOM (byte order mark) or in big endian order.
Definition at line 22 of file igtl_query.c.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, igtl_query_header::deviceUIDLength, igtl_export, igtl_is_little_endian(), and igtl_query_header::queryID.
Referenced by igtl_query_get_crc(), igtl::QueryMessage::PackContent(), and igtl::QueryMessage::UnpackContent().
igtl_query_get_crc()
igtl_uint64 igtl_export igtl_query_get_crc (igtl_query_header * header, void * query)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 33 of file igtl_query.c.
References crc64(), igtl_query_header::deviceUIDLength, igtl_export, igtl_query_convert_byte_order(), and IGTL_QUERY_HEADER_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012