igtl_capability.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_capability.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_capability_info
Macros
#define IGTL_CAPABILITY_HEADER_SIZE 4
Functions
int igtl_export igtl_capability_alloc_info (igtl_capability_info *info, int ntypes)
int igtl_export igtl_capability_free_info (igtl_capability_info *info)
igtl_uint64 igtl_export igtl_capability_get_crc (igtl_capability_info *info, void *capability)
igtl_uint32 igtl_export igtl_capability_get_length (igtl_capability_info *info)
void igtl_export igtl_capability_init_info (igtl_capability_info *info)
int igtl_export igtl_capability_pack (igtl_capability_info *info, void *byte_array)
int igtl_export igtl_capability_unpack (void *byte_array, igtl_capability_info *info, igtl_uint64 pack_size)
Macro Definition Documentation
IGTL_CAPABILITY_HEADER_SIZE
#define IGTL_CAPABILITY_HEADER_SIZE 4
Definition at line 23 of file igtl_capability.h.
Function Documentation
igtl_capability_alloc_info()
int igtl_export igtl_capability_alloc_info (igtl_capability_info * info, int ntypes)
Allocates ndarray info. Allocate size array and ND-array pointed from igtl_ndarray_info. 'type' and 'dim' in igtl_ndarray_info must be specified before calling igtl_ndarray_alloc_info().
Definition at line 32 of file igtl_capability.c.
References igtl_export, IGTL_HEADER_TYPE_SIZE, igtl_capability_info::ntypes, and igtl_capability_info::typenames.
Referenced by igtl_capability_unpack(), and igtl::CapabilityMessage::PackContent().
igtl_capability_free_info()
int igtl_export igtl_capability_free_info (igtl_capability_info * info)
Frees ndarray info.
Definition at line 69 of file igtl_capability.c.
References igtl_export, igtl_capability_info::ntypes, and igtl_capability_info::typenames.
Referenced by igtl_capability_unpack().
igtl_capability_get_crc()
igtl_uint64 igtl_export igtl_capability_get_crc (igtl_capability_info * info, void * capability)
Calculates CRC of image data body including header and array of pixel data.
Definition at line 168 of file igtl_capability.c.
References crc64(), igtl_capability_get_length(), and igtl_export.
igtl_capability_get_length()
igtl_uint32 igtl_export igtl_capability_get_length (igtl_capability_info * info)
Calculates capability data size of the pixel array, which will be transferred with the specified header.
Definition at line 90 of file igtl_capability.c.
References igtl_export, IGTL_HEADER_TYPE_SIZE, and igtl_capability_info::ntypes.
Referenced by igtl_capability_get_crc().
igtl_capability_init_info()
void igtl_export igtl_capability_init_info (igtl_capability_info * info)
Initializes igtl_ndarray_info
Definition at line 22 of file igtl_capability.c.
References igtl_export, igtl_capability_info::ntypes, and igtl_capability_info::typenames.
Referenced by igtl::CapabilityMessage::PackContent(), and igtl::CapabilityMessage::UnpackContent().
igtl_capability_pack()
int igtl_export igtl_capability_pack (igtl_capability_info * info, void * byte_array)
Packs CAPABILITY message. Converts an igtl_capability_info structure to a byte array. 'byte_array' should be allocated prior to calling igtl_capability_pack() with memory size calculated by igtl_capability_get_size(). 'type' argument specifies a message type prefix (none, or GET_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 141 of file igtl_capability.c.
References igtl_export, IGTL_HEADER_TYPE_SIZE, igtl_capability_info::ntypes, and igtl_capability_info::typenames.
Referenced by igtl::CapabilityMessage::PackContent().
igtl_capability_unpack()
int igtl_export igtl_capability_unpack (void * byte_array, igtl_capability_info * info, igtl_uint64 pack_size)
Unpacks CAPABILITY message. Extracts information in a byte array of CAPABILITY messages and store it in a igtl_capability_info structure. 'type' argument specifies a message type prefix (none, GET_, STT_, STP_ or RTS_) by IGTL_TYPE_PREFIX_* macro. Returns 1 if success, otherwise 0.
Definition at line 102 of file igtl_capability.c.
References igtl_capability_alloc_info(), igtl_capability_free_info(), igtl_export, IGTL_HEADER_TYPE_SIZE, igtl_capability_info::ntypes, and igtl_capability_info::typenames.
Referenced by igtl::CapabilityMessage::UnpackContent().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012