igtl_position.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_position.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_position
Macros
#define IGTL_POSITION_MESSAGE_DEFAULT_SIZE 28
#define IGTL_POSITION_MESSAGE_POSITON_ONLY_SIZE 12 /* size w/o quaternion */
#define IGTL_POSITION_MESSAGE_WITH_QUATERNION3_SIZE 24 /* size 3-element quaternion */
Functions
void igtl_export igtl_position_convert_byte_order (igtl_position *pos)
void igtl_export igtl_position_convert_byte_order_position_only (igtl_position *pos)
void igtl_export igtl_position_convert_byte_order_quaternion3 (igtl_position *pos)
igtl_uint64 igtl_export igtl_position_get_crc (igtl_position *pos)
Macro Definition Documentation
IGTL_POSITION_MESSAGE_DEFAULT_SIZE
#define IGTL_POSITION_MESSAGE_DEFAULT_SIZE 28
Definition at line 22 of file igtl_position.h.
Referenced by igtl::PositionMessage::CalculateContentBufferSize(), igtl_position_get_crc(), and igtl::PositionMessage::SetPackTypeByContentSize().
IGTL_POSITION_MESSAGE_POSITON_ONLY_SIZE
#define IGTL_POSITION_MESSAGE_POSITON_ONLY_SIZE 12 /* size w/o quaternion */
NOTE: the size varies if orientation is omitted
Definition at line 24 of file igtl_position.h.
Referenced by igtl::PositionMessage::CalculateContentBufferSize(), igtl::PositionMessage::SetPackTypeByContentSize(), and igtl::PositionMessage::UnpackContent().
IGTL_POSITION_MESSAGE_WITH_QUATERNION3_SIZE
#define IGTL_POSITION_MESSAGE_WITH_QUATERNION3_SIZE 24 /* size 3-element quaternion */
Definition at line 25 of file igtl_position.h.
Referenced by igtl::PositionMessage::CalculateContentBufferSize(), igtl::PositionMessage::SetPackTypeByContentSize(), and igtl::PositionMessage::UnpackContent().
Function Documentation
igtl_position_convert_byte_order()
void igtl_export igtl_position_convert_byte_order (igtl_position * pos)
Converts endianness of each member variable in igtl_status_header from host byte order to network byte order, or vice versa.
Definition at line 22 of file igtl_position.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), igtl_position::position, and igtl_position::quaternion.
Referenced by igtl::PositionMessage::PackContent(), and igtl::PositionMessage::UnpackContent().
igtl_position_convert_byte_order_position_only()
void igtl_export igtl_position_convert_byte_order_position_only (igtl_position * pos)
Definition at line 46 of file igtl_position.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), and igtl_position::position.
Referenced by igtl::PositionMessage::PackContent(), and igtl::PositionMessage::UnpackContent().
igtl_position_convert_byte_order_quaternion3()
void igtl_export igtl_position_convert_byte_order_quaternion3 (igtl_position * pos)
Definition at line 62 of file igtl_position.c.
References BYTE_SWAP_INT32, igtl_export, igtl_is_little_endian(), igtl_position::position, and igtl_position::quaternion.
Referenced by igtl::PositionMessage::PackContent(), and igtl::PositionMessage::UnpackContent().
igtl_position_get_crc()
igtl_uint64 igtl_export igtl_position_get_crc (igtl_position * pos)
Calculates CRC of position message
Definition at line 87 of file igtl_position.c.
References crc64(), igtl_export, and IGTL_POSITION_MESSAGE_DEFAULT_SIZE.
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012