igtl_colortable.h File Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl_colortable.h File Reference
#include "igtl_win32header.h"
#include "igtl_util.h"
#include "igtl_types.h"
Data Structures
struct igtl_colortable_header
Macros
#define IGTL_COLORTABLE_HEADER_SIZE 2
#define IGTL_COLORTABLE_INDEX_UINT16 5
#define IGTL_COLORTABLE_INDEX_UINT8 3
#define IGTL_COLORTABLE_MAP_RGB 19
#define IGTL_COLORTABLE_MAP_UINT16 5
#define IGTL_COLORTABLE_MAP_UINT8 3
Functions
void igtl_export igtl_colortable_convert_byte_order (igtl_colortable_header *header, void *table)
igtl_uint64 igtl_export igtl_colortable_get_crc (igtl_colortable_header *header, void *table)
igtl_uint64 igtl_export igtl_colortable_get_table_size (igtl_colortable_header *header)
Macro Definition Documentation
IGTL_COLORTABLE_HEADER_SIZE
#define IGTL_COLORTABLE_HEADER_SIZE 2
Definition at line 22 of file igtl_colortable.h.
Referenced by igtl::ColorTableMessage::AllocateTable(), igtl::ColorTableMessage::CalculateContentBufferSize(), igtl_colortable_get_crc(), and igtl::ColorTableMessage::UnpackContent().
IGTL_COLORTABLE_INDEX_UINT16
#define IGTL_COLORTABLE_INDEX_UINT16 5
Definition at line 25 of file igtl_colortable.h.
Referenced by igtl_colortable_convert_byte_order().
IGTL_COLORTABLE_INDEX_UINT8
#define IGTL_COLORTABLE_INDEX_UINT8 3
Definition at line 24 of file igtl_colortable.h.
Referenced by igtl_colortable_get_table_size().
IGTL_COLORTABLE_MAP_RGB
#define IGTL_COLORTABLE_MAP_RGB 19
Definition at line 28 of file igtl_colortable.h.
IGTL_COLORTABLE_MAP_UINT16
#define IGTL_COLORTABLE_MAP_UINT16 5
Definition at line 27 of file igtl_colortable.h.
Referenced by igtl_colortable_convert_byte_order(), and igtl_colortable_get_table_size().
IGTL_COLORTABLE_MAP_UINT8
#define IGTL_COLORTABLE_MAP_UINT8 3
Definition at line 26 of file igtl_colortable.h.
Referenced by igtl_colortable_get_table_size().
Function Documentation
igtl_colortable_convert_byte_order()
void igtl_export igtl_colortable_convert_byte_order (igtl_colortable_header * header, void * table)
Converts endianness of each element in an array of igtl_igtl_colortable_header and color table from host byte order to network byte order, or vice versa (if necessary). The function automatically determins the endian type of the host.
Definition at line 49 of file igtl_colortable.c.
References BYTE_SWAP_INT16, IGTL_COLORTABLE_INDEX_UINT16, IGTL_COLORTABLE_MAP_UINT16, igtl_export, igtl_is_little_endian(), igtl_colortable_header::indexType, and igtl_colortable_header::mapType.
Referenced by igtl::ColorTableMessage::PackContent(), and igtl::ColorTableMessage::UnpackContent().
igtl_colortable_get_crc()
igtl_uint64 igtl_export igtl_colortable_get_crc (igtl_colortable_header * header, void * table)
Calculates CRC of color table message
Definition at line 70 of file igtl_colortable.c.
References crc64(), igtl_colortable_get_table_size(), IGTL_COLORTABLE_HEADER_SIZE, and igtl_export.
igtl_colortable_get_table_size()
igtl_uint64 igtl_export igtl_colortable_get_table_size (igtl_colortable_header * header)
igtl_colortable_get_data_size(n) calculates the size of body based on the index and map types. The size of body is used in the message header. igtl_colortable_get_data_n(size) calculates the number of images in the body, based on the body size. This function may be used when a client program parses a COLORTABLE message.
Definition at line 18 of file igtl_colortable.c.
References IGTL_COLORTABLE_INDEX_UINT8, IGTL_COLORTABLE_MAP_UINT16, IGTL_COLORTABLE_MAP_UINT8, igtl_export, igtl_colortable_header::indexType, and igtl_colortable_header::mapType.
Referenced by igtl::ColorTableMessage::GetColorTableSize(), and igtl_colortable_get_crc().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012