igtl Namespace Reference
Main Page Namespace List Class Hierarchy Alphabetical List Compound List File List Namespace Members Compound Members File Members
igtl Namespace Reference
The "igtl" namespace contains all OpenIGTLink classes. There are several nested namespaces within the igtl:: namespace.
Data Structures
struct AomInterfaceDecoder
struct AomInterfaceEncoder
class Array
class ArrayBase
class BindMessage
A class for the BIND message type.
class BindMessageBase
class CapabilityMessage
class ClientDest
class ClientSocket
class ColorTableMessage
A class for the COLORT message type.
class CommandMessage
class ConditionVariable
A thread synchronization object used to suspend execution until some condition on shared data is met.
class CreateObjectFunction
CreateObjectFunction is used to create callback functions that create IGTL Objects for use with the igtl::ObjectFactory.
class CreateObjectFunctionBase
Define API for object creation callback functions.
class FastMutexLock
Critical section locking class.
class GeneralSocket
class IGTL_EXPORT Socket
class GenericDecoder
class GenericEncoder
class GetBindMessage
class GetColorTableMessage
A class for the GET_COLORT message type.
class GetImageMessage
class GetImageMessage2
class GetImageMetaMessage
A class for the GET_IMGMETA message type.
class GetLabelMetaMessage
A class for the GET_LBMETA message type.
class GetPointMessage
A class for the GET_POINT message type.
class GetPolyDataMessage
A class for the GET_POLYDATA message type.
class GetStatusMessage
A class for the GET_STATUS message type.
class GetTrajectoryMessage
A class for the GET_TRAJ message type.
class GetTransformMessage
A class for the GET_TRANS message type.
class GetVideoMetaMessage
A class for the GET_IMGMETA message type.
class GroupDest
class H264Decoder
class H264Encoder
class H265Decoder
class H265Encoder
class HeaderOnlyMessageBase
A class for header-only message types, which are used for querying.
class I420Decoder
class I420Encoder
class igtlAV1Decoder
class igtlAV1Encoder
class ImageMessage
class ImageMessage2
class ImageMetaElement
A class to manage meta data of images.
class ImageMetaMessage
class LabelMetaElement
class LabelMetaMessage
struct LayerpEncCtx_s
class LightObject
Light weight base class for most igtl classes.
class MessageBase
class MessageFactory
class MessageHandler
class MessageRTPWrapper
class MultiThreader
class MutexLock
Mutual exclusion locking class.
class NDArrayMessage
class Object
Base class for most igtl classes.
class ObjectFactory
Create instances of a class.
class ObjectFactoryBase
Create instances of classes using an object factory.
class OStringStream
class OverRideMap
Internal implementation class for ObjectFactorBase.
class PacketBuffer
class PointElement
A class to manage point information.
class PointMessage
class PolyDataAttribute
Attribute class used for passing attribute data.
class PolyDataCellArray
class PolyDataMessage
A class for the POLYDATA message type.
class PolyDataPointArray
class PositionMessage
class QuaternionTrackingDataElement
class QuaternionTrackingDataMessage
class QueryMessage
THe STRING message type is used for transferring a character string. It supports character strings up to 65535 bytes.
class ReadConfigFile
struct ReadSocketAndPush
class ReorderBuffer
class RTSBindMessage
class RTSCommandMessage
class RTSPolyDataMessage
A class for the RTS_POLYDATA message type.
class RTSQuaternionTrackingDataMessage
A class for the RTS_QTDATA message type.
class RTSTrackingDataMessage
A class for the RTS_TDATA message type.
class SensorMessage
struct serverPointer
class ServerSocket
class SessionManager
class SimpleFastMutexLock
Critical section locking class that can be allocated on the stack.
class SimpleMutexLock
Simple mutual exclusion locking class.
class SmartPointer
Implements transparent reference counting.
class Socket
class IGTL_EXPORT Socket
struct SourcePicture
class StartBindMessage
class StartPolyDataMessage
A class for the STT_POLYDATA message type.
class StartQuaternionTrackingDataMessage
A class for the STT_QTDATA message type.
class StartTrackingDataMessage
A class for the STT_TDATA message type.
class StartVideoMessage
A class for the STT_TDATA message type.
class StatusMessage
class StopBindMessage
class StopImageMessage
class StopPolyDataMessage
A class for the STP_POLYDATA message type.
class StopQuaternionTrackingDataMessage
class StopTrackingDataMessage
A class for the STP_TDATA message type.
class StopVideoMessage
class StringMessage
THe STRING message type is used for transferring a character string. It supports character strings up to 65535 bytes.
class TimeStamp
class TrackingDataElement
class TrackingDataMessage
class TrajectoryElement
TrajectoryElement class is used to manage a trajectory in TrajectoryMessage class.
class TrajectoryMessage
class TransformMessage
class UDPClientSocket
class UDPServerSocket
class Unit
class UnWrappedMessage
class VideoMessage
class VideoMessageHeader
class VideoMetaElement
A class to manage meta data of images.
class VideoMetaMessage
class VideoStreamIGTLinkReceiver
class VideoStreamIGTLinkServer
class VP9Decoder
class VP9Encoder
struct VpxInterfaceDecoder
struct VpxInterfaceEncoder
struct Wrapper
Typedefs
typedef struct igtl::AomInterfaceDecoder AomInterfaceDecoder
typedef struct igtl::AomInterfaceEncoder AomInterfaceEncoder
typedef int FastMutexType
typedef ObjectFactoryBase *(* IGTL_LOAD_FUNCTION) ()
typedef igtlUint64 igtlUnit
typedef float Matrix4x4[4][4]
typedef class MessageBase MessageHeader
typedef int MultiThreaderIDType
typedef int MutexType
typedef struct igtl::LayerpEncCtx_s SLayerPEncCtx
typedef std::multimap< std::string, ObjectFactoryBase::OverrideInformation > StringOverMapType
typedef void(* ThreadFunctionType) (void *)
typedef int ThreadProcessIDType
typedef struct igtl::VpxInterfaceDecoder VpxInterfaceDecoder
typedef struct igtl::VpxInterfaceEncoder VpxInterfaceEncoder
Enumerations
enum cmRETURN {
ResultSuccess ,
InitParaError ,
UnknownReason ,
MallocMemeError ,
InitExpected ,
UnsupportedData
}
Enumerate return type.
enum H264VideoFrameType {
H264FrameTypeInvalid ,
H264FrameTypeIDR ,
H264FrameTypeI ,
H264FrameTypeP ,
H264FrameTypeSkip ,
H264FrameTypeIPMixed
}
Enumerate video frame type This is H264 related frame types.
enum H265VideoFrameType {
H265FrameTypeInvalid ,
H265FrameTypeIDR ,
H265FrameTypeI ,
H265FrameTypeP ,
H265FrameTypeSkip ,
H265FrameTypeIPMixed
}
Enumerate video frame type This is H265 related frame types.
enum VideoFormatType {
FormatI420 = 1 ,
FormatI444 = 2
}
Enumerate the type of video format, Only YV12, I420, I422, I444 images are supported in the codec. RGB format are not supported yet.
enum VideoFrameType {
FrameTypeInvalid ,
FrameTypeKey ,
FrameTypeIntraPrediction ,
FrameTypeInterPrediction ,
FrameTypeSkip ,
FrameTypeUnKnown
}
Functions
std::vector< igtlFloat32 >::const_iterator begin (const PolyDataAttribute &list)
std::vector< igtlFloat32 >::iterator begin (PolyDataAttribute &list)
Implement support for C++11 ranged for loops.
void IGTLCommon_EXPORT Cross (float *a, float *b, float *c)
std::vector< igtlFloat32 >::const_iterator end (const PolyDataAttribute &list)
std::vector< igtlFloat32 >::iterator end (PolyDataAttribute &list)
void IGTLCommon_EXPORT IdentityMatrix (igtl::Matrix4x4 &matrix)
Initialize a 4-by-4 matrix as an identity matrix.
static int IGTLProtocolToHeaderLookup (int igtlProtocolVersion)
igtlRangeBasedForBodyMacro (PolyDataCellArray, std::vector< PolyDataCellArray::Cell >, m_Data)
Implement support for C++11 ranged for loops.
igtlRangeBasedForBodyMacro (PolyDataPointArray, std::vector< PolyDataPointArray::Point >, m_Data)
Implement support for C++11 ranged for loops.
igtlRangeBasedForHeaderExternalMacro (PolyDataCellArray, std::vector< PolyDataCellArray::Cell >, IGTLCommon_EXPORT)
Implement support for C++11 ranged for loops.
igtlRangeBasedForHeaderExternalMacro (PolyDataPointArray, std::vector< PolyDataPointArray::Point >, IGTLCommon_EXPORT)
void IGTLCommon_EXPORT MatrixToQuaternion (Matrix4x4 &m, float *q)
bool operator< (const ObjectFactoryBase::OverrideInformation &rhs, const ObjectFactoryBase::OverrideInformation &lhs)
std::ostream & operator<< (std::ostream &os, const LightObject &o)
template<typename T>
std::ostream & operator<< (std::ostream &os, SmartPointer< T > p)
bool operator== (const ObjectFactoryBase::OverrideInformation &rhs, const ObjectFactoryBase::OverrideInformation &lhs)
void IGTLCommon_EXPORT PrintMatrix (igtl::Matrix4x4 &matrix)
Prints out a 4-by-4 matrix on the standard output.
void IGTLCommon_EXPORT PrintVector3 (float v[3])
Prints out a 3-element vector on the standard output.
void IGTLCommon_EXPORT PrintVector3 (float x, float y, float z)
Prints out a 3-element vector on the standard output.
void IGTLCommon_EXPORT PrintVector4 (float v[4])
Prints out a 4-element vector on the standard output.
void IGTLCommon_EXPORT PrintVector4 (float x, float y, float z, float w)
Prints out a 4-element vector on the standard output.
void IGTLCommon_EXPORT QuaternionToMatrix (float *q, Matrix4x4 &m)
std::vector< igtlFloat32 >::const_reverse_iterator rbegin (const PolyDataAttribute &list)
std::vector< igtlFloat32 >::reverse_iterator rbegin (PolyDataAttribute &list)
std::vector< igtlFloat32 >::const_reverse_iterator rend (const PolyDataAttribute &list)
std::vector< igtlFloat32 >::reverse_iterator rend (PolyDataAttribute &list)
void IGTLCommon_EXPORT SetPolyDataInfo (igtl_polydata_info *info, PolyDataMessage *pdm)
void IGTLCommon_EXPORT SetPolyDataInfoAttribute (igtl_polydata_info *info, PolyDataMessage *pdm)
static void SigIntHandler (int a)
void Sleep (int milliseconds)
vcl_size_t Strnlen (const char *s, vcl_size_t maxlen)
static void * ThreadFunctionReadFrameFromFile (void *ptr)
void * ThreadFunctionReadSocket (void *ptr)
static void * ThreadFunctionSendPacket (void *ptr)
static void * ThreadFunctionServer (void *ptr)
void * ThreadFunctionUnWrap (void *ptr)
template<typename T>
std::string ToString (T variable)
void IGTLCommon_EXPORT UnSetPolyDataInfoAttribute (igtl_polydata_info *info)
void WriteTimeInfo (unsigned char *UDPPacket, int totMsgLen, VideoStreamIGTLinkReceiver *receiver)
Variables
static const AomInterfaceDecoder AV1StaticDecoder [] = { { &aom_codec_av1_dx } }
static const AomInterfaceEncoder AV1StaticEncoder [] = {{&aom_codec_av1_cx}}
static int g_iCtrlC = 0
igtl_int32 iFrameCountTotal = 0
static int MultiThreaderGlobalDefaultNumberOfThreads = 0
static int MultiThreaderGlobalMaximumNumberOfThreads = 0
static const VpxInterfaceDecoder vp9StaticDecoder [] = {{&vpx_codec_vp9_dx}}
static const VpxInterfaceEncoder vp9StaticEncoder [] = {{&vpx_codec_vp9_cx}}
Detailed Description
The "igtl" namespace contains all OpenIGTLink classes. There are several nested namespaces within the igtl:: namespace.
igtlMacro.h defines standard system-wide macros, constants, and other parameters. One of its most important functions is to define macros used to interface to instance variables in a standard fashion. For example, these macros manage modified time, debugging information, and provide a standard interface to set and get instance variables. Macros are available for built-in types; for string classe; vector arrays; object pointers; and debug, warning, and error printout information.
\copy Copyright (c) 2013, Cisco Systems All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Typedef Documentation
AomInterfaceDecoder
typedef struct igtl::AomInterfaceDecoder igtl::AomInterfaceDecoder
AomInterfaceEncoder
typedef struct igtl::AomInterfaceEncoder igtl::AomInterfaceEncoder
FastMutexType
typedef int igtl::FastMutexType
Definition at line 71 of file igtlSimpleFastMutexLock.h.
IGTL_LOAD_FUNCTION
typedef ObjectFactoryBase *(* igtl::IGTL_LOAD_FUNCTION) ()
Load all libraries in IGTL_AUTOLOAD_PATH follow PATH conventions find PathSeparator in LoadPath Move past separator A file scope helper function to concat path and file into a full path make sure the end of path is a separator A file scope typedef to make the cast code to the load function cleaner to read.
Definition at line 298 of file igtlObjectFactoryBase.cxx.
igtlUnit
typedef igtlUint64 igtl::igtlUnit
Definition at line 28 of file igtlUnit.h.
Matrix4x4
typedef float igtl::Matrix4x4[4][4]
Definition at line 23 of file igtlMath.h.
MessageHeader
typedef class MessageBase igtl::MessageHeader
Definition at line 74 of file igtlMessageHeader.h.
MultiThreaderIDType
typedef int igtl::MultiThreaderIDType
Definition at line 127 of file igtlMultiThreader.h.
MutexType
typedef int igtl::MutexType
Definition at line 69 of file igtlMutexLock.h.
SLayerPEncCtx
typedef struct igtl::LayerpEncCtx_s igtl::SLayerPEncCtx
StringOverMapType
typedef std::multimap<std::string, ObjectFactoryBase::OverrideInformation> igtl::StringOverMapType
Definition at line 98 of file igtlObjectFactoryBase.cxx.
ThreadFunctionType
typedef void(* igtl::ThreadFunctionType) (void *)
Definition at line 125 of file igtlMultiThreader.h.
ThreadProcessIDType
typedef int igtl::ThreadProcessIDType
Definition at line 126 of file igtlMultiThreader.h.
VpxInterfaceDecoder
typedef struct igtl::VpxInterfaceDecoder igtl::VpxInterfaceDecoder
VpxInterfaceEncoder
typedef struct igtl::VpxInterfaceEncoder igtl::VpxInterfaceEncoder
Enumeration Type Documentation
cmRETURN
enum igtl::cmRETURN
Enumerate return type.
Enumerator
ResultSuccess
successful
InitParaError
parameters are invalid
UnknownReason
MallocMemeError
malloc a memory error
InitExpected
initial action is expected
UnsupportedData
Definition at line 50 of file igtlCodecCommonClasses.h.
H264VideoFrameType
enum igtl::H264VideoFrameType
Enumerate video frame type This is H264 related frame types.
Enumerator
H264FrameTypeInvalid
encoder not ready or parameters are invalidate
H264FrameTypeIDR
IDR frame in H.264.
H264FrameTypeI
I frame type.
H264FrameTypeP
P frame type.
H264FrameTypeSkip
skip the frame based encoder kernel
H264FrameTypeIPMixed
a frame where I and P slices are mixing, not supported yet
Definition at line 93 of file igtlH264Encoder.h.
H265VideoFrameType
enum igtl::H265VideoFrameType
Enumerate video frame type This is H265 related frame types.
Enumerator
H265FrameTypeInvalid
encoder not ready or parameters are invalidate
H265FrameTypeIDR
IDR frame in H.264.
H265FrameTypeI
I frame type.
H265FrameTypeP
P frame type.
H265FrameTypeSkip
skip the frame based encoder kernel
H265FrameTypeIPMixed
a frame where I and P slices are mixing, not supported yet
Definition at line 59 of file igtlH265Encoder.h.
VideoFormatType
enum igtl::VideoFormatType
Enumerate the type of video format, Only YV12, I420, I422, I444 images are supported in the codec. RGB format are not supported yet.
Enumerator
FormatI420
FormatI444
Definition at line 33 of file igtlCodecCommonClasses.h.
VideoFrameType
enum igtl::VideoFrameType
Enumerator
FrameTypeInvalid
encoder not ready or parameters are invalidate
FrameTypeKey
Key Frame.
FrameTypeIntraPrediction
Intra Prediction Frame.
FrameTypeInterPrediction
Inter Prediction Frame.
FrameTypeSkip
skip the frame based encoder kernel
FrameTypeUnKnown
Definition at line 38 of file igtlCodecCommonClasses.h.
Function Documentation
begin() [1/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::const_iterator igtl::begin (const PolyDataAttribute & list)
Definition at line 487 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::begin().
begin() [2/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::iterator igtl::begin (PolyDataAttribute & list)
Implement support for C++11 ranged for loops.
Definition at line 479 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::begin().
Cross()
void IGTLCommon_EXPORT igtl::Cross (float * a, float * b, float * c)
Calculates the cross products of 3-element vectors 'b' and 'c'. The result is substituted into a 3-element vector a.
Definition at line 154 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
end() [1/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::const_iterator igtl::end (const PolyDataAttribute & list)
Definition at line 491 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::end().
end() [2/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::iterator igtl::end (PolyDataAttribute & list)
Definition at line 483 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::end().
Referenced by igtl::ObjectFactoryBase::CreateObject(), igtl::ObjectFactoryBase::Disable(), igtl::ObjectFactoryBase::GetEnableFlag(), and igtl::ObjectFactoryBase::SetEnableFlag().
IdentityMatrix()
void IGTLCommon_EXPORT igtl::IdentityMatrix (igtl::Matrix4x4 & matrix)
Initialize a 4-by-4 matrix as an identity matrix.
Definition at line 161 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
Referenced by igtl::TrackingDataElement::TrackingDataElement(), and igtl::TrackingDataMessage::UnpackContent().
IGTLProtocolToHeaderLookup()
int igtl::IGTLProtocolToHeaderLookup (int igtlProtocolVersion) static
This function contains the extrinsic knowledge of the protocol version history so that programmers don't need to know which protocol version uses which header version
Definition at line 41 of file igtlCommon.h.
References IGTL_HEADER_VERSION_1, and IGTL_HEADER_VERSION_2.
igtlRangeBasedForBodyMacro() [1/2]
igtl::igtlRangeBasedForBodyMacro (PolyDataCellArray , std::vector< PolyDataCellArray::Cell > , m_Data)
Implement support for C++11 ranged for loops.
igtlRangeBasedForBodyMacro() [2/2]
igtl::igtlRangeBasedForBodyMacro (PolyDataPointArray , std::vector< PolyDataPointArray::Point > , m_Data)
Implement support for C++11 ranged for loops.
igtlRangeBasedForHeaderExternalMacro() [1/2]
igtl::igtlRangeBasedForHeaderExternalMacro (PolyDataCellArray , std::vector< PolyDataCellArray::Cell > , IGTLCommon_EXPORT)
Implement support for C++11 ranged for loops.
References IGTLCommon_EXPORT.
igtlRangeBasedForHeaderExternalMacro() [2/2]
igtl::igtlRangeBasedForHeaderExternalMacro (PolyDataPointArray , std::vector< PolyDataPointArray::Point > , IGTLCommon_EXPORT)
References IGTLCommon_EXPORT.
MatrixToQuaternion()
void IGTLCommon_EXPORT igtl::MatrixToQuaternion (Matrix4x4 & m, float * q)
Converts a 3-by-3 rotation matrix a quaternion. Only the 3-by-3 rotation matrix part in the 4-by-4 matrix is used.
Definition at line 98 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
operator<()
bool igtl::operator< (const ObjectFactoryBase::OverrideInformation & rhs, const ObjectFactoryBase::OverrideInformation & lhs)
Add this for the SGI compiler which does not seem to provide a default implementation as it should.
Definition at line 81 of file igtlObjectFactoryBase.cxx.
References igtl::ObjectFactoryBase::OverrideInformation::m_Description, and igtl::ObjectFactoryBase::OverrideInformation::m_OverrideWithName.
operator<<() [1/2]
std::ostream & igtl::operator<< (std::ostream & os, const LightObject & o)
This operator allows all subclasses of LightObject to be printed via <<. It in turn invokes the Print method, which in turn will invoke the PrintSelf method that all objects should define, if they have anything interesting to print out.
Definition at line 271 of file igtlLightObject.cxx.
References igtl::LightObject::Print().
operator<<() [2/2]
template<typename T> std::ostream & igtl::operator<< (std::ostream & os, SmartPointer< T > p)
Definition at line 167 of file igtlSmartPointer.h.
References igtl::SmartPointer< TObjectType >::Print().
operator==()
bool igtl::operator== (const ObjectFactoryBase::OverrideInformation & rhs, const ObjectFactoryBase::OverrideInformation & lhs)
Add this for the SGI compiler which does not seem to provide a default implementation as it should.
Definition at line 70 of file igtlObjectFactoryBase.cxx.
References igtl::ObjectFactoryBase::OverrideInformation::m_Description, and igtl::ObjectFactoryBase::OverrideInformation::m_OverrideWithName.
PrintMatrix()
void IGTLCommon_EXPORT igtl::PrintMatrix (igtl::Matrix4x4 & matrix)
Prints out a 4-by-4 matrix on the standard output.
Definition at line 22 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
PrintVector3() [1/2]
void IGTLCommon_EXPORT igtl::PrintVector3 (float v[3])
Prints out a 3-element vector on the standard output.
Definition at line 32 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
PrintVector3() [2/2]
void IGTLCommon_EXPORT igtl::PrintVector3 (float x, float y, float z)
Prints out a 3-element vector on the standard output.
Definition at line 37 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
PrintVector4() [1/2]
void IGTLCommon_EXPORT igtl::PrintVector4 (float v[4])
Prints out a 4-element vector on the standard output.
Definition at line 42 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
PrintVector4() [2/2]
void IGTLCommon_EXPORT igtl::PrintVector4 (float x, float y, float z, float w)
Prints out a 4-element vector on the standard output.
Definition at line 47 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
QuaternionToMatrix()
void IGTLCommon_EXPORT igtl::QuaternionToMatrix (float * q, Matrix4x4 & m)
Converts a quaternion to a 3-by-3 rotation matrix. Only the 3-by-3 rotation matrix part in the 4-by-4 matrix is used.
Definition at line 52 of file igtlMath.cxx.
References IGTLCommon_EXPORT.
rbegin() [1/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::const_reverse_iterator igtl::rbegin (const PolyDataAttribute & list)
Definition at line 504 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::rbegin().
rbegin() [2/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::reverse_iterator igtl::rbegin (PolyDataAttribute & list)
Definition at line 496 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::rbegin().
rend() [1/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::const_reverse_iterator igtl::rend (const PolyDataAttribute & list)
Definition at line 508 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::rend().
rend() [2/2]
IGTLCommon_EXPORT std::vector< igtlFloat32 >::reverse_iterator igtl::rend (PolyDataAttribute & list)
Definition at line 500 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataAttribute::rend().
SetPolyDataInfo()
void IGTLCommon_EXPORT igtl::SetPolyDataInfo (igtl_polydata_info * info, PolyDataMessage * pdm)
Definition at line 527 of file igtlPolyDataMessage.cxx.
References igtl::PolyDataMessage::GetNumberOfAttributes(), igtl_polydata_info::header, igtl_polydata_init_info(), IGTLCommon_EXPORT, igtl_polydata_header::nattributes, igtl_polydata_header::nlines, igtl_polydata_header::npoints, igtl_polydata_header::npolygons, igtl_polydata_header::ntriangle_strips, igtl_polydata_header::nvertices, igtl_polydata_header::size_lines, igtl_polydata_header::size_polygons, igtl_polydata_header::size_triangle_strips, and igtl_polydata_header::size_vertices.
Referenced by igtl::PolyDataMessage::CalculateContentBufferSize(), and igtl::PolyDataMessage::PackContent().
SetPolyDataInfoAttribute()
void IGTLCommon_EXPORT igtl::SetPolyDataInfoAttribute (igtl_polydata_info * info, PolyDataMessage * pdm)
Definition at line 590 of file igtlPolyDataMessage.cxx.
References igtl_polydata_info::attributes, igtl_polydata_attribute::data, igtl::PolyDataMessage::GetAttribute(), igtl::PolyDataAttribute::GetData(), igtl::PolyDataAttribute::GetName(), igtl::PolyDataAttribute::GetNumberOfComponents(), igtl::PolyDataAttribute::GetSize(), igtl::PolyDataAttribute::GetType(), igtl_polydata_info::header, IGTLCommon_EXPORT, igtl_polydata_attribute::n, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_attribute::ncomponents, and igtl_polydata_attribute::type.
Referenced by igtl::PolyDataMessage::CalculateContentBufferSize(), and igtl::PolyDataMessage::PackContent().
SigIntHandler()
void igtl::SigIntHandler (int a) static
Definition at line 104 of file igtlH264Encoder.cxx.
References g_iCtrlC.
Referenced by igtl::H264Encoder::H264Encoder().
Sleep()
void IGTLCommon_EXPORT igtl::Sleep (int millisecond)
Stop the program for the duration specified in millisecond The maximum dulation is
Definition at line 29 of file igtlOSUtil.cxx.
References Sleep().
Referenced by igtl::VideoStreamIGTLinkServer::EncodeFile(), igtl::GeneralSocket::Receive(), igtl::Socket::Receive(), igtl::GeneralSocket::ReceiveUDP(), igtl::VideoStreamIGTLinkReceiver::RunOnTCPSocket(), Sleep(), igtl::VideoStreamIGTLinkServer::StartReadFrameThread(), igtl::VideoStreamIGTLinkServer::StartSendPacketThread(), igtl::VideoStreamIGTLinkServer::StartTCPServer(), ThreadFunctionReadFrameFromFile(), ThreadFunctionSendPacket(), ThreadFunctionServer(), and webSocketServer::WaitForConnection().
Strnlen()
vcl_size_t IGTLCommon_EXPORT igtl::Strnlen (const char * s, vcl_size_t maxlen)
Just in case strnlen() is not defined (e.g. Mac OS X Snow Leopard)
Definition at line 54 of file igtlOSUtil.cxx.
Referenced by igtl::CapabilityMessage::UnpackContent().
ThreadFunctionReadFrameFromFile()
void * igtl::ThreadFunctionReadFrameFromFile (void * ptr) static
Definition at line 450 of file igtlVideoStreamIGTLinkServer.cxx.
References igtl::VideoStreamIGTLinkServer::glockInFrame, igtl::VideoStreamIGTLinkServer::incommingFrames, igtl::VideoStreamIGTLinkServer::interval, igtl::VideoStreamIGTLinkServer::iTotalFrameToEncode, igtl::SimpleMutexLock::Lock(), igtl::SourcePicture::picHeight, igtl::SourcePicture::picWidth, igtl::VideoStreamIGTLinkServer::pSrcPic, igtl::serverPointer::server, Sleep(), igtl::VideoStreamIGTLinkServer::strSeqFile, igtl::SimpleMutexLock::Unlock(), and igtl::MultiThreader::ThreadInfo::UserData.
Referenced by igtl::VideoStreamIGTLinkServer::StartReadFrameThread().
ThreadFunctionReadSocket()
void * igtl::ThreadFunctionReadSocket (void * ptr)
Definition at line 63 of file igtlVideoStreamIGTLinkReceiver.cxx.
References igtl::ReadSocketAndPush::clientSocket, igtl::ReadSocketAndPush::receiver, RTP_HEADER_LENGTH, RTP_PAYLOAD_LENGTH, igtl::MultiThreader::ThreadInfo::UserData, igtl::ReadSocketAndPush::wrapper, and WriteTimeInfo().
Referenced by igtl::VideoStreamIGTLinkReceiver::RunOnUDPSocket().
ThreadFunctionSendPacket()
void * igtl::ThreadFunctionSendPacket (void * ptr) static
Definition at line 529 of file igtlVideoStreamIGTLinkServer.cxx.
References igtl::VideoStreamIGTLinkServer::encodedFrames, igtl::VideoStreamIGTLinkServer::glock, igtl::SimpleMutexLock::Lock(), igtl::VideoStreamIGTLinkServer::encodedFrame::messageDataLength, igtl::VideoStreamIGTLinkServer::encodedFrame::messagePackPointer, igtl::VideoStreamIGTLinkServer::rtpWrapper, igtl::serverPointer::server, igtl::VideoStreamIGTLinkServer::serverUDPSocket, Sleep(), igtl::VideoStreamIGTLinkServer::socket, igtl::VideoStreamIGTLinkServer::transportMethod, igtl::SimpleMutexLock::Unlock(), igtl::MultiThreader::ThreadInfo::UserData, igtl::VideoStreamIGTLinkServer::UseTCP, and igtl::VideoStreamIGTLinkServer::UseUDP.
Referenced by igtl::VideoStreamIGTLinkServer::StartSendPacketThread().
ThreadFunctionServer()
void * igtl::ThreadFunctionServer (void * ptr) static
Definition at line 223 of file igtlVideoStreamIGTLinkServer.cxx.
References igtl::VideoStreamIGTLinkServer::codecName, igtl::VideoStreamIGTLinkServer::conditionVar, igtl::VideoStreamIGTLinkServer::glock, IGTL_VIDEO_CODEC_NAME_SIZE, igtl::VideoStreamIGTLinkServer::interval, igtl::SmartPointer< TObjectType >::IsNotNull(), igtl::SimpleMutexLock::Lock(), igtl::LightObject::New(), igtl::VideoStreamIGTLinkServer::serverConnected, igtl::VideoStreamIGTLinkServer::serverIsSet, igtl::VideoStreamIGTLinkServer::serverPortNumber, igtl::VideoStreamIGTLinkServer::serverSocket, Sleep(), igtl::VideoStreamIGTLinkServer::socket, igtl::SimpleMutexLock::Unlock(), igtl::MultiThreader::ThreadInfo::UserData, and igtl::VideoStreamIGTLinkServer::waitSTTCommand.
Referenced by igtl::VideoStreamIGTLinkServer::StartTCPServer().
ThreadFunctionUnWrap()
void * igtl::ThreadFunctionUnWrap (void * ptr)
Definition at line 33 of file igtlVideoStreamIGTLinkReceiver.cxx.
References igtl::VideoStreamIGTLinkReceiver::GetDeviceName(), igtl::Wrapper::receiver, igtl::MultiThreader::ThreadInfo::UserData, and igtl::Wrapper::wrapper.
Referenced by igtl::VideoStreamIGTLinkReceiver::RunOnUDPSocket().
ToString()
template<typename T> std::string igtl::ToString (T variable)
Definition at line 21 of file igtlH265Encoder.cxx.
Referenced by igtl::H265Encoder::FillSpecificParameters(), and igtl::H265Encoder::SetSpeed().
UnSetPolyDataInfoAttribute()
void IGTLCommon_EXPORT igtl::UnSetPolyDataInfoAttribute (igtl_polydata_info * info)
Definition at line 629 of file igtlPolyDataMessage.cxx.
References igtl_polydata_info::attributes, igtl_polydata_attribute::data, igtl_polydata_info::header, IGTLCommon_EXPORT, igtl_polydata_attribute::n, igtl_polydata_attribute::name, igtl_polydata_header::nattributes, igtl_polydata_attribute::ncomponents, and igtl_polydata_attribute::type.
Referenced by igtl::PolyDataMessage::CalculateContentBufferSize().
WriteTimeInfo()
void igtl::WriteTimeInfo (unsigned char * UDPPacket, int totMsgLen, VideoStreamIGTLinkReceiver * receiver)
Definition at line 47 of file igtlVideoStreamIGTLinkReceiver.cxx.
References BYTE_SWAP_INT16, BYTE_SWAP_INT32, IGTL_EXTENDED_HEADER_SIZE, IGTL_HEADER_SIZE, igtl_is_little_endian(), and RTP_HEADER_LENGTH.
Referenced by ThreadFunctionReadSocket().
Variable Documentation
AV1StaticDecoder
const AomInterfaceDecoder igtl::AV1StaticDecoder[] = { { &aom_codec_av1_dx } } static
Definition at line 20 of file igtlAV1Decoder.cxx.
Referenced by igtl::igtlAV1Decoder::igtlAV1Decoder().
AV1StaticEncoder
const AomInterfaceEncoder igtl::AV1StaticEncoder[] = {{&aom_codec_av1_cx}} static
Definition at line 21 of file igtlAV1Encoder.cxx.
Referenced by igtl::igtlAV1Encoder::igtlAV1Encoder().
g_iCtrlC
int igtl::g_iCtrlC = 0 static
Definition at line 103 of file igtlH264Encoder.cxx.
Referenced by SigIntHandler().
iFrameCountTotal
igtl_int32 igtl::iFrameCountTotal = 0
Definition at line 87 of file igtlH264Decoder.cxx.
MultiThreaderGlobalDefaultNumberOfThreads
int igtl::MultiThreaderGlobalDefaultNumberOfThreads = 0 static
Definition at line 90 of file igtlMultiThreader.cxx.
Referenced by igtl::MultiThreader::GetGlobalDefaultNumberOfThreads(), and igtl::MultiThreader::SetGlobalDefaultNumberOfThreads().
MultiThreaderGlobalMaximumNumberOfThreads
int igtl::MultiThreaderGlobalMaximumNumberOfThreads = 0 static
Definition at line 73 of file igtlMultiThreader.cxx.
Referenced by igtl::MultiThreader::GetGlobalMaximumNumberOfThreads(), igtl::MultiThreader::GetNumberOfThreads(), igtl::MultiThreader::MultipleMethodExecute(), igtl::MultiThreader::PrintSelf(), igtl::MultiThreader::SetGlobalMaximumNumberOfThreads(), and igtl::MultiThreader::SingleMethodExecute().
vp9StaticDecoder
const VpxInterfaceDecoder igtl::vp9StaticDecoder[] = {{&vpx_codec_vp9_dx}} static
Definition at line 18 of file igtlVP9Decoder.cxx.
Referenced by igtl::VP9Decoder::VP9Decoder().
vp9StaticEncoder
const VpxInterfaceEncoder igtl::vp9StaticEncoder[] = {{&vpx_codec_vp9_cx}} static
Definition at line 21 of file igtlVP9Encoder.cxx.
Referenced by igtl::VP9Encoder::VP9Encoder().
Generated at Tue Sep 9 2025 15:29:14 for OpenIGTLink by 1.14.0 written by Dimitri van Heesch, © 1997-2012